name = "flyology_pgish"
description = "A small read-only Postgres-like server built on Flyology"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
tags = ["example", "postgres", "server", "introspection"]

executables = [
  "flyology_pgish",
  "pgish_extended_client",
  "pgish_tests",
]

[[depends-on]]
flyology_postgres = "*"

[[pins]]
flyology_postgres = { path = "../.." }

[[depends-on]]
flyology_postgres_sql = "*"

[[pins]]
flyology_postgres_sql = { path = "../../sql" }

[[actions]]
type = "test"
command = ["./scripts/test.sh"]
