--  Generated by tools/generate_native_actions.py.  Do not edit.
with Interfaces;
with Flyology.Postgres.SQL.Native.Builders;
with Flyology.Postgres.SQL.Native.Semantics;
with Flyology.Postgres.SQL.Native.Actions_V16_Support;

package body Flyology.Postgres.SQL.Native.Actions_V16_Chunk_04 is

   pragma Style_Checks (Off);
   use type Interfaces.Integer_64;

   function Invoke
     (Build : not null access Builders.Builder; Name : String;
      Arguments : Builders.Semantic_Array) return Builders.Dynamic_Value
      renames Actions_V16_Support.Invoke;

   procedure Reduce
     (Build        : aliased in out Builders.Builder;
      Rule         : Positive;
      Values       : Builders.Semantic_Array;
      Locations    : Builders.Location_Array;
      Result       : in out Builders.Dynamic_Value;
      Location     : in out Integer;
      Parse_Result : in out Builders.Dynamic_Value)
   is
      Build_Access : constant not null access Builders.Builder :=
        Build'Unchecked_Access;
   begin
      case Rule is
         when 534 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "keys", Values (4));
               Build_Access.Set_Field (Locals (1), "including", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Values (7));
               Build_Access.Set_Field (Locals (1), "indexname", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexspace", Values (8));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "processCASbits", (1 => Values (9), 2 => Builders.Number
                       (Interfaces.Integer_64 (Locations (9))), 3 => Builders.Text ("PRIMARY KEY"), 4 =>
                       Builders.Field_Reference (Locals (1), "deferrable"), 5 => Builders.Field_Reference (Locals (1),
                       "initdeferred"), 6 => Builders.No_Value, 7 => Builders.No_Value, 8 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Locals (1);
            end;
         when 535 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "keys", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "including", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexname", Values (3));
               Build_Access.Set_Field (Locals (1), "indexspace", Builders.No_Value);
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "processCASbits", (1 => Values (4), 2 => Builders.Number
                       (Interfaces.Integer_64 (Locations (4))), 3 => Builders.Text ("PRIMARY KEY"), 4 =>
                       Builders.Field_Reference (Locals (1), "deferrable"), 5 => Builders.Field_Reference (Locals (1),
                       "initdeferred"), 6 => Builders.No_Value, 7 => Builders.No_Value, 8 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Locals (1);
            end;
         when 536 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (8));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "access_method", Values (2));
               Build_Access.Set_Field (Locals (1), "exclusions", Values (4));
               Build_Access.Set_Field (Locals (1), "including", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Values (7));
               Build_Access.Set_Field (Locals (1), "indexname", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexspace", Values (8));
               Build_Access.Set_Field (Locals (1), "where_clause", Values (9));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "processCASbits", (1 => Values (10), 2 => Builders.Number
                       (Interfaces.Integer_64 (Locations (10))), 3 => Builders.Text ("EXCLUDE"), 4 =>
                       Builders.Field_Reference (Locals (1), "deferrable"), 5 => Builders.Field_Reference (Locals (1),
                       "initdeferred"), 6 => Builders.No_Value, 7 => Builders.No_Value, 8 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Locals (1);
            end;
         when 537 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (9));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "pktable", Values (7));
               Build_Access.Set_Field (Locals (1), "fk_attrs", Values (4));
               Build_Access.Set_Field (Locals (1), "pk_attrs", Values (8));
               Build_Access.Set_Field (Locals (1), "fk_matchtype", Values (9));
               Build_Access.Set_Field (Locals (1), "fk_upd_action", Build_Access.Field (Values (10),
                  "updateAction.action"));
               Build_Access.Set_Field (Locals (1), "fk_del_action", Build_Access.Field (Values (10),
                  "deleteAction.action"));
               Build_Access.Set_Field (Locals (1), "fk_del_set_cols", Build_Access.Field (Values (10),
                  "deleteAction.cols"));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "processCASbits", (1 => Values (11), 2 => Builders.Number
                       (Interfaces.Integer_64 (Locations (11))), 3 => Builders.Text ("FOREIGN KEY"), 4 =>
                       Builders.Field_Reference (Locals (1), "deferrable"), 5 => Builders.Field_Reference (Locals (1),
                       "initdeferred"), 6 => Builders.Field_Reference (Locals (1), "skip_validation"), 7 =>
                       Builders.No_Value, 8 => Builders.No_Value));
               begin
                  null;
               end;
               Build_Access.Set_Field (Locals (1), "initially_valid", Semantics.Unary ("!", Build_Access.Field (Locals
                  (1), "skip_validation")));
               Result := Locals (1);
            end;
         when 538 =>
               Result := Builders.Number (1);
         when 539 =>
               Result := Builders.Number (0);
         when 540 =>
               Result := Values (2);
         when 541 =>
               Result := Builders.No_Value;
         when 542 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 543 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 544 =>
               Result := Invoke (Build_Access, "makeString", (1 => Values (1)));
         when 545 =>
               Result := Values (3);
         when 546 =>
               Result := Builders.No_Value;
         when 547 =>
               Result := Builders.Number (102);
         when 548 =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("MATCH PARTIAL not yet implemented"));
               Result := Builders.Number (112);
         when 549 =>
               Result := Builders.Number (115);
         when 550 =>
               Result := Builders.Number (115);
         when 551 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 552 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 553 =>
               Result := Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 => Values (1), 3 =>
                  Values (3)));
         when 554 =>
               Result := Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 => Values (1), 3 =>
                  Values (5)));
         when 555 =>
               Result := Values (3);
         when 556 =>
               Result := Builders.No_Value;
         when 557 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyActions");
               Build_Access.Set_Field (Locals (1), "updateAction", Values (1));
               Build_Access.Set_Field (Locals (1), "deleteAction", Build_Access.New_Object ("__KeyAction"));
               Build_Access.Set_Field (Locals (1), "deleteAction.action", Builders.Number (97));
               Build_Access.Set_Field (Locals (1), "deleteAction.cols", Builders.No_Value);
               Result := Locals (1);
            end;
         when 558 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyActions");
               Build_Access.Set_Field (Locals (1), "updateAction", Build_Access.New_Object ("__KeyAction"));
               Build_Access.Set_Field (Locals (1), "updateAction.action", Builders.Number (97));
               Build_Access.Set_Field (Locals (1), "updateAction.cols", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "deleteAction", Values (1));
               Result := Locals (1);
            end;
         when 559 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyActions");
               Build_Access.Set_Field (Locals (1), "updateAction", Values (1));
               Build_Access.Set_Field (Locals (1), "deleteAction", Values (2));
               Result := Locals (1);
            end;
         when 560 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyActions");
               Build_Access.Set_Field (Locals (1), "updateAction", Values (2));
               Build_Access.Set_Field (Locals (1), "deleteAction", Values (1));
               Result := Locals (1);
            end;
         when 561 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyActions");
               Build_Access.Set_Field (Locals (1), "updateAction", Build_Access.New_Object ("__KeyAction"));
               Build_Access.Set_Field (Locals (1), "updateAction.action", Builders.Number (97));
               Build_Access.Set_Field (Locals (1), "updateAction.cols", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "deleteAction", Build_Access.New_Object ("__KeyAction"));
               Build_Access.Set_Field (Locals (1), "deleteAction.action", Builders.Number (97));
               Build_Access.Set_Field (Locals (1), "deleteAction.cols", Builders.No_Value);
               Result := Locals (1);
            end;
         when 562 =>
               if Semantics.Truth (Build_Access.Field (Values (3), "cols")) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("a column list with %s is only supported for ON DELETE actions"));
               end if;
               Result := Values (3);
         when 563 =>
               Result := Values (3);
         when 564 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyAction");
               Build_Access.Set_Field (Locals (1), "action", Builders.Number (97));
               Build_Access.Set_Field (Locals (1), "cols", Builders.No_Value);
               Result := Locals (1);
            end;
         when 565 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyAction");
               Build_Access.Set_Field (Locals (1), "action", Builders.Number (114));
               Build_Access.Set_Field (Locals (1), "cols", Builders.No_Value);
               Result := Locals (1);
            end;
         when 566 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyAction");
               Build_Access.Set_Field (Locals (1), "action", Builders.Number (99));
               Build_Access.Set_Field (Locals (1), "cols", Builders.No_Value);
               Result := Locals (1);
            end;
         when 567 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyAction");
               Build_Access.Set_Field (Locals (1), "action", Builders.Number (110));
               Build_Access.Set_Field (Locals (1), "cols", Values (3));
               Result := Locals (1);
            end;
         when 568 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__KeyAction");
               Build_Access.Set_Field (Locals (1), "action", Builders.Number (100));
               Build_Access.Set_Field (Locals (1), "cols", Values (3));
               Result := Locals (1);
            end;
         when 569 =>
               Result := Values (3);
         when 570 =>
               Result := Builders.No_Value;
         when 571 =>
               Result := Values (1);
         when 572 =>
               Result := Builders.No_Value;
         when 573 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionSpec");
               Build_Access.Set_Field (Locals (1), "strategy", Invoke (Build_Access, "parsePartitionStrategy", (1 =>
                  Values (3))));
               Build_Access.Set_Field (Locals (1), "partParams", Values (5));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 574 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 575 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 576 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionElem");
               Build_Access.Set_Field (Locals (1), "name", Values (1));
               Build_Access.Set_Field (Locals (1), "expr", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "collation", Values (2));
               Build_Access.Set_Field (Locals (1), "opclass", Values (3));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 577 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionElem");
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "expr", Values (1));
               Build_Access.Set_Field (Locals (1), "collation", Values (2));
               Build_Access.Set_Field (Locals (1), "opclass", Values (3));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 578 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionElem");
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "expr", Values (2));
               Build_Access.Set_Field (Locals (1), "collation", Values (4));
               Build_Access.Set_Field (Locals (1), "opclass", Values (5));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 579 =>
               Result := Values (2);
         when 580 =>
               Result := Builders.No_Value;
         when 581 =>
               Result := Values (2);
         when 582 =>
               Result := Builders.No_Value;
         when 583 =>
               Result := Builders.No_Value;
         when 584 =>
               Result := Builders.Number (3);
         when 585 =>
               Result := Builders.Number (2);
         when 586 =>
               Result := Builders.Number (1);
         when 587 =>
               Result := Builders.Number (0);
         when 588 =>
               Result := Values (2);
         when 589 =>
               Result := Builders.No_Value;
         when 590 =>
               Result := Values (4);
         when 591 =>
               Result := Builders.No_Value;
         when 592 =>
               Result := Values (3);
         when 593 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStatsStmt");
               Build_Access.Set_Field (Locals (1), "defnames", Values (3));
               Build_Access.Set_Field (Locals (1), "stat_types", Values (4));
               Build_Access.Set_Field (Locals (1), "exprs", Values (6));
               Build_Access.Set_Field (Locals (1), "relations", Values (8));
               Build_Access.Set_Field (Locals (1), "stxcomment", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Result := Locals (1);
            end;
         when 594 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStatsStmt");
               Build_Access.Set_Field (Locals (1), "defnames", Values (6));
               Build_Access.Set_Field (Locals (1), "stat_types", Values (7));
               Build_Access.Set_Field (Locals (1), "exprs", Values (9));
               Build_Access.Set_Field (Locals (1), "relations", Values (11));
               Build_Access.Set_Field (Locals (1), "stxcomment", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Result := Locals (1);
            end;
         when 595 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 596 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 597 =>
               Result := Build_Access.New_Object ("StatsElem");
               Build_Access.Set_Field (Result, "name", Values (1));
               Build_Access.Set_Field (Result, "expr", Builders.No_Value);
         when 598 =>
               Result := Build_Access.New_Object ("StatsElem");
               Build_Access.Set_Field (Result, "name", Builders.No_Value);
               Build_Access.Set_Field (Result, "expr", Values (1));
         when 599 =>
               Result := Build_Access.New_Object ("StatsElem");
               Build_Access.Set_Field (Result, "name", Builders.No_Value);
               Build_Access.Set_Field (Result, "expr", Values (2));
         when 600 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterStatsStmt");
               Build_Access.Set_Field (Locals (1), "defnames", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "stxstattarget", Values (6));
               Result := Locals (1);
            end;
         when 601 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterStatsStmt");
               Build_Access.Set_Field (Locals (1), "defnames", Values (5));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "stxstattarget", Values (8));
               Result := Locals (1);
            end;
         when 602 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableAsStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (6));
               Build_Access.Set_Field (Locals (1), "into", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "is_select_into", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Build_Access.Set_Field (Values (4), "rel.relpersistence", Values (2));
               Build_Access.Set_Field (Values (4), "skipData", Semantics.Unary ("!", Values (7)));
               Result := Locals (1);
            end;
         when 603 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableAsStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (9));
               Build_Access.Set_Field (Locals (1), "into", Values (7));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "is_select_into", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Build_Access.Set_Field (Values (7), "rel.relpersistence", Values (2));
               Build_Access.Set_Field (Values (7), "skipData", Semantics.Unary ("!", Values (10)));
               Result := Locals (1);
            end;
         when 604 =>
               Result := Build_Access.New_Object ("IntoClause");
               Build_Access.Set_Field (Result, "rel", Values (1));
               Build_Access.Set_Field (Result, "colNames", Values (2));
               Build_Access.Set_Field (Result, "accessMethod", Values (3));
               Build_Access.Set_Field (Result, "options", Values (4));
               Build_Access.Set_Field (Result, "onCommit", Values (5));
               Build_Access.Set_Field (Result, "tableSpaceName", Values (6));
               Build_Access.Set_Field (Result, "viewQuery", Builders.No_Value);
               Build_Access.Set_Field (Result, "skipData", Builders.Number (0));
         when 605 =>
               Result := Builders.Number (1);
         when 606 =>
               Result := Builders.Number (0);
         when 607 =>
               Result := Builders.Number (1);
         when 608 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableAsStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (7));
               Build_Access.Set_Field (Locals (1), "into", Values (5));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (23));
               Build_Access.Set_Field (Locals (1), "is_select_into", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Build_Access.Set_Field (Values (5), "rel.relpersistence", Values (2));
               Build_Access.Set_Field (Values (5), "skipData", Semantics.Unary ("!", Values (8)));
               Result := Locals (1);
            end;
         when 609 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableAsStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (10));
               Build_Access.Set_Field (Locals (1), "into", Values (8));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (23));
               Build_Access.Set_Field (Locals (1), "is_select_into", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Build_Access.Set_Field (Values (8), "rel.relpersistence", Values (2));
               Build_Access.Set_Field (Values (8), "skipData", Semantics.Unary ("!", Values (11)));
               Result := Locals (1);
            end;
         when 610 =>
               Result := Build_Access.New_Object ("IntoClause");
               Build_Access.Set_Field (Result, "rel", Values (1));
               Build_Access.Set_Field (Result, "colNames", Values (2));
               Build_Access.Set_Field (Result, "accessMethod", Values (3));
               Build_Access.Set_Field (Result, "options", Values (4));
               Build_Access.Set_Field (Result, "onCommit", Builders.Number (0));
               Build_Access.Set_Field (Result, "tableSpaceName", Values (5));
               Build_Access.Set_Field (Result, "viewQuery", Builders.No_Value);
               Build_Access.Set_Field (Result, "skipData", Builders.Number (0));
         when 611 =>
               Result := Builders.Number (117);
         when 612 =>
               Result := Builders.Number (112);
         when 613 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RefreshMatViewStmt");
               Build_Access.Set_Field (Locals (1), "concurrent", Values (4));
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "skipData", Semantics.Unary ("!", Values (6)));
               Result := Locals (1);
            end;
         when 614 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateSeqStmt");
               Build_Access.Set_Field (Values (4), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "sequence", Values (4));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Build_Access.Set_Field (Locals (1), "ownerId", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Result := Locals (1);
            end;
         when 615 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateSeqStmt");
               Build_Access.Set_Field (Values (7), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "sequence", Values (7));
               Build_Access.Set_Field (Locals (1), "options", Values (8));
               Build_Access.Set_Field (Locals (1), "ownerId", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Result := Locals (1);
            end;
         when 616 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterSeqStmt");
               Build_Access.Set_Field (Locals (1), "sequence", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (4));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 617 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterSeqStmt");
               Build_Access.Set_Field (Locals (1), "sequence", Values (5));
               Build_Access.Set_Field (Locals (1), "options", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 618 =>
               Result := Values (1);
         when 619 =>
               Result := Builders.No_Value;
         when 620 =>
               Result := Values (2);
         when 621 =>
               Result := Builders.No_Value;
         when 622 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 623 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 624 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("as"), 2 => Values (2), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 625 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("cache"), 2 => Values (2), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 626 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("cycle"), 2 => Invoke
                  (Build_Access, "makeBoolean", (1 => Builders.Number (1))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 627 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("cycle"), 2 => Invoke
                  (Build_Access, "makeBoolean", (1 => Builders.Number (0))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 628 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("increment"), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 629 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("maxvalue"), 2 => Values (2), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 630 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("minvalue"), 2 => Values (2), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 631 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("maxvalue"), 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 632 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("minvalue"), 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 633 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("owned_by"), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 634 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("sequence_name"), 2 => Values (3),
                  3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 635 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("start"), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 636 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("restart"), 2 => Builders.No_Value,
                  3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 637 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("restart"), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 640 =>
               Result := Invoke (Build_Access, "makeFloat", (1 => Values (1)));
         when 641 =>
               Result := Invoke (Build_Access, "makeFloat", (1 => Values (2)));
         when 642 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Invoke (Build_Access, "makeFloat", (1 => Values (2)));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "doNegateFloat", (1 => Locals (1)));
               begin
                  null;
               end;
               Result := Locals (1);
            end;
         when 643 =>
               Result := Invoke (Build_Access, "makeInteger", (1 => Values (1)));
         when 644 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 645 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 646 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateExtensionStmt");
               Build_Access.Set_Field (Locals (1), "if_not_exists", Values (2));
               Build_Access.Set_Field (Locals (1), "extname", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Result := Locals (1);
            end;
         when 647 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreatePLangStmt");
               Build_Access.Set_Field (Locals (1), "replace", Values (2));
               Build_Access.Set_Field (Locals (1), "plname", Values (6));
               Build_Access.Set_Field (Locals (1), "plhandler", Values (8));
               Build_Access.Set_Field (Locals (1), "plinline", Values (9));
               Build_Access.Set_Field (Locals (1), "plvalidator", Values (10));
               Build_Access.Set_Field (Locals (1), "pltrusted", Values (3));
               Result := Locals (1);
            end;
         when 648 =>
               Result := Builders.Number (1);
         when 649 =>
               Result := Builders.Number (0);
         when 650 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (1)))));
         when 651 =>
               Result := Invoke (Build_Access, "lcons", (1 => Invoke (Build_Access, "makeString", (1 => Values (1))),
                  2 => Values (2)));
         when 652 =>
               Result := Values (2);
         when 653 =>
               Result := Builders.No_Value;
         when 654 =>
               Result := Values (2);
         when 655 =>
               Result := Builders.No_Value;
         when 656 =>
               Result := Values (1);
         when 657 =>
               Result := Builders.No_Value;
         when 660 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableSpaceStmt");
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (3));
               Build_Access.Set_Field (Locals (1), "owner", Values (4));
               Build_Access.Set_Field (Locals (1), "location", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Values (7));
               Result := Locals (1);
            end;
         when 661 =>
               Result := Values (2);
         when 662 =>
               Result := Builders.No_Value;
         when 663 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropTableSpaceStmt");
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 664 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropTableSpaceStmt");
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (5));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 665 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateExtensionStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Result := Locals (1);
            end;
         when 666 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateExtensionStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (6));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "options", Values (8));
               Result := Locals (1);
            end;
         when 667 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 668 =>
               Result := Builders.No_Value;
         when 669 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("schema"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (2))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 670 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("new_version"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (2))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 671 =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("CREATE EXTENSION ... FROM is no longer supported"));
         when 672 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("cascade"), 2 => Invoke
                  (Build_Access, "makeBoolean", (1 => Builders.Number (1))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 673 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Result := Locals (1);
            end;
         when 674 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 675 =>
               Result := Builders.No_Value;
         when 676 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("new_version"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (2))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 677 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Values (5));
               Build_Access.Set_Field (Locals (1), "object", Invoke (Build_Access, "makeString", (1 => Values (6))));
               Result := Locals (1);
            end;
         when 678 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Values (5));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 679 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 680 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (5));
               Build_Access.Set_Field (Locals (1), "object", Invoke (Build_Access, "list_make2_impl", (1 =>
                  Builders.Number (1), 2 => Values (7), 3 => Values (9))));
               Result := Locals (1);
            end;
         when 681 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (12));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 682 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (19));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 683 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (25));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 684 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (24));
               Build_Access.Set_Field (Locals (1), "object", Invoke (Build_Access, "lcons", (1 => Invoke
                  (Build_Access, "makeString", (1 => Values (9))), 2 => Values (7))));
               Result := Locals (1);
            end;
         when 685 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (26));
               Build_Access.Set_Field (Locals (1), "object", Invoke (Build_Access, "lcons", (1 => Invoke
                  (Build_Access, "makeString", (1 => Values (9))), 2 => Values (7))));
               Result := Locals (1);
            end;
         when 686 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (29));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 687 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (34));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 688 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (43));
               Build_Access.Set_Field (Locals (1), "object", Invoke (Build_Access, "list_make2_impl", (1 =>
                  Builders.Number (1), 2 => Values (7), 3 => Invoke (Build_Access, "makeString", (1 => Values
                  (9))))));
               Result := Locals (1);
            end;
         when 689 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (49));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 690 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateFdwStmt");
               Build_Access.Set_Field (Locals (1), "fdwname", Values (5));
               Build_Access.Set_Field (Locals (1), "func_options", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Values (7));
               Result := Locals (1);
            end;
         when 691 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("handler"), 2 => Values (2), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 692 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("handler"), 2 => Builders.No_Value,
                  3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 693 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("validator"), 2 => Values (2), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 694 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("validator"), 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 695 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 696 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 697 =>
               Result := Values (1);
         when 698 =>
               Result := Builders.No_Value;
         when 699 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterFdwStmt");
               Build_Access.Set_Field (Locals (1), "fdwname", Values (5));
               Build_Access.Set_Field (Locals (1), "func_options", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Values (7));
               Result := Locals (1);
            end;
         when 700 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterFdwStmt");
               Build_Access.Set_Field (Locals (1), "fdwname", Values (5));
               Build_Access.Set_Field (Locals (1), "func_options", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Result := Locals (1);
            end;
         when 701 =>
               Result := Values (3);
         when 702 =>
               Result := Builders.No_Value;
         when 703 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 704 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 705 =>
               Result := Values (3);
         when 706 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when others => null;
      end case;
   end Reduce;

end Flyology.Postgres.SQL.Native.Actions_V16_Chunk_04;
