--  Generated by tools/generate_native_actions.py.  Do not edit.
with Interfaces;
with Flyology.Postgres.SQL.Native.Builders;
with Flyology.Postgres.SQL.Native.Semantics;

package body Flyology.Postgres.SQL.Native.Action_Catalog_Chunk_03 is

   pragma Style_Checks (Off);
   use type Interfaces.Integer_64;

   procedure Reduce
     (Action       : Action_Catalog.Action_Id;
      Build        : aliased in out Builders.Builder;
      Values       : Builders.Semantic_Array;
      Locations    : Builders.Location_Array;
      Result       : in out Builders.Dynamic_Value;
      Location     : in out Integer;
      Error_Location : not null access Integer;
      Parse_Result : in out Builders.Dynamic_Value;
      Callback     : Action_Catalog.Invoke_Access)
   is
      Build_Access : constant not null access Builders.Builder :=
        Build'Unchecked_Access;

      function Version_Invoke
        (Build : not null access Builders.Builder; Name : String;
         Arguments : Builders.Semantic_Array) return Builders.Dynamic_Value
      is
      begin
         return Callback.all (Build, Name, Arguments, Error_Location);
      end Version_Invoke;
   begin
      case Action is
         when 16#23962A32FD306945# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (13));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Version_Invoke (Build_Access, "makeString", (1 => Values
                  (5))));
               Result := Locals (1);
            end;
         when 16#23D86BEE367E33C1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("GrantRoleStmt");
               Build_Access.Set_Field (Locals (1), "is_grant", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "granted_roles", Values (2));
               Build_Access.Set_Field (Locals (1), "grantee_roles", Values (4));
               Build_Access.Set_Field (Locals (1), "opt", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "grantor", Values (5));
               Result := Locals (1);
            end;
         when 16#23E90AEEE5EBE0DF# =>
               Result := Version_Invoke (Build_Access, "makeGroupingSet", (1 => Builders.Number (2), 2 => Values (3),
                  3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#23EEB6AC65B529F4# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CommentStmt");
               Build_Access.Set_Field (Locals (1), "objtype", Values (3));
               Build_Access.Set_Field (Locals (1), "object", Values (4));
               Build_Access.Set_Field (Locals (1), "comment", Values (6));
               Result := Locals (1);
            end;
         when 16#23EF34A9F35961F5# =>
               Result := Version_Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Version_Invoke (Build_Access,
                  "makeInteger", (1 => Semantics.Unary ("-", Builders.Number (1))))));
         when 16#243924CE01947DE5# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Values (8));
               Result := Locals (1);
            end;
         when 16#245F08FABCE7BC90# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterOwnerStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (21));
               Build_Access.Set_Field (Locals (1), "object", Version_Invoke (Build_Access, "makeString", (1 => Values
                  (4))));
               Build_Access.Set_Field (Locals (1), "newowner", Values (7));
               Result := Locals (1);
            end;
         when 16#2482B7C449797DD3# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Alias");
               Build_Access.Set_Field (Locals (1), "aliasname", Values (2));
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 => Locals (1),
                  3 => Values (4)));
            end;
         when 16#2483025F89E72D38# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("password"), 2 =>
                  Version_Invoke (Build_Access, "makeParamRef", (1 => Values (2), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (2))))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 16#24C661B3DAE2DA89# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateOpClassItem");
               Build_Access.Set_Field (Locals (1), "itemtype", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "number", Values (2));
               Build_Access.Set_Field (Locals (1), "class_args", Values (4));
               Result := Locals (1);
            end;
         when 16#24D0DBB7BCF59DAB# =>
               Result := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "SystemFuncName", (1 => Builders.Text ("pg_collation_for"))), 2 => Version_Invoke (Build_Access,
                  "list_make1_impl", (1 => Builders.Number (1), 2 => Values (4))), 3 => Builders.Number (3), 4 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#24DC078D714F3717# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("GrantRoleStmt");
               Build_Access.Set_Field (Locals (1), "is_grant", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "granted_roles", Values (2));
               Build_Access.Set_Field (Locals (1), "grantee_roles", Values (4));
               Build_Access.Set_Field (Locals (1), "opt", Values (6));
               Build_Access.Set_Field (Locals (1), "grantor", Values (7));
               Result := Locals (1);
            end;
         when 16#250F7E0B93E9C76E# =>
               Result := Builders.Number (16);
         when 16#2511F6B2CC163C7C# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "SystemFuncName", (1 => Builders.Text ("similar_to_escape"))), 2 => Version_Invoke (Build_Access,
                  "list_make1_impl", (1 => Builders.Number (231), 2 => Values (5))), 3 => Builders.Number (0), 4 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2)))));
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (9), 2 =>
                  Builders.Text ("!~"), 3 => Values (1), 4 => Locals (1), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
            end;
         when 16#255A206FEF870DB3# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ReplicaIdentityStmt");
               Build_Access.Set_Field (Locals (1), "identity_type", Builders.Number (102));
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 16#260FCD9C74658C8E# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Locals (2) := Build_Access.New_Object ("PartitionCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (64));
               Build_Access.Set_Field (Locals (2), "name", Values (3));
               Build_Access.Set_Field (Locals (2), "bound", Values (4));
               Build_Access.Set_Field (Locals (2), "concurrent", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "def", Locals (2));
               Result := Locals (1);
            end;
         when 16#261AAEC3E180B687# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#264F3472FE438FCB# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SecLabelStmt");
               Build_Access.Set_Field (Locals (1), "provider", Values (3));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (49));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Build_Access.Set_Field (Locals (1), "label", Values (8));
               Result := Locals (1);
            end;
         when 16#2678B5A4C145A99C# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "matched", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (7));
               Build_Access.Set_Field (Locals (1), "condition", Values (3));
               Result := Locals (1);
            end;
         when 16#26857ECA389428EE# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableMoveAllStmt");
               Build_Access.Set_Field (Locals (1), "orig_tablespacename", Values (6));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (39));
               Build_Access.Set_Field (Locals (1), "roles", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "new_tablespacename", Values (9));
               Build_Access.Set_Field (Locals (1), "nowait", Values (10));
               Result := Locals (1);
            end;
         when 16#26A596E4F848B5FE# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableAsStmt");
               Locals (2) := Build_Access.New_Object ("ExecuteStmt");
               Build_Access.Set_Field (Locals (2), "name", Values (7));
               Build_Access.Set_Field (Locals (2), "params", Values (8));
               Build_Access.Set_Field (Locals (1), "query", Locals (2));
               Build_Access.Set_Field (Locals (1), "into", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "is_select_into", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Build_Access.Set_Field (Build_Access.Field (Values (4), "rel"), "relpersistence", Values (2));
               Build_Access.Set_Field (Values (4), "skipData", Semantics.Unary ("!", Values (9)));
               Result := Locals (1);
            end;
         when 16#26C365451D1A9793# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateSchemaStmt");
               Build_Access.Set_Field (Locals (1), "schemaname", Values (6));
               Build_Access.Set_Field (Locals (1), "authrole", Builders.No_Value);
               if Semantics.Truth (Semantics.Binary ("!=", Values (7), Builders.No_Value)) then
                  Error_Location.all := Integer (Semantics.Integer_Of (Builders.Number (Interfaces.Integer_64
                     (Locations (7)))));
                  raise Action_Catalog.Positioned_Error with Semantics.Text_Of (Builders.Text
                     ("CREATE SCHEMA IF NOT EXISTS cannot include schema elements"));
               end if;
               Build_Access.Set_Field (Locals (1), "schemaElts", Values (7));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#26DB3D02085F0FBF# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("transaction_read_only"), 2
                  => Version_Invoke (Build_Access, "makeIntConst", (1 => Builders.Number (0), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1))))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 16#2768954838703EC5# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (4));
               Build_Access.Set_Field (Locals (1), "cmds", Values (5));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (18));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#279BA9EA2F39CCE1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "cmds", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Values (6))));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#27ABB6EFCFA54438# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreatePublicationStmt");
               Build_Access.Set_Field (Locals (1), "pubname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (6));
               Build_Access.Set_Field (Locals (1), "pubobjects", Values (5));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Version_Invoke (Build_Access, "preprocess_pubobj_list", (1 => Build_Access.Field (Locals (1),
                       "pubobjects"), 2 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Locals (1);
            end;
         when 16#27BD759BB65D9259# =>
               Result := Build_Access.New_Object ("InsertStmt");
               Build_Access.Set_Field (Result, "cols", Values (2));
               Build_Access.Set_Field (Result, "selectStmt", Values (4));
         when 16#27D700C297C34463# =>
               Result := Builders.Number (1);
         when 16#27DC753083079C0A# =>
               Result := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "SystemFuncName", (1 => Builders.Text ("substring"))), 2 => Values (3), 3 => Builders.Number (3), 4
                  => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#27FCD9DF6B4C4675# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 => Values (2),
                  3 => Version_Invoke (Build_Access, "makeInteger", (1 => Semantics.Unary ("-", Builders.Number
                  (1))))));
         when 16#2841C0BAB12FB26A# =>
               Result := Version_Invoke (Build_Access, "lcons", (1 => Version_Invoke (Build_Access, "makeString", (1
                  => Values (1))), 2 => Values (3)));
         when 16#2847162BA42A8E43# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "removeType", Values (2));
               Build_Access.Set_Field (Locals (1), "objects", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "lappend", (1 => Values (5), 2 =>
                  Version_Invoke (Build_Access, "makeString", (1 => Values (3))))))));
               Build_Access.Set_Field (Locals (1), "behavior", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#284BF6503AA4E1B3# =>
               Error_Location.all := Integer (Semantics.Integer_Of (Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
               raise Action_Catalog.Positioned_Error with Semantics.Text_Of (Builders.Text
                  ("MATCH PARTIAL not yet implemented"));
               Result := Builders.Number (112);
         when 16#2862F0B0B27DA233# =>
               Result := Build_Access.New_Object ("PublicationObjSpec");
               Build_Access.Set_Field (Result, "pubobjtype", Builders.Number (3));
               if Semantics.Truth (Semantics.Binary ("||", Values (2), Values (3))) then
                  Build_Access.Set_Field (Result, "pubtable", Build_Access.New_Object ("PublicationTable"));
                  Build_Access.Set_Field (Build_Access.Field (Result, "pubtable"), "relation", Version_Invoke
                     (Build_Access, "makeRangeVar", (1 => Builders.No_Value, 2 => Values (1), 3 => Builders.Number
                     (Interfaces.Integer_64 (Locations (1))))));
                  Build_Access.Set_Field (Build_Access.Field (Result, "pubtable"), "columns", Values (2));
                  Build_Access.Set_Field (Build_Access.Field (Result, "pubtable"), "whereClause", Values (3));
               else
                  Build_Access.Set_Field (Result, "name", Values (1));
               end if;
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 16#28779CB58D18D08F# =>
               Result := Semantics.Binary ("|", Values (1), Builders.Number (2));
         when 16#2889B5ABE2D769EB# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 => Values (1),
                  3 => Values (4)));
         when 16#2896FEA67A7754CD# =>
               Result := Values (2);
               Build_Access.Set_Field (Result, "inh", Builders.Number (0));
               Build_Access.Set_Field (Result, "alias", Builders.No_Value);
         when 16#28AE90FA541779EE# =>
               Result := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "SystemFuncName", (1 => Builders.Text ("normalize"))), 2 => Version_Invoke (Build_Access,
                  "list_make2_impl", (1 => Builders.Number (231), 2 => Values (3), 3 => Version_Invoke (Build_Access,
                  "makeStringConst", (1 => Values (5), 2 => Builders.Number (Interfaces.Integer_64 (Locations
                  (5))))))), 3 => Builders.Number (3), 4 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#28C48041FFF4463A# =>
               Result := Version_Invoke (Build_Access, "makeTypeCast", (1 => Values (1), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2)))));
         when 16#28C5C46609CFD3D8# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("BooleanTest");
               Build_Access.Set_Field (Locals (1), "arg", Values (1));
               Build_Access.Set_Field (Locals (1), "booltesttype", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (2))));
               Result := Locals (1);
            end;
         when 16#28DE051B367AC66A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDatabaseRefreshCollStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Result := Locals (1);
            end;
         when 16#29194FCFC68FC509# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 16#294D64D0692CE53E# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("FetchStmt");
               Build_Access.Set_Field (Locals (1), "portalname", Values (3));
               Build_Access.Set_Field (Locals (1), "direction", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "howMany", Semantics.Unary ("-", Builders.Number (1)));
               Result := Locals (1);
            end;
         when 16#2954807C70BE5EE2# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DiscardStmt");
               Build_Access.Set_Field (Locals (1), "target", Builders.Number (3));
               Result := Locals (1);
            end;
         when 16#295A97BB9333F262# =>
               Result := Builders.Number (36);
         when 16#297833419FEBBD1A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ViewStmt");
               Build_Access.Set_Field (Locals (1), "view", Values (5));
               Build_Access.Set_Field (Build_Access.Field (Locals (1), "view"), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "aliases", Values (7));
               Build_Access.Set_Field (Locals (1), "query", Version_Invoke (Build_Access, "makeRecursiveViewSelect",
                  (1 => Build_Access.Field (Build_Access.Field (Locals (1), "view"), "relname"), 2 =>
                  Build_Access.Field (Locals (1), "aliases"), 3 => Values (11))));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Values (9));
               Build_Access.Set_Field (Locals (1), "withCheckOption", Values (12));
               if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (1), "withCheckOption"),
                  Builders.Number (0))) then
                  Error_Location.all := Integer (Semantics.Integer_Of (Builders.Number (Interfaces.Integer_64
                     (Locations (12)))));
                  raise Action_Catalog.Positioned_Error with Semantics.Text_Of (Builders.Text
                     ("WITH CHECK OPTION not supported on recursive views"));
               end if;
               Result := Locals (1);
            end;
         when 16#297A32A2B51DBA21# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (0), 2 =>
                  Builders.Text ("="), 3 => Values (1), 4 => Values (3), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
         when 16#29995FDC5486C53E# =>
               Result := Builders.Number (98);
         when 16#29E6AD0118D8E0F3# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Locals (2) := Build_Access.New_Object ("PartitionCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (65));
               Build_Access.Set_Field (Locals (2), "name", Values (3));
               Build_Access.Set_Field (Locals (2), "bound", Builders.No_Value);
               Build_Access.Set_Field (Locals (2), "concurrent", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "def", Locals (2));
               Result := Locals (1);
            end;
         when 16#2A12F6FE7CD5E0DB# =>
               Result := Build_Access.New_Object ("Alias");
               Build_Access.Set_Field (Result, "aliasname", Values (1));
         when 16#2A39D1DCDEB80313# =>
               Result := Builders.Number (99);
         when 16#2A43C39B8647EEE3# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (9));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "pktable", Values (8));
               Build_Access.Set_Field (Locals (1), "fk_attrs", Values (4));
               if Semantics.Truth (Values (5)) then
                  Build_Access.Set_Field (Locals (1), "fk_attrs", Version_Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "fk_attrs"), 2 => Values (5))));
                  Build_Access.Set_Field (Locals (1), "fk_with_period", Builders.Number (1));
               end if;
               Build_Access.Set_Field (Locals (1), "pk_attrs", Build_Access.Cell_Element (Version_Invoke
                  (Build_Access, "list_nth_cell", (1 => Values (9), 2 => Builders.Number (0)))));
               if Semantics.Truth (Build_Access.Cell_Element (Version_Invoke (Build_Access, "list_nth_cell", (1 =>
                  Values (9), 2 => Builders.Number (1))))) then
                  Build_Access.Set_Field (Locals (1), "pk_attrs", Version_Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "pk_attrs"), 2 => Build_Access.Cell_Element (Version_Invoke
                     (Build_Access, "list_nth_cell", (1 => Values (9), 2 => Builders.Number (1)))))));
                  Build_Access.Set_Field (Locals (1), "pk_with_period", Builders.Number (1));
               end if;
               Build_Access.Set_Field (Locals (1), "fk_matchtype", Values (10));
               Build_Access.Set_Field (Locals (1), "fk_upd_action", Build_Access.Field (Build_Access.Field (Values
                  (11), "updateAction"), "action"));
               Build_Access.Set_Field (Locals (1), "fk_del_action", Build_Access.Field (Build_Access.Field (Values
                  (11), "deleteAction"), "action"));
               Build_Access.Set_Field (Locals (1), "fk_del_set_cols", Build_Access.Field (Build_Access.Field (Values
                  (11), "deleteAction"), "cols"));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Version_Invoke (Build_Access, "processCASbits", (1 => Values (12), 2 => Builders.Number
                       (Interfaces.Integer_64 (Locations (12))), 3 => Builders.Text ("FOREIGN KEY"), 4 =>
                       Builders.Field_Reference (Locals (1), "deferrable"), 5 => Builders.Field_Reference (Locals (1),
                       "initdeferred"), 6 => Builders.Field_Reference (Locals (1), "is_enforced"), 7 =>
                       Builders.Field_Reference (Locals (1), "skip_validation"), 8 => Builders.No_Value, 9 =>
                       Builders.No_Value));
               begin
                  null;
               end;
               Build_Access.Set_Field (Locals (1), "initially_valid", Semantics.Unary ("!", Build_Access.Field (Locals
                  (1), "skip_validation")));
               Result := Locals (1);
            end;
         when 16#2A6884EFBF30FF56# =>
               Result := Version_Invoke (Build_Access, "makeIntConst", (1 => Values (1), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 16#2A965EABA16D49F4# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ParamRef");
               Build_Access.Set_Field (Locals (1), "number", Values (1));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               if Semantics.Truth (Values (2)) then
                  Locals (2) := Build_Access.New_Object ("A_Indirection");
                  Build_Access.Set_Field (Locals (2), "arg", Locals (1));
                  Build_Access.Set_Field (Locals (2), "indirection", Version_Invoke (Build_Access,
                     "check_indirection", (1 => Values (2), 2 => Builders.No_Value)));
                  Result := Locals (2);
               else
                  Result := Locals (1);
               end if;
            end;
         when 16#2A98C1CA821B30E0# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__PrivTarget");
               Build_Access.Set_Field (Locals (1), "targtype", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (49));
               Build_Access.Set_Field (Locals (1), "objs", Values (2));
               Result := Locals (1);
            end;
         when 16#2ABAD5D482C655E4# =>
               if Semantics.Truth (Semantics.Binary ("<", Builders.Number (Interfaces.Integer_64 (Location)),
                  Builders.Number (0))) then
                  Location := Integer (Semantics.Integer_Of (Builders.Number (Interfaces.Integer_64 (Locations
                     (2)))));
               end if;
               Result := Version_Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 16#2AD3F7F3F8174767# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (11), 2 =>
                  Builders.Text ("NOT BETWEEN"), 3 => Values (1), 4 => Version_Invoke (Build_Access,
                  "list_make2_impl", (1 => Builders.Number (231), 2 => Values (5), 3 => Values (7))), 5 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2)))));
         when 16#2AD5258171F7CF33# =>
               Result := Version_Invoke (Build_Access, "makeXmlExpr", (1 => Builders.Number (4), 2 => Values (4), 3 =>
                  Builders.No_Value, 4 => Builders.No_Value, 5 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 16#2AE0200E69B15D0E# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterOwnerStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "object", Values (3));
               Build_Access.Set_Field (Locals (1), "newowner", Values (6));
               Result := Locals (1);
            end;
         when 16#2AF0184242240E31# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterObjectDependsStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (42));
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "object", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (231), 2 => Version_Invoke (Build_Access, "makeString", (1 => Values (3))))));
               Build_Access.Set_Field (Locals (1), "extname", Version_Invoke (Build_Access, "makeString", (1 => Values
                  (10))));
               Build_Access.Set_Field (Locals (1), "remove", Values (6));
               Result := Locals (1);
            end;
         when 16#2B183B022EFFBC06# =>
               Result := Build_Access.New_Object ("StatsElem");
               Build_Access.Set_Field (Result, "name", Builders.No_Value);
               Build_Access.Set_Field (Result, "expr", Values (1));
         when 16#2B4ED4EE170B9789# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterObjectSchemaStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (37));
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "newschema", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#2B65670C29EA52A4# =>
               if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 => Values (1), 2
                  => Builders.Text ("superuser"))), Builders.Number (0))) then
                  Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("superuser"), 2 =>
                     Version_Invoke (Build_Access, "makeInteger", (1 => Builders.Number (1))), 3 => Builders.Number
                     (Interfaces.Integer_64 (Locations (1)))));
               else
                  if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 => Values
                     (1), 2 => Builders.Text ("nosuperuser"))), Builders.Number (0))) then
                     Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("superuser"), 2 =>
                        Version_Invoke (Build_Access, "makeInteger", (1 => Builders.Number (0))), 3 => Builders.Number
                        (Interfaces.Integer_64 (Locations (1)))));
                  else
                     if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 => Values
                        (1), 2 => Builders.Text ("createrole"))), Builders.Number (0))) then
                        Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("createrole"), 2
                           => Version_Invoke (Build_Access, "makeInteger", (1 => Builders.Number (1))), 3 =>
                           Builders.Number (Interfaces.Integer_64 (Locations (1)))));
                     else
                        if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 =>
                           Values (1), 2 => Builders.Text ("nocreaterole"))), Builders.Number (0))) then
                           Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("createrole"),
                              2 => Version_Invoke (Build_Access, "makeInteger", (1 => Builders.Number (0))), 3 =>
                              Builders.Number (Interfaces.Integer_64 (Locations (1)))));
                        else
                           if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 =>
                              Values (1), 2 => Builders.Text ("replication"))), Builders.Number (0))) then
                              Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text
                                 ("isreplication"), 2 => Version_Invoke (Build_Access, "makeInteger", (1 =>
                                 Builders.Number (1))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                                 (1)))));
                           else
                              if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1
                                 => Values (1), 2 => Builders.Text ("noreplication"))), Builders.Number (0))) then
                                 Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text
                                    ("isreplication"), 2 => Version_Invoke (Build_Access, "makeInteger", (1 =>
                                    Builders.Number (0))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                                    (1)))));
                              else
                                 if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp",
                                    (1 => Values (1), 2 => Builders.Text ("createdb"))), Builders.Number (0))) then
                                    Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text
                                       ("createdb"), 2 => Version_Invoke (Build_Access, "makeInteger", (1 =>
                                       Builders.Number (1))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                                       (1)))));
                                 else
                                    if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access,
                                       "strcmp", (1 => Values (1), 2 => Builders.Text ("nocreatedb"))),
                                       Builders.Number (0))) then
                                       Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text
                                          ("createdb"), 2 => Version_Invoke (Build_Access, "makeInteger", (1 =>
                                          Builders.Number (0))), 3 => Builders.Number (Interfaces.Integer_64
                                          (Locations (1)))));
                                    else
                                       if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access,
                                          "strcmp", (1 => Values (1), 2 => Builders.Text ("login"))), Builders.Number
                                          (0))) then
                                          Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text
                                             ("canlogin"), 2 => Version_Invoke (Build_Access, "makeInteger", (1 =>
                                             Builders.Number (1))), 3 => Builders.Number (Interfaces.Integer_64
                                             (Locations (1)))));
                                       else
                                          if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access,
                                             "strcmp", (1 => Values (1), 2 => Builders.Text ("nologin"))),
                                             Builders.Number (0))) then
                                             Result := Version_Invoke (Build_Access, "makeDefElem", (1 =>
                                                Builders.Text ("canlogin"), 2 => Version_Invoke (Build_Access,
                                                "makeInteger", (1 => Builders.Number (0))), 3 => Builders.Number
                                                (Interfaces.Integer_64 (Locations (1)))));
                                          else
                                             if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access,
                                                "strcmp", (1 => Values (1), 2 => Builders.Text ("bypassrls"))),
                                                Builders.Number (0))) then
                                                Result := Version_Invoke (Build_Access, "makeDefElem", (1 =>
                                                   Builders.Text ("bypassrls"), 2 => Version_Invoke (Build_Access,
                                                   "makeInteger", (1 => Builders.Number (1))), 3 => Builders.Number
                                                   (Interfaces.Integer_64 (Locations (1)))));
                                             else
                                                if Semantics.Truth (Semantics.Binary ("==", Version_Invoke
                                                   (Build_Access, "strcmp", (1 => Values (1), 2 => Builders.Text
                                                   ("nobypassrls"))), Builders.Number (0))) then
                                                   Result := Version_Invoke (Build_Access, "makeDefElem", (1 =>
                                                      Builders.Text ("bypassrls"), 2 => Version_Invoke (Build_Access,
                                                      "makeInteger", (1 => Builders.Number (0))), 3 => Builders.Number
                                                      (Interfaces.Integer_64 (Locations (1)))));
                                                else
                                                   if Semantics.Truth (Semantics.Binary ("==", Version_Invoke
                                                      (Build_Access, "strcmp", (1 => Values (1), 2 => Builders.Text
                                                      ("noinherit"))), Builders.Number (0))) then
                                                      Result := Version_Invoke (Build_Access, "makeDefElem", (1 =>
                                                         Builders.Text ("inherit"), 2 => Version_Invoke (Build_Access,
                                                         "makeInteger", (1 => Builders.Number (0))), 3 =>
                                                         Builders.Number (Interfaces.Integer_64 (Locations (1)))));
                                                   else
                                                      Error_Location.all := Integer (Semantics.Integer_Of
                                                         (Builders.Number (Interfaces.Integer_64 (Locations (1)))));
                                                      raise Action_Catalog.Positioned_Error with Semantics.Text_Of
                                                         (Version_Invoke (Build_Access, "psprintf", (1 =>
                                                         Builders.Text ("unrecognized role option ""%s"""), 2 =>
                                                         Values (1))));
                                                   end if;
                                                end if;
                                             end if;
                                          end if;
                                       end if;
                                    end if;
                                 end if;
                              end if;
                           end if;
                        end if;
                     end if;
                  end if;
               end if;
         when 16#2B7E90B4A844DA2E# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               if Semantics.Truth (Semantics.Binary ("||", Semantics.Binary ("<=", Values (3), Builders.Number (0)),
                  Semantics.Binary (">", Values (3), Builders.Number (32767)))) then
                  Error_Location.all := Integer (Semantics.Integer_Of (Builders.Number (Interfaces.Integer_64
                     (Locations (3)))));
                  raise Action_Catalog.Positioned_Error with Semantics.Text_Of (Version_Invoke (Build_Access,
                     "psprintf", (1 => Builders.Text ("column number must be in range from 1 to %d"), 2 =>
                     Builders.Number (32767))));
               end if;
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (8));
               Build_Access.Set_Field (Locals (1), "num", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Version_Invoke (Build_Access, "makeInteger", (1 => Values
                  (6))));
               Result := Locals (1);
            end;
         when 16#2B94BA1E6A4B2E3E# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (231), 2 =>
                  Version_Invoke (Build_Access, "makeInteger", (1 => Semantics.Binary ("<<", Builders.Number (1),
                  Builders.Number (3)))), 3 => Builders.No_Value));
         when 16#2BA0DAEB9F174655# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("null"), 2 =>
                  Version_Invoke (Build_Access, "makeString", (1 => Values (3))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 16#2C27BAF8CAC8DAFA# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (68));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Values (4));
               Result := Locals (1);
            end;
         when 16#2C606E07C550B8AE# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("FetchStmt");
               Build_Access.Set_Field (Locals (1), "portalname", Values (4));
               Build_Access.Set_Field (Locals (1), "direction", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "howMany", Values (2));
               Result := Locals (1);
            end;
         when 16#2C8A97186950495F# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (34));
               Build_Access.Set_Field (Locals (1), "subname", Values (3));
               Build_Access.Set_Field (Locals (1), "newname", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#2CA5757E822607D2# =>
               Result := Version_Invoke (Build_Access, "makeXmlExpr", (1 => Builders.Number (1), 2 => Values (4), 3 =>
                  Values (6), 4 => Builders.No_Value, 5 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#2CA90319E99B99A5# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("force_not_null"), 2 =>
                  Values (4), 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#2CB121791CC60252# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__PrivTarget");
               Build_Access.Set_Field (Locals (1), "targtype", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (34));
               Build_Access.Set_Field (Locals (1), "objs", Values (5));
               Result := Locals (1);
            end;
         when 16#2CCA8C8605ECD286# =>
               Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 =>
                  Version_Invoke (Build_Access, "makeIntConst", (1 => Semantics.Binary ("<<", Builders.Number (1),
                  Builders.Number (12)), 2 => Builders.Number (Interfaces.Integer_64 (Locations (1)))))));
         when 16#2CDA22893DF3280B# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("window"), 2 =>
                  Version_Invoke (Build_Access, "makeBoolean", (1 => Builders.Number (1))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 16#2CEF8B589DCB480A# =>
               Build_Access.Set_Field (Values (5), "relation", Values (4));
               Build_Access.Set_Field (Values (5), "onConflictClause", Values (6));
               Build_Access.Set_Field (Values (5), "returningList", Values (7));
               Build_Access.Set_Field (Values (5), "withClause", Values (1));
               Result := Values (5);
         when 16#2CF8EF7CBB2A2C96# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "relationType", Builders.Number (39));
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "subname", Values (6));
               Build_Access.Set_Field (Locals (1), "newname", Values (8));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#2CFF351FF9925410# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitCount", Values (3));
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "offsetLoc", Semantics.Unary ("-", Builders.Number (1)));
               Build_Access.Set_Field (Locals (1), "countLoc", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "optionLoc", Builders.Number (Interfaces.Integer_64 (Locations
                  (5))));
               Result := Locals (1);
            end;
         when 16#2D1BCEEA3DBA08B6# =>
               Result := Builders.Number (39);
         when 16#2D3BF857E2B4AE6D# =>
               Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 =>
                  Version_Invoke (Build_Access, "makeIntConst", (1 => Semantics.Binary ("<<", Builders.Number (1),
                  Builders.Number (3)), 2 => Builders.Number (Interfaces.Integer_64 (Locations (1)))))));
         when 16#2D4202FDF59B3B6B# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 => Values (2),
                  3 => Values (4)));
         when 16#2D610F57CDA54D00# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateFdwStmt");
               Build_Access.Set_Field (Locals (1), "fdwname", Values (5));
               Build_Access.Set_Field (Locals (1), "func_options", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Values (7));
               Result := Locals (1);
            end;
         when 16#2D83474509751DE1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (4), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (4));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (7));
               Build_Access.Set_Field (Locals (1), "inhRelations", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "partspec", Values (8));
               Build_Access.Set_Field (Locals (1), "ofTypename", Version_Invoke (Build_Access,
                  "makeTypeNameFromNameList", (1 => Values (6))));
               Build_Access.Set_Field (Build_Access.Field (Locals (1), "ofTypename"), "location", Builders.Number
                  (Interfaces.Integer_64 (Locations (6))));
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (9));
               Build_Access.Set_Field (Locals (1), "options", Values (10));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (11));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (12));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#2D9F88DD5A76840D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (32));
               Result := Locals (1);
            end;
         when 16#2DCA35A4FB31C841# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VariableSetStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "name", Builders.Text ("session_authorization"));
               Build_Access.Set_Field (Locals (1), "location", Semantics.Unary ("-", Builders.Number (1)));
               Result := Locals (1);
            end;
         when 16#2E1008570AA045BB# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "cmds", Values (6));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (49));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#2E4CA947E606A69E# =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Version_Invoke (Build_Access, "insertSelectOptions", (1 => Values (2), 2 => Values (3), 3 =>
                       Builders.No_Value, 4 => Builders.No_Value, 5 => Values (1), 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (2);
         when 16#2E7994C9E4CF08E9# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateOpClassItem");
               Build_Access.Set_Field (Locals (1), "itemtype", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "name", Values (6));
               Build_Access.Set_Field (Locals (1), "number", Values (2));
               Build_Access.Set_Field (Locals (1), "class_args", Values (4));
               Result := Locals (1);
            end;
         when 16#2E7C2E4DCBD3EEBE# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (11), 2 =>
                  Builders.Text ("NOT BETWEEN"), 3 => Values (1), 4 => Version_Invoke (Build_Access,
                  "list_make2_impl", (1 => Builders.Number (1), 2 => Values (5), 3 => Values (7))), 5 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2)))));
         when 16#2EB336864CA82F4D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (1);
               Build_Access.Set_Field (Locals (1), "typmods", Version_Invoke (Build_Access, "list_make2_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "makeIntConst", (1 => Builders.Number
                  (32767), 2 => Semantics.Unary ("-", Builders.Number (1)))), 3 => Version_Invoke (Build_Access,
                  "makeIntConst", (1 => Values (3), 2 => Builders.Number (Interfaces.Integer_64 (Locations (3))))))));
               Result := Version_Invoke (Build_Access, "makeParamRefCast", (1 => Values (5), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (5))), 3 => Locals (1)));
            end;
         when 16#2EEEE7A00874A728# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (5));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "is_no_inherit", Values (5));
               Build_Access.Set_Field (Locals (1), "raw_expr", Values (3));
               Build_Access.Set_Field (Locals (1), "cooked_expr", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "skip_validation", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "initially_valid", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#2EF0FC66913CC9A2# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (231), 2 =>
                  Builders.No_Value, 3 => Version_Invoke (Build_Access, "makeInteger", (1 => Semantics.Unary ("-",
                  Builders.Number (1))))));
         when 16#2EF294455DA6A7F1# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (0), 2 =>
                  Builders.Text ("<="), 3 => Values (1), 4 => Values (3), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
         when 16#2EFF9233E2F7C710# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ColumnDef");
               Build_Access.Set_Field (Locals (1), "colname", Values (1));
               Build_Access.Set_Field (Locals (1), "typeName", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "inhcount", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_local", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "is_not_null", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_from_type", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "storage", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "raw_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "cooked_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "collOid", Builders.Number (0));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Version_Invoke (Build_Access, "SplitColQualList", (1 => Values (2), 2 => Builders.Field_Reference
                       (Locals (1), "constraints"), 3 => Builders.Field_Reference (Locals (1), "collClause"), 4 =>
                       Builders.No_Value));
               begin
                  null;
               end;
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#2F0B5A1332089B6C# =>
               if Semantics.Truth (Semantics.Binary ("!=", Values (1), Builders.No_Value)) then
                  Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 =>
                     Version_Invoke (Build_Access, "makeRawStmt", (1 => Values (1), 2 => Builders.Number (0)))));
               else
                  Result := Builders.No_Value;
               end if;
         when 16#2F0DCEAF47B3A3E3# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DiscardStmt");
               Build_Access.Set_Field (Locals (1), "target", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#2F28B6C64F415484# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateForeignTableStmt");
               Build_Access.Set_Field (Values (7), "relpersistence", Builders.Number (112));
               Build_Access.Set_Field (Locals (1), "base.relation", Values (7));
               Build_Access.Set_Field (Locals (1), "base.inhRelations", Version_Invoke (Build_Access,
                  "list_make1_impl", (1 => Builders.Number (231), 2 => Values (10))));
               Build_Access.Set_Field (Locals (1), "base.tableElts", Values (11));
               Build_Access.Set_Field (Locals (1), "base.partbound", Values (12));
               Build_Access.Set_Field (Locals (1), "base.ofTypename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.oncommit", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "base.tablespacename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.if_not_exists", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "servername", Values (14));
               Build_Access.Set_Field (Locals (1), "options", Values (15));
               Result := Locals (1);
            end;
         when 16#2F4892BDD80EF567# =>
               Result := Builders.Number (112);
         when 16#2F4A3AA1AF35747D# =>
               Result := Builders.Text ("select");
         when 16#2F85F7362FA9882F# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterObjectSchemaStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (18));
               Build_Access.Set_Field (Locals (1), "relation", Values (6));
               Build_Access.Set_Field (Locals (1), "newschema", Values (9));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#2F9F4E8DC60807A2# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (6), 2 =>
                  Builders.Text ("<>"), 3 => Values (1), 4 => Values (5), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
               Build_Access.Set_Field (Locals (1), "rexpr_list_start", Builders.Number (Interfaces.Integer_64
                  (Locations (4))));
               Build_Access.Set_Field (Locals (1), "rexpr_list_end", Builders.Number (Interfaces.Integer_64 (Locations
                  (6))));
               Result := Locals (1);
            end;
         when 16#2FA40D79FDDDFE72# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ObjectWithArgs");
               Build_Access.Set_Field (Locals (1), "objname", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "makeString", (1 => Values (1))))));
               Build_Access.Set_Field (Locals (1), "args_unspecified", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#2FA941B3440F00F3# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SubLink");
               Build_Access.Set_Field (Locals (1), "subLinkType", Values (3));
               Build_Access.Set_Field (Locals (1), "subLinkId", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "testexpr", Values (1));
               Build_Access.Set_Field (Locals (1), "operName", Values (2));
               Build_Access.Set_Field (Locals (1), "subselect", Values (4));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (2))));
               Result := Locals (1);
            end;
         when 16#2FD15F2CB1E4DCE5# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitCount", Version_Invoke (Build_Access, "makeIntConst", (1 =>
                  Builders.Number (1), 2 => Semantics.Unary ("-", Builders.Number (1)))));
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "offsetLoc", Semantics.Unary ("-", Builders.Number (1)));
               Build_Access.Set_Field (Locals (1), "countLoc", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "optionLoc", Builders.Number (Interfaces.Integer_64 (Locations
                  (4))));
               Result := Locals (1);
            end;
         when 16#2FD17B062181FAE2# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (42));
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "subname", Values (3));
               Build_Access.Set_Field (Locals (1), "newname", Values (8));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#2FE1BAC4ED501417# =>
               Result := Version_Invoke (Build_Access, "SystemTypeName", (1 => Values (1)));
               Build_Access.Set_Field (Result, "typmods", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "makeIntConst", (1 => Values (3), 2 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (3))))))));
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 16#301C0E24A966681C# =>
               Result := Builders.Number (47);
         when 16#3032F14585A67655# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("JsonSerializeExpr");
               Build_Access.Set_Field (Locals (1), "expr", Values (3));
               Build_Access.Set_Field (Locals (1), "output", Values (4));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#30392644E51D683C# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VariableSetStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "name", Values (1));
               Build_Access.Set_Field (Locals (1), "location", Semantics.Unary ("-", Builders.Number (1)));
               Result := Locals (1);
            end;
         when 16#304586EC18A71589# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ObjectWithArgs");
               Build_Access.Set_Field (Locals (1), "objname", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (231), 2 => Version_Invoke (Build_Access, "makeString", (1 => Version_Invoke
                  (Build_Access, "pstrdup", (1 => Values (1))))))));
               Build_Access.Set_Field (Locals (1), "args_unspecified", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#3051B28B6C7C9E59# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "objects", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "lcons", (1 => Version_Invoke (Build_Access,
                  "makeString", (1 => Values (6))), 2 => Values (4))))));
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (26));
               Build_Access.Set_Field (Locals (1), "behavior", Values (7));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#3082CD3525FAD472# =>
               Result := Builders.Number (97);
         when 16#30BEDE409BC709F6# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("FunctionParameter");
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "argType", Values (1));
               Build_Access.Set_Field (Locals (1), "mode", Builders.Number (100));
               Build_Access.Set_Field (Locals (1), "defexpr", Builders.No_Value);
               Result := Locals (1);
            end;
         when 16#30C162E699220914# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterObjectSchemaStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (48));
               Build_Access.Set_Field (Locals (1), "object", Values (5));
               Build_Access.Set_Field (Locals (1), "newschema", Values (8));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#30D99718FB489E08# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (43));
               Build_Access.Set_Field (Locals (1), "name", Values (4));
               Result := Locals (1);
            end;
         when 16#30E2652D4FB4CC2A# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (0), 2 =>
                  Builders.Text ("%"), 3 => Values (1), 4 => Values (3), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
         when 16#30FE306AB8146089# =>
               if Semantics.Truth (Semantics.Binary ("==", Values (3), Builders.Number (2))) then
                  Result := Version_Invoke (Build_Access, "makeA_Expr", (1 => Builders.Number (1), 2 => Values (2), 3
                     => Values (1), 4 => Values (5), 5 => Builders.Number (Interfaces.Integer_64 (Locations (2)))));
               else
                  Result := Version_Invoke (Build_Access, "makeA_Expr", (1 => Builders.Number (2), 2 => Values (2), 3
                     => Values (1), 4 => Values (5), 5 => Builders.Number (Interfaces.Integer_64 (Locations (2)))));
               end if;
         when 16#3110BD66CCB6E3EF# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (1);
               Build_Access.Set_Field (Locals (1), "valuesLists", Version_Invoke (Build_Access, "lappend", (1 =>
                  Build_Access.Field (Locals (1), "valuesLists"), 2 => Values (4))));
               Result := Locals (1);
            end;
         when 16#31381947EC1E29E7# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (20));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "objects", Values (6));
               Build_Access.Set_Field (Locals (1), "behavior", Values (7));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#315D7FF78DD4781D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateOpClassItem");
               Build_Access.Set_Field (Locals (1), "itemtype", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "number", Values (2));
               Result := Locals (1);
            end;
         when 16#31DD9CE6185C7248# =>
               Result := Semantics.Binary ("|", Semantics.Binary ("<<", Builders.Number (97), Builders.Number (8)),
                  Semantics.Binary ("&", Builders.Number (97), Builders.Number (255)));
         when 16#31DFE97E8A280126# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "override", Values (6));
               Build_Access.Set_Field (Locals (1), "targetList", Values (3));
               Build_Access.Set_Field (Locals (1), "values", Values (8));
               Result := Locals (1);
            end;
         when 16#31F2BF799FB84DE7# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (65));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#3243FE0676713F15# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "cmds", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (39));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#324DAEF4778AA4AD# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (3), 2 =>
                  Builders.Text ("="), 3 => Values (1), 4 => Values (5), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
         when 16#32FC86A03C622B67# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTrigStmt");
               Build_Access.Set_Field (Locals (1), "replace", Values (2));
               if Semantics.Truth (Build_Access.Field (Locals (1), "replace")) then
                  Error_Location.all := Integer (Semantics.Integer_Of (Builders.Number (Interfaces.Integer_64
                     (Locations (1)))));
                  raise Action_Catalog.Positioned_Error with Semantics.Text_Of (Builders.Text
                     ("CREATE OR REPLACE CONSTRAINT TRIGGER is not supported"));
               end if;
               Build_Access.Set_Field (Locals (1), "isconstraint", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "trigname", Values (5));
               Build_Access.Set_Field (Locals (1), "relation", Values (9));
               Build_Access.Set_Field (Locals (1), "funcname", Values (18));
               Build_Access.Set_Field (Locals (1), "args", Values (20));
               Build_Access.Set_Field (Locals (1), "row", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "timing", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "events", Build_Access.Field (Build_Access.Cell_Element
                  (Version_Invoke (Build_Access, "list_nth_cell", (1 => Values (7), 2 => Builders.Number (0)))),
                  "ival"));
               Build_Access.Set_Field (Locals (1), "columns", Build_Access.Cell_Element (Version_Invoke (Build_Access,
                  "list_nth_cell", (1 => Values (7), 2 => Builders.Number (1)))));
               Build_Access.Set_Field (Locals (1), "whenClause", Values (15));
               Build_Access.Set_Field (Locals (1), "transitionRels", Builders.No_Value);
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Version_Invoke (Build_Access, "processCASbits", (1 => Values (11), 2 => Builders.Number
                       (Interfaces.Integer_64 (Locations (11))), 3 => Builders.Text ("TRIGGER"), 4 =>
                       Builders.Field_Reference (Locals (1), "deferrable"), 5 => Builders.Field_Reference (Locals (1),
                       "initdeferred"), 6 => Builders.No_Value, 7 => Builders.No_Value, 8 => Builders.No_Value, 9 =>
                       Builders.No_Value));
               begin
                  null;
               end;
               Build_Access.Set_Field (Locals (1), "constrrel", Values (10));
               Result := Locals (1);
            end;
         when 16#3303448EB66B5238# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CommentStmt");
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (19));
               Build_Access.Set_Field (Locals (1), "object", Values (4));
               Build_Access.Set_Field (Locals (1), "comment", Values (6));
               Result := Locals (1);
            end;
         when 16#3303979CB2AB18B8# =>
               Result := Version_Invoke (Build_Access, "makeSQLValueFunction", (1 => Builders.Number (14), 2 =>
                  Semantics.Unary ("-", Builders.Number (1)), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 16#332E7B4CA6C62E26# =>
               Parse_Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 =>
                  Version_Invoke (Build_Access, "makeRawStmt", (1 => Values (2), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (2)))))));
         when 16#333039459D531DB2# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "def", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#3330895D65D52862# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("cycle"), 2 =>
                  Version_Invoke (Build_Access, "makeInteger", (1 => Builders.Number (0))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when others => null;
      end case;
   end Reduce;

end Flyology.Postgres.SQL.Native.Action_Catalog_Chunk_03;
