--  Generated by tools/generate_native_actions.py.  Do not edit.
with Flyology.Postgres.SQL.Native.Builders;
with Flyology.Postgres.SQL.Native.Action_Catalog;
with Flyology.Postgres.SQL.Native.Action_Helper_Catalog;

private package Flyology.Postgres.SQL.Native.Action_Helper_Catalog_Chunk_03 is

   function Execute
     (Helper    : Action_Helper_Catalog.Helper_Id;
      Build     : not null access Builders.Builder;
      Arguments : Builders.Semantic_Array;
      Error_Location : not null access Integer;
      Callback  : Action_Catalog.Invoke_Access) return Builders.Dynamic_Value;

end Flyology.Postgres.SQL.Native.Action_Helper_Catalog_Chunk_03;
