--  Generated by tools/generate_native_actions.py.  Do not edit.
with Interfaces;
with Flyology.Postgres.SQL.Native.Builders;
with Flyology.Postgres.SQL.Native.Semantics;
with Flyology.Postgres.SQL.Native.Actions_V16_Support;

package body Flyology.Postgres.SQL.Native.Actions_V16_Chunk_10 is

   pragma Style_Checks (Off);
   use type Interfaces.Integer_64;

   function Invoke
     (Build : not null access Builders.Builder; Name : String;
      Arguments : Builders.Semantic_Array) return Builders.Dynamic_Value
      renames Actions_V16_Support.Invoke;

   procedure Reduce
     (Build        : aliased in out Builders.Builder;
      Rule         : Positive;
      Values       : Builders.Semantic_Array;
      Locations    : Builders.Location_Array;
      Result       : in out Builders.Dynamic_Value;
      Location     : in out Integer;
      Parse_Result : in out Builders.Dynamic_Value)
   is
      Build_Access : constant not null access Builders.Builder :=
        Build'Unchecked_Access;
   begin
      case Rule is
         when 1405 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterSubscriptionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "subname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("enabled"), 2 =>
                  Invoke (Build_Access, "makeBoolean", (1 => Builders.Number (0))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1))))))));
               Result := Locals (1);
            end;
         when 1406 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterSubscriptionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (7));
               Build_Access.Set_Field (Locals (1), "subname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Result := Locals (1);
            end;
         when 1407 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropSubscriptionStmt");
               Build_Access.Set_Field (Locals (1), "subname", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "behavior", Values (4));
               Result := Locals (1);
            end;
         when 1408 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropSubscriptionStmt");
               Build_Access.Set_Field (Locals (1), "subname", Values (5));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "behavior", Values (6));
               Result := Locals (1);
            end;
         when 1409 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RuleStmt");
               Build_Access.Set_Field (Locals (1), "replace", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (9));
               Build_Access.Set_Field (Locals (1), "rulename", Values (4));
               Build_Access.Set_Field (Locals (1), "whereClause", Values (10));
               Build_Access.Set_Field (Locals (1), "event", Values (7));
               Build_Access.Set_Field (Locals (1), "instead", Values (12));
               Build_Access.Set_Field (Locals (1), "actions", Values (13));
               Result := Locals (1);
            end;
         when 1410 =>
               Result := Builders.No_Value;
         when 1411 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1412 =>
               Result := Values (2);
         when 1413 =>
               if Semantics.Truth (Semantics.Binary ("!=", Values (3), Builders.No_Value)) then
                  Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
               else
                  Result := Values (1);
               end if;
         when 1414 =>
               if Semantics.Truth (Semantics.Binary ("!=", Values (1), Builders.No_Value)) then
                  Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
               else
                  Result := Builders.No_Value;
               end if;
         when 1420 =>
               Result := Values (1);
         when 1421 =>
               Result := Builders.No_Value;
         when 1422 =>
               Result := Builders.Number (1);
         when 1423 =>
               Result := Builders.Number (2);
         when 1424 =>
               Result := Builders.Number (4);
         when 1425 =>
               Result := Builders.Number (3);
         when 1426 =>
               Result := Builders.Number (1);
         when 1427 =>
               Result := Builders.Number (0);
         when 1428 =>
               Result := Builders.Number (0);
         when 1429 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("NotifyStmt");
               Build_Access.Set_Field (Locals (1), "conditionname", Values (2));
               Build_Access.Set_Field (Locals (1), "payload", Values (3));
               Result := Locals (1);
            end;
         when 1430 =>
               Result := Values (2);
         when 1431 =>
               Result := Builders.No_Value;
         when 1432 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ListenStmt");
               Build_Access.Set_Field (Locals (1), "conditionname", Values (2));
               Result := Locals (1);
            end;
         when 1433 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("UnlistenStmt");
               Build_Access.Set_Field (Locals (1), "conditionname", Values (2));
               Result := Locals (1);
            end;
         when 1434 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("UnlistenStmt");
               Build_Access.Set_Field (Locals (1), "conditionname", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1435 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "chain", Values (3));
               Result := Locals (1);
            end;
         when 1436 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "options", Values (3));
               Result := Locals (1);
            end;
         when 1437 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "chain", Values (3));
               Result := Locals (1);
            end;
         when 1438 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "chain", Values (3));
               Result := Locals (1);
            end;
         when 1439 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "savepoint_name", Values (2));
               Result := Locals (1);
            end;
         when 1440 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (5));
               Build_Access.Set_Field (Locals (1), "savepoint_name", Values (3));
               Result := Locals (1);
            end;
         when 1441 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (5));
               Build_Access.Set_Field (Locals (1), "savepoint_name", Values (2));
               Result := Locals (1);
            end;
         when 1442 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "savepoint_name", Values (5));
               Result := Locals (1);
            end;
         when 1443 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "savepoint_name", Values (4));
               Result := Locals (1);
            end;
         when 1444 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (7));
               Build_Access.Set_Field (Locals (1), "gid", Values (3));
               Result := Locals (1);
            end;
         when 1445 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (8));
               Build_Access.Set_Field (Locals (1), "gid", Values (3));
               Result := Locals (1);
            end;
         when 1446 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (9));
               Build_Access.Set_Field (Locals (1), "gid", Values (3));
               Result := Locals (1);
            end;
         when 1447 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Values (3));
               Result := Locals (1);
            end;
         when 1448 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "chain", Values (3));
               Result := Locals (1);
            end;
         when 1452 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("transaction_isolation"), 2 =>
                  Invoke (Build_Access, "makeStringConst", (1 => Values (3), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (3))))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 1453 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("transaction_read_only"), 2 =>
                  Invoke (Build_Access, "makeIntConst", (1 => Builders.Number (1), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1))))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 1454 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("transaction_read_only"), 2 =>
                  Invoke (Build_Access, "makeIntConst", (1 => Builders.Number (0), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1))))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 1455 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("transaction_deferrable"), 2 =>
                  Invoke (Build_Access, "makeIntConst", (1 => Builders.Number (1), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1))))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 1456 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("transaction_deferrable"), 2 =>
                  Invoke (Build_Access, "makeIntConst", (1 => Builders.Number (0), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1))))), 3 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 1457 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1458 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1459 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 1461 =>
               Result := Builders.No_Value;
         when 1462 =>
               Result := Builders.Number (1);
         when 1463 =>
               Result := Builders.Number (0);
         when 1464 =>
               Result := Builders.Number (0);
         when 1465 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ViewStmt");
               Build_Access.Set_Field (Locals (1), "view", Values (4));
               Build_Access.Set_Field (Locals (1), "view.relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "aliases", Values (5));
               Build_Access.Set_Field (Locals (1), "query", Values (8));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Values (6));
               Build_Access.Set_Field (Locals (1), "withCheckOption", Values (9));
               Result := Locals (1);
            end;
         when 1466 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ViewStmt");
               Build_Access.Set_Field (Locals (1), "view", Values (6));
               Build_Access.Set_Field (Locals (1), "view.relpersistence", Values (4));
               Build_Access.Set_Field (Locals (1), "aliases", Values (7));
               Build_Access.Set_Field (Locals (1), "query", Values (10));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "options", Values (8));
               Build_Access.Set_Field (Locals (1), "withCheckOption", Values (11));
               Result := Locals (1);
            end;
         when 1467 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ViewStmt");
               Build_Access.Set_Field (Locals (1), "view", Values (5));
               Build_Access.Set_Field (Locals (1), "view.relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "aliases", Values (7));
               Build_Access.Set_Field (Locals (1), "query", Invoke (Build_Access, "makeRecursiveViewSelect", (1 =>
                  Build_Access.Field (Locals (1), "view.relname"), 2 => Build_Access.Field (Locals (1), "aliases"), 3
                  => Values (11))));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Values (9));
               Build_Access.Set_Field (Locals (1), "withCheckOption", Values (12));
               if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (1), "withCheckOption"),
                  Builders.Number (0))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("WITH CHECK OPTION not supported on recursive views"));
               end if;
               Result := Locals (1);
            end;
         when 1468 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ViewStmt");
               Build_Access.Set_Field (Locals (1), "view", Values (7));
               Build_Access.Set_Field (Locals (1), "view.relpersistence", Values (4));
               Build_Access.Set_Field (Locals (1), "aliases", Values (9));
               Build_Access.Set_Field (Locals (1), "query", Invoke (Build_Access, "makeRecursiveViewSelect", (1 =>
                  Build_Access.Field (Locals (1), "view.relname"), 2 => Build_Access.Field (Locals (1), "aliases"), 3
                  => Values (13))));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "options", Values (11));
               Build_Access.Set_Field (Locals (1), "withCheckOption", Values (14));
               if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (1), "withCheckOption"),
                  Builders.Number (0))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("WITH CHECK OPTION not supported on recursive views"));
               end if;
               Result := Locals (1);
            end;
         when 1469 =>
               Result := Builders.Number (2);
         when 1470 =>
               Result := Builders.Number (2);
         when 1471 =>
               Result := Builders.Number (1);
         when 1472 =>
               Result := Builders.Number (0);
         when 1473 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("LoadStmt");
               Build_Access.Set_Field (Locals (1), "filename", Values (2));
               Result := Locals (1);
            end;
         when 1474 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreatedbStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Result := Locals (1);
            end;
         when 1475 =>
               Result := Values (1);
         when 1476 =>
               Result := Builders.No_Value;
         when 1477 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1478 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 1479 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Values (3), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 1480 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Invoke (Build_Access,
                  "makeString", (1 => Values (3))), 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 1481 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Builders.No_Value, 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 1482 =>
               Result := Values (1);
         when 1483 =>
               Result := Invoke (Build_Access, "pstrdup", (1 => Builders.Text ("connection_limit")));
         when 1484 =>
               Result := Invoke (Build_Access, "pstrdup", (1 => Values (1)));
         when 1485 =>
               Result := Invoke (Build_Access, "pstrdup", (1 => Values (1)));
         when 1486 =>
               Result := Invoke (Build_Access, "pstrdup", (1 => Values (1)));
         when 1487 =>
               Result := Invoke (Build_Access, "pstrdup", (1 => Values (1)));
         when 1488 =>
               Result := Invoke (Build_Access, "pstrdup", (1 => Values (1)));
         when 1491 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDatabaseStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Result := Locals (1);
            end;
         when 1492 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDatabaseStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (4));
               Result := Locals (1);
            end;
         when 1493 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDatabaseStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("tablespace"), 2
                  => Invoke (Build_Access, "makeString", (1 => Values (6))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (6))))))));
               Result := Locals (1);
            end;
         when 1494 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDatabaseRefreshCollStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Result := Locals (1);
            end;
         when 1495 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDatabaseSetStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Build_Access.Set_Field (Locals (1), "setstmt", Values (4));
               Result := Locals (1);
            end;
         when 1496 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropdbStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1497 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropdbStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (5));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1498 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropdbStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Values (6));
               Result := Locals (1);
            end;
         when 1499 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropdbStmt");
               Build_Access.Set_Field (Locals (1), "dbname", Values (5));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "options", Values (8));
               Result := Locals (1);
            end;
         when 1500 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1501 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1502 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("force"), 2 => Builders.No_Value, 3
                  => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 1503 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterCollationStmt");
               Build_Access.Set_Field (Locals (1), "collname", Values (3));
               Result := Locals (1);
            end;
         when 1504 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterSystemStmt");
               Build_Access.Set_Field (Locals (1), "setstmt", Values (4));
               Result := Locals (1);
            end;
         when 1505 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterSystemStmt");
               Build_Access.Set_Field (Locals (1), "setstmt", Values (4));
               Result := Locals (1);
            end;
         when 1506 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateDomainStmt");
               Build_Access.Set_Field (Locals (1), "domainname", Values (3));
               Build_Access.Set_Field (Locals (1), "typeName", Values (5));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "SplitColQualList", (1 => Values (6), 2 => Builders.Field_Reference (Locals
                       (1), "constraints"), 3 => Builders.Field_Reference (Locals (1), "collClause"), 4 =>
                       Builders.No_Value));
               begin
                  null;
               end;
               Result := Locals (1);
            end;
         when 1507 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDomainStmt");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (84));
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Values (4));
               Result := Locals (1);
            end;
         when 1508 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDomainStmt");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (78));
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Result := Locals (1);
            end;
         when 1509 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDomainStmt");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (79));
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Result := Locals (1);
            end;
         when 1510 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDomainStmt");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (67));
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Values (5));
               Result := Locals (1);
            end;
         when 1511 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDomainStmt");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (88));
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Build_Access.Set_Field (Locals (1), "name", Values (6));
               Build_Access.Set_Field (Locals (1), "behavior", Values (7));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 1512 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDomainStmt");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (88));
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Build_Access.Set_Field (Locals (1), "name", Values (8));
               Build_Access.Set_Field (Locals (1), "behavior", Values (9));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1513 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterDomainStmt");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (86));
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Build_Access.Set_Field (Locals (1), "name", Values (6));
               Result := Locals (1);
            end;
         when 1516 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTSDictionaryStmt");
               Build_Access.Set_Field (Locals (1), "dictname", Values (5));
               Build_Access.Set_Field (Locals (1), "options", Values (6));
               Result := Locals (1);
            end;
         when 1517 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTSConfigurationStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "cfgname", Values (5));
               Build_Access.Set_Field (Locals (1), "tokentype", Values (9));
               Build_Access.Set_Field (Locals (1), "dicts", Values (11));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (0));
               Result := Locals (1);
            end;
         when 1518 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTSConfigurationStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "cfgname", Values (5));
               Build_Access.Set_Field (Locals (1), "tokentype", Values (9));
               Build_Access.Set_Field (Locals (1), "dicts", Values (11));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (0));
               Result := Locals (1);
            end;
         when 1519 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTSConfigurationStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "cfgname", Values (5));
               Build_Access.Set_Field (Locals (1), "tokentype", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "dicts", Invoke (Build_Access, "list_make2_impl", (1 =>
                  Builders.Number (1), 2 => Values (9), 3 => Values (11))));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1520 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTSConfigurationStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "cfgname", Values (5));
               Build_Access.Set_Field (Locals (1), "tokentype", Values (9));
               Build_Access.Set_Field (Locals (1), "dicts", Invoke (Build_Access, "list_make2_impl", (1 =>
                  Builders.Number (1), 2 => Values (11), 3 => Values (13))));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1521 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTSConfigurationStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "cfgname", Values (5));
               Build_Access.Set_Field (Locals (1), "tokentype", Values (9));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 1522 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTSConfigurationStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "cfgname", Values (5));
               Build_Access.Set_Field (Locals (1), "tokentype", Values (11));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1525 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateConversionStmt");
               Build_Access.Set_Field (Locals (1), "conversion_name", Values (4));
               Build_Access.Set_Field (Locals (1), "for_encoding_name", Values (6));
               Build_Access.Set_Field (Locals (1), "to_encoding_name", Values (8));
               Build_Access.Set_Field (Locals (1), "func_name", Values (10));
               Build_Access.Set_Field (Locals (1), "def", Values (2));
               Result := Locals (1);
            end;
         when 1526 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ClusterStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "indexname", Values (4));
               Build_Access.Set_Field (Locals (1), "params", Builders.No_Value);
               if Semantics.Truth (Values (2)) then
                  Build_Access.Set_Field (Locals (1), "params", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "params"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("verbose"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (2))))))));
               end if;
               Result := Locals (1);
            end;
         when 1527 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ClusterStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "indexname", Values (6));
               Build_Access.Set_Field (Locals (1), "params", Values (3));
               Result := Locals (1);
            end;
         when 1528 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ClusterStmt");
               Build_Access.Set_Field (Locals (1), "relation", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexname", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "params", Builders.No_Value);
               if Semantics.Truth (Values (2)) then
                  Build_Access.Set_Field (Locals (1), "params", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "params"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("verbose"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (2))))))));
               end if;
               Result := Locals (1);
            end;
         when 1529 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ClusterStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "indexname", Values (3));
               Build_Access.Set_Field (Locals (1), "params", Builders.No_Value);
               if Semantics.Truth (Values (2)) then
                  Build_Access.Set_Field (Locals (1), "params", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "params"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("verbose"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (2))))))));
               end if;
               Result := Locals (1);
            end;
         when 1530 =>
               Result := Values (2);
         when 1531 =>
               Result := Builders.No_Value;
         when 1532 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VacuumStmt");
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               if Semantics.Truth (Values (2)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("full"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (2))))))));
               end if;
               if Semantics.Truth (Values (3)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("freeze"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (3))))))));
               end if;
               if Semantics.Truth (Values (4)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("verbose"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (4))))))));
               end if;
               if Semantics.Truth (Values (5)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("analyze"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (5))))))));
               end if;
               Build_Access.Set_Field (Locals (1), "rels", Values (6));
               Build_Access.Set_Field (Locals (1), "is_vacuumcmd", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1533 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VacuumStmt");
               Build_Access.Set_Field (Locals (1), "options", Values (3));
               Build_Access.Set_Field (Locals (1), "rels", Values (5));
               Build_Access.Set_Field (Locals (1), "is_vacuumcmd", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1534 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VacuumStmt");
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               if Semantics.Truth (Values (2)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("verbose"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (2))))))));
               end if;
               Build_Access.Set_Field (Locals (1), "rels", Values (3));
               Build_Access.Set_Field (Locals (1), "is_vacuumcmd", Builders.Number (0));
               Result := Locals (1);
            end;
         when 1535 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VacuumStmt");
               Build_Access.Set_Field (Locals (1), "options", Values (3));
               Build_Access.Set_Field (Locals (1), "rels", Values (5));
               Build_Access.Set_Field (Locals (1), "is_vacuumcmd", Builders.Number (0));
               Result := Locals (1);
            end;
         when 1536 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1537 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1540 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Values (2), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 1541 =>
               Result := Values (1);
         when 1542 =>
               Result := Builders.Text ("analyze");
         when 1543 =>
               Result := Builders.Text ("format");
         when 1544 =>
               Result := Invoke (Build_Access, "makeString", (1 => Values (1)));
         when 1545 =>
               Result := Values (1);
         when 1546 =>
               Result := Builders.No_Value;
         when 1547 =>
               Result := Builders.Number (1);
         when 1548 =>
               Result := Builders.Number (0);
         when 1549 =>
               Result := Builders.Number (1);
         when 1550 =>
               Result := Builders.Number (0);
         when 1551 =>
               Result := Builders.Number (1);
         when 1552 =>
               Result := Builders.Number (0);
         when 1553 =>
               Result := Builders.Number (1);
         when 1554 =>
               Result := Builders.Number (0);
         when 1555 =>
               Result := Values (2);
         when 1556 =>
               Result := Builders.No_Value;
         when 1557 =>
               Result := Invoke (Build_Access, "makeVacuumRelation", (1 => Values (1), 2 => Builders.Number (0), 3 =>
                  Values (2)));
         when 1558 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1559 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1560 =>
               Result := Values (1);
         when 1561 =>
               Result := Builders.No_Value;
         when 1562 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ExplainStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (2));
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1563 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ExplainStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (4));
               Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("analyze"), 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (2))))))));
               if Semantics.Truth (Values (3)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Invoke (Build_Access, "makeDefElem", (1 =>
                     Builders.Text ("verbose"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (3))))))));
               end if;
               Result := Locals (1);
            end;
         when 1564 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ExplainStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("verbose"), 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (2))))))));
               Result := Locals (1);
            end;
         when 1565 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ExplainStmt");
               Build_Access.Set_Field (Locals (1), "query", Values (5));
               Build_Access.Set_Field (Locals (1), "options", Values (3));
               Result := Locals (1);
            end;
         when others => null;
      end case;
   end Reduce;

end Flyology.Postgres.SQL.Native.Actions_V16_Chunk_10;
