--  Generated by tools/generate_owned_ast.py.  Do not edit.
with Flyology.Postgres.SQL.AST.V14;

private package Flyology.Postgres.SQL.AST_Materialization_V14 is

   procedure Materialize
     (Arena : Syntax_Tree; Result : in out Flyology.Postgres.SQL.AST.V14.Owned_Syntax_Tree);

end Flyology.Postgres.SQL.AST_Materialization_V14;
