--  Generated by tools/generate_native_actions.py.  Do not edit.
with Interfaces;
with Flyology.Postgres.SQL.Native.Builders;
with Flyology.Postgres.SQL.Native.Semantics;

package body Flyology.Postgres.SQL.Native.Action_Catalog_Chunk_07 is

   pragma Style_Checks (Off);
   use type Interfaces.Integer_64;

   procedure Reduce
     (Action       : Action_Catalog.Action_Id;
      Build        : aliased in out Builders.Builder;
      Values       : Builders.Semantic_Array;
      Locations    : Builders.Location_Array;
      Result       : in out Builders.Dynamic_Value;
      Location     : in out Integer;
      Parse_Result : in out Builders.Dynamic_Value;
      Callback     : Action_Catalog.Invoke_Access)
   is
      Build_Access : constant not null access Builders.Builder :=
        Build'Unchecked_Access;

      function Version_Invoke
        (Build : not null access Builders.Builder; Name : String;
         Arguments : Builders.Semantic_Array) return Builders.Dynamic_Value
      is
      begin
         return Callback.all (Build, Name, Arguments);
      end Version_Invoke;
   begin
      case Action is
         when 16#6F7E1540AD411668# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SubLink");
               Build_Access.Set_Field (Locals (1), "subselect", Values (3));
               Build_Access.Set_Field (Locals (1), "subLinkType", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "subLinkId", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "testexpr", Values (1));
               Build_Access.Set_Field (Locals (1), "operName", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (2))));
               Result := Locals (1);
            end;
         when 16#6F9BFCA95EF41D37# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (16));
               Build_Access.Set_Field (Locals (1), "def", Values (2));
               Result := Locals (1);
            end;
         when 16#706384B67DF88B8D# =>
               if Semantics.Truth (Semantics.Binary ("!=", Values (3), Builders.No_Value)) then
                  Result := Version_Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
               else
                  Result := Values (1);
               end if;
         when 16#7080138CEE5AC9A2# =>
               Result := Builders.Text ("NFKC");
         when 16#7083C9481364566E# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SecLabelStmt");
               Build_Access.Set_Field (Locals (1), "provider", Values (3));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Build_Access.Set_Field (Locals (1), "label", Values (8));
               Result := Locals (1);
            end;
         when 16#7086AAEF38024BC1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("FetchStmt");
               Build_Access.Set_Field (Locals (1), "portalname", Values (3));
               Build_Access.Set_Field (Locals (1), "direction", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "howMany", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#70A0663413AF2D8C# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("format"), 2 =>
                  Version_Invoke (Build_Access, "makeString", (1 => Builders.Text ("csv"))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 16#70A683D9BE8E38B4# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "SystemFuncName", (1 => Builders.Text ("like_escape"))), 2 => Version_Invoke (Build_Access,
                  "list_make2_impl", (1 => Builders.Number (231), 2 => Values (3), 3 => Values (5))), 3 =>
                  Builders.Number (0), 4 => Builders.Number (Interfaces.Integer_64 (Locations (2)))));
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (8), 2 =>
                  Builders.Text ("~~*"), 3 => Values (1), 4 => Locals (1), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
            end;
         when 16#70ACC97B82F170C4# =>
               Result := Build_Access.New_Object ("IndexElem");
               Build_Access.Set_Field (Result, "name", Builders.No_Value);
               Build_Access.Set_Field (Result, "expr", Builders.No_Value);
               Build_Access.Set_Field (Result, "indexcolname", Builders.No_Value);
               Build_Access.Set_Field (Result, "collation", Values (1));
               Build_Access.Set_Field (Result, "opclass", Values (2));
               Build_Access.Set_Field (Result, "opclassopts", Values (3));
               Build_Access.Set_Field (Result, "ordering", Values (4));
               Build_Access.Set_Field (Result, "nulls_ordering", Values (5));
         when 16#70D76C60E4F0E691# =>
               Result := Values (1);
               Build_Access.Set_Field (Result, "inh", Builders.Number (1));
               Build_Access.Set_Field (Result, "alias", Builders.No_Value);
         when 16#710CA599DCA75ADC# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("maxvalue"), 2 => Values
                  (2), 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#714CFD57C0946D0A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Locals (2) := Build_Access.New_Object ("PartitionCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (59));
               Build_Access.Set_Field (Locals (2), "name", Values (3));
               Build_Access.Set_Field (Locals (2), "bound", Builders.No_Value);
               Build_Access.Set_Field (Locals (2), "concurrent", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "def", Locals (2));
               Result := Locals (1);
            end;
         when 16#71648C42C1F888AB# =>
               Result := Values (3);
               Build_Access.Set_Field (Version_Invoke (Build_Access, "list_nth_cell", (1 => Result, 2 =>
                  Builders.Number (0))), "ptr_value", Version_Invoke (Build_Access, "makeIntConst", (1 =>
                  Semantics.Binary ("|", Semantics.Binary ("|", Semantics.Binary ("|", Semantics.Binary ("<<",
                  Builders.Number (1), Builders.Number (3)), Semantics.Binary ("<<", Builders.Number (1),
                  Builders.Number (10))), Semantics.Binary ("<<", Builders.Number (1), Builders.Number (11))),
                  Semantics.Binary ("<<", Builders.Number (1), Builders.Number (12))), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1))))));
         when 16#719568B44998DE3F# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__PrivTarget");
               Build_Access.Set_Field (Locals (1), "targtype", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (32));
               Build_Access.Set_Field (Locals (1), "objs", Values (5));
               Result := Locals (1);
            end;
         when 16#71D208DF9C8C89C9# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (29));
               Build_Access.Set_Field (Locals (1), "objects", Values (5));
               Build_Access.Set_Field (Locals (1), "behavior", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#71E56C723A449C0A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("FunctionParameter");
               Build_Access.Set_Field (Locals (1), "name", Values (1));
               Build_Access.Set_Field (Locals (1), "argType", Values (2));
               Build_Access.Set_Field (Locals (1), "mode", Builders.Number (5));
               Build_Access.Set_Field (Locals (1), "defexpr", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#72527C1960C77AAB# =>
               Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 =>
                  Version_Invoke (Build_Access, "makeRoleSpec", (1 => Builders.Number (4), 2 => Semantics.Unary ("-",
                  Builders.Number (1))))));
         when 16#728107FFFBFB810D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VariableSetStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "name", Builders.Text ("role"));
               Build_Access.Set_Field (Locals (1), "args", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "makeStringConst", (1 => Values (2), 2 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2))))))));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (2))));
               Result := Locals (1);
            end;
         when 16#72986D2548FA2CC8# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TransactionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "savepoint_name", Values (2));
               Result := Locals (1);
            end;
         when 16#733B5503A9DD3E85# =>
               Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 =>
                  Version_Invoke (Build_Access, "makeIntConst", (1 => Semantics.Binary ("<<", Builders.Number (1),
                  Builders.Number (12)), 2 => Builders.Number (Interfaces.Integer_64 (Locations (1)))))));
         when 16#7345B361B2DC807B# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VariableSetStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "name", Builders.Text ("timezone"));
               if Semantics.Truth (Semantics.Binary ("!=", Values (3), Builders.No_Value)) then
                  Build_Access.Set_Field (Locals (1), "args", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                     Builders.Number (1), 2 => Values (3))));
               else
                  Build_Access.Set_Field (Locals (1), "kind", Builders.Number (1));
               end if;
               Result := Locals (1);
            end;
         when 16#73A459638C4BAF0D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateRoleStmt");
               Build_Access.Set_Field (Locals (1), "stmt_type", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "role", Values (3));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Result := Locals (1);
            end;
         when 16#73ACD063AAB5EB57# =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Version_Invoke (Build_Access, "check_qualified_name", (1 => Values (2), 2 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Version_Invoke (Build_Access, "makeRangeVar", (1 => Builders.No_Value, 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
               case Build_Access.Length (Values (2)) is
                  when 1 =>
                     Build_Access.Set_Field (Result, "catalogname", Builders.No_Value);
                     Build_Access.Set_Field (Result, "schemaname", Values (1));
                     Build_Access.Set_Field (Result, "relname",
                       Build_Access.Field (Build_Access.Element (Values (2), 1), "sval"));
                  when 2 =>
                     Build_Access.Set_Field (Result, "catalogname", Values (1));
                     Build_Access.Set_Field (Result, "schemaname",
                       Build_Access.Field (Build_Access.Element (Values (2), 1), "sval"));
                     Build_Access.Set_Field (Result, "relname",
                       Build_Access.Field (Build_Access.Element (Values (2), 2), "sval"));
                  when others =>
                     raise Semantics.Parser_Error with "improper qualified name";
               end case;
         when 16#73D47166D988D53C# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VariableSetStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "name", Builders.Text ("xmloption"));
               Build_Access.Set_Field (Locals (1), "args", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "makeStringConst", (1 => (if Semantics.Truth
                  (Semantics.Binary ("==", Values (3), Builders.Number (0))) then Builders.Text ("DOCUMENT") else
                  Builders.Text ("CONTENT")), 2 => Builders.Number (Interfaces.Integer_64 (Locations (3))))))));
               Build_Access.Set_Field (Locals (1), "jumble_args", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "location", Semantics.Unary ("-", Builders.Number (1)));
               Result := Locals (1);
            end;
         when 16#73F47BC78B091A18# =>
               Result := Build_Access.New_Object ("Alias");
               Build_Access.Set_Field (Result, "aliasname", Values (2));
               Build_Access.Set_Field (Result, "colnames", Values (4));
         when 16#73FD4E753993A541# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CommentStmt");
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (29));
               Build_Access.Set_Field (Locals (1), "object", Values (4));
               Build_Access.Set_Field (Locals (1), "comment", Values (6));
               Result := Locals (1);
            end;
         when 16#742F45012FDC5C11# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionElem");
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "expr", Values (1));
               Build_Access.Set_Field (Locals (1), "collation", Values (2));
               Build_Access.Set_Field (Locals (1), "opclass", Values (3));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#746C2B989F53E2FE# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (7), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (7));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (10));
               Build_Access.Set_Field (Locals (1), "inhRelations", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "partspec", Values (11));
               Build_Access.Set_Field (Locals (1), "ofTypename", Version_Invoke (Build_Access,
                  "makeTypeNameFromNameList", (1 => Values (9))));
               Build_Access.Set_Field (Locals (1), "ofTypename.location", Builders.Number (Interfaces.Integer_64
                  (Locations (9))));
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (12));
               Build_Access.Set_Field (Locals (1), "options", Values (13));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (14));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (15));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#746FCFDB3CD04ECA# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (33));
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 16#747F888FA897FCAA# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterExtensionContentsStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (3));
               Build_Access.Set_Field (Locals (1), "action", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (25));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Result := Locals (1);
            end;
         when 16#74993036D3DAA38A# =>
               Result := Builders.Text ("on");
         when 16#74A0E597373EEA47# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (29));
               Build_Access.Set_Field (Locals (1), "objects", Values (3));
               Build_Access.Set_Field (Locals (1), "behavior", Values (4));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#74AA5E7AF1BCB367# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 =>
                  Version_Invoke (Build_Access, "makeIntConst", (1 => Semantics.Binary ("<<", Builders.Number (1),
                  Builders.Number (12)), 2 => Builders.Number (Interfaces.Integer_64 (Locations (1))))), 3 =>
                  Version_Invoke (Build_Access, "makeIntConst", (1 => Values (3), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (3)))))));
         when 16#74BD26DBC4B2A8EC# =>
               Result := Values (2);
               Build_Access.Set_Field (Result, "limitOffset", Values (1));
         when 16#74D0888E01C903AC# =>
               Result := Values (1);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (112));
         when 16#74FA87A894E59045# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (231), 2 =>
                  Builders.No_Value, 3 => Values (5)));
         when 16#7503ADE664323E1C# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (50));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 16#751922B7ACFA6861# =>
               Result := Version_Invoke (Build_Access, "makeSetOp", (1 => Builders.Number (2), 2 => Semantics.Binary
                  ("==", Values (3), Builders.Number (1)), 3 => Values (1), 4 => Values (4)));
         when 16#751BC38D45B12FEB# =>
               Result := Version_Invoke (Build_Access, "makeGroupingSet", (1 => Builders.Number (0), 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#7525E9FD60114ECC# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (13), 2 =>
                  Builders.Text ("NOT BETWEEN SYMMETRIC"), 3 => Values (1), 4 => Version_Invoke (Build_Access,
                  "list_make2_impl", (1 => Builders.Number (231), 2 => Values (5), 3 => Values (7))), 5 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2)))));
         when 16#75406D5391CAB423# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateForeignTableStmt");
               Build_Access.Set_Field (Values (4), "relpersistence", Builders.Number (112));
               Build_Access.Set_Field (Locals (1), "base.relation", Values (4));
               Build_Access.Set_Field (Locals (1), "base.inhRelations", Version_Invoke (Build_Access,
                  "list_make1_impl", (1 => Builders.Number (231), 2 => Values (7))));
               Build_Access.Set_Field (Locals (1), "base.tableElts", Values (8));
               Build_Access.Set_Field (Locals (1), "base.partbound", Values (9));
               Build_Access.Set_Field (Locals (1), "base.ofTypename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.oncommit", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "base.tablespacename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "base.if_not_exists", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "servername", Values (11));
               Build_Access.Set_Field (Locals (1), "options", Values (12));
               Result := Locals (1);
            end;
         when 16#755EDAF11BB0D95F# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterSubscriptionStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "subname", Values (3));
               Build_Access.Set_Field (Locals (1), "publication", Values (6));
               Build_Access.Set_Field (Locals (1), "options", Values (7));
               Result := Locals (1);
            end;
         when 16#75638E4C5371F3F1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterObjectSchemaStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "newschema", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#757466A68F999364# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "cmds", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Values (4))));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (20));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#75A447819FCE5D7D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               if Semantics.Truth (Semantics.Binary ("||", Semantics.Binary ("<=", Values (3), Builders.Number (0)),
                  Semantics.Binary (">", Values (3), Builders.Number (32767)))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("column number must be in range from 1 to %d"));
               end if;
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (9));
               Build_Access.Set_Field (Locals (1), "num", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Values (6));
               Result := Locals (1);
            end;
         when 16#75C3B6D073EEDAFE# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "def", Values (3));
               Build_Access.Set_Field (Locals (1), "behavior", Values (4));
               Result := Locals (1);
            end;
         when 16#75C3BE96F9377CE1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Locals (2) := Version_Invoke (Build_Access, "makeTypeNameFromNameList", (1 => Values (2)));
               Build_Access.Set_Field (Locals (2), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (2))));
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (52));
               Build_Access.Set_Field (Locals (1), "def", Locals (2));
               Result := Locals (1);
            end;
         when 16#75CA349BD7D3BE20# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 4) :=
                 (others => Builders.No_Value);
            begin
               Locals (2) := Build_Access.New_Object ("PartitionBoundSpec");
               Build_Access.Set_Field (Locals (2), "strategy", Builders.Number (104));
               Build_Access.Set_Field (Locals (2), "modulus", Semantics.Set_Field (Build_Access, Locals (2),
                  "remainder", Semantics.Unary ("-", Builders.Number (1))));
               declare
                  Loop_List : constant Builders.Dynamic_Value := Values (5);
               begin
                  for Loop_Index in 1 .. Build_Access.Length (Loop_List) loop
                     Locals (1) := Build_Access.Cell (Loop_List, Loop_Index);
                     Locals (4) := Build_Access.Cell_Element (Locals (1));
                     if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 =>
                        Build_Access.Field (Locals (4), "defname"), 2 => Builders.Text ("modulus"))), Builders.Number
                        (0))) then
                        if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (2), "modulus"),
                           Semantics.Unary ("-", Builders.Number (1)))) then
                           raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                              ("modulus for hash partition provided more than once"));
                        end if;
                        Build_Access.Set_Field (Locals (2), "modulus", Version_Invoke (Build_Access, "defGetInt32", (1
                           => Locals (4))));
                     else
                        if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 =>
                           Build_Access.Field (Locals (4), "defname"), 2 => Builders.Text ("remainder"))),
                           Builders.Number (0))) then
                           if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (2), "remainder"),
                              Semantics.Unary ("-", Builders.Number (1)))) then
                              raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                                 ("remainder for hash partition provided more than once"));
                           end if;
                           Build_Access.Set_Field (Locals (2), "remainder", Version_Invoke (Build_Access,
                              "defGetInt32", (1 => Locals (4))));
                        else
                           raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                              ("unrecognized hash partition bound specification ""%s"""));
                        end if;
                     end if;
                     <<Continue_Loop_H75CA349BD7D3BE20_1>>
                     null;
                  end loop;
               end;
               if Semantics.Truth (Semantics.Binary ("==", Build_Access.Field (Locals (2), "modulus"), Semantics.Unary
                  ("-", Builders.Number (1)))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("modulus for hash partition must be specified"));
               end if;
               if Semantics.Truth (Semantics.Binary ("==", Build_Access.Field (Locals (2), "remainder"),
                  Semantics.Unary ("-", Builders.Number (1)))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("remainder for hash partition must be specified"));
               end if;
               Build_Access.Set_Field (Locals (2), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (3))));
               Result := Locals (2);
            end;
         when 16#761FD921A8055280# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CTESearchClause");
               Build_Access.Set_Field (Locals (1), "search_col_list", Values (5));
               Build_Access.Set_Field (Locals (1), "search_breadth_first", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "search_seq_column", Values (7));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#762B12C18230B39B# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (63));
               Build_Access.Set_Field (Locals (1), "def", Values (1));
               Result := Locals (1);
            end;
         when 16#766A2E1C88C46548# =>
               Result := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "list_make1_impl", (1 => Builders.Number (231), 2 => Version_Invoke (Build_Access, "makeString", (1
                  => Builders.Text ("overlay"))))), 2 => Values (3), 3 => Builders.Number (0), 4 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 16#768848AC3B910B14# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (53));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 16#76B4DA4ECA287D7C# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateExtensionStmt");
               Build_Access.Set_Field (Locals (1), "extname", Values (6));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "options", Values (8));
               Result := Locals (1);
            end;
         when 16#77042D9322930372# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("IndexStmt");
               Build_Access.Set_Field (Locals (1), "unique", Values (2));
               Build_Access.Set_Field (Locals (1), "concurrent", Values (4));
               Build_Access.Set_Field (Locals (1), "idxname", Values (8));
               Build_Access.Set_Field (Locals (1), "relation", Values (10));
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (11));
               Build_Access.Set_Field (Locals (1), "indexParams", Values (13));
               Build_Access.Set_Field (Locals (1), "indexIncludingParams", Values (15));
               Build_Access.Set_Field (Locals (1), "nulls_not_distinct", Semantics.Unary ("!", Values (16)));
               Build_Access.Set_Field (Locals (1), "options", Values (17));
               Build_Access.Set_Field (Locals (1), "tableSpace", Values (18));
               Build_Access.Set_Field (Locals (1), "whereClause", Values (19));
               Build_Access.Set_Field (Locals (1), "excludeOpNames", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "idxcomment", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexOid", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "oldNode", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "oldCreateSubid", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "oldFirstRelfilenodeSubid", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "primary", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "isconstraint", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "deferrable", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "initdeferred", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "transformed", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "reset_default_tblspc", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7713F5314F1EDD5B# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (47));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "objects", Values (5));
               Build_Access.Set_Field (Locals (1), "behavior", Values (6));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#777342398D7B0C8B# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ObjectWithArgs");
               Build_Access.Set_Field (Locals (1), "objname", Values (1));
               Build_Access.Set_Field (Locals (1), "objargs", Version_Invoke (Build_Access, "extractAggrArgTypes", (1
                  => Values (2))));
               Build_Access.Set_Field (Locals (1), "objfuncargs", Build_Access.Cell_Element (Version_Invoke
                  (Build_Access, "list_nth_cell", (1 => Values (2), 2 => Builders.Number (0)))));
               Result := Locals (1);
            end;
         when 16#779F90A878E0F960# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "subname", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "newname", Values (8));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#77A9EEC807340864# =>
               Build_Access.Set_Field (Values (1), "val", Values (3));
               Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values
                  (1)));
         when 16#77BA8861B642F845# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PrepareStmt");
               Build_Access.Set_Field (Locals (1), "name", Values (2));
               Build_Access.Set_Field (Locals (1), "argtypes", Values (3));
               Build_Access.Set_Field (Locals (1), "query", Values (5));
               Result := Locals (1);
            end;
         when 16#77F1AE6A762987C7# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (68));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#7806F06D495C80E0# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VariableSetStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "name", Builders.Text ("xmloption"));
               Build_Access.Set_Field (Locals (1), "args", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (231), 2 => Version_Invoke (Build_Access, "makeStringConst", (1 => (if
                  Semantics.Truth (Semantics.Binary ("==", Values (3), Builders.Number (0))) then Builders.Text
                  ("DOCUMENT") else Builders.Text ("CONTENT")), 2 => Builders.Number (Interfaces.Integer_64 (Locations
                  (3))))))));
               Result := Locals (1);
            end;
         when 16#780F4C07D6064C3D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (27));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 16#78184364C123058E# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VacuumStmt");
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               if Semantics.Truth (Values (2)) then
                  Build_Access.Set_Field (Locals (1), "options", Version_Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Version_Invoke (Build_Access, "makeDefElem", (1
                     => Builders.Text ("full"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (2))))))));
               end if;
               if Semantics.Truth (Values (3)) then
                  Build_Access.Set_Field (Locals (1), "options", Version_Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Version_Invoke (Build_Access, "makeDefElem", (1
                     => Builders.Text ("freeze"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (3))))))));
               end if;
               if Semantics.Truth (Values (4)) then
                  Build_Access.Set_Field (Locals (1), "options", Version_Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Version_Invoke (Build_Access, "makeDefElem", (1
                     => Builders.Text ("verbose"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (4))))))));
               end if;
               if Semantics.Truth (Values (5)) then
                  Build_Access.Set_Field (Locals (1), "options", Version_Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Version_Invoke (Build_Access, "makeDefElem", (1
                     => Builders.Text ("analyze"), 2 => Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64
                     (Locations (5))))))));
               end if;
               Build_Access.Set_Field (Locals (1), "rels", Values (6));
               Build_Access.Set_Field (Locals (1), "is_vacuumcmd", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#782575D6712AB990# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (34));
               Build_Access.Set_Field (Locals (1), "objects", Values (3));
               Build_Access.Set_Field (Locals (1), "behavior", Values (4));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7838E5A444626EDA# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "is_no_inherit", Values (3));
               Build_Access.Set_Field (Locals (1), "is_enforced", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "skip_validation", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "initially_valid", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#784C2C366B4B0E16# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (28));
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "subname", Values (3));
               Build_Access.Set_Field (Locals (1), "newname", Values (8));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#784C73C1EC58999A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SecLabelStmt");
               Build_Access.Set_Field (Locals (1), "provider", Values (3));
               Build_Access.Set_Field (Locals (1), "objtype", Values (5));
               Build_Access.Set_Field (Locals (1), "object", Values (6));
               Build_Access.Set_Field (Locals (1), "label", Values (8));
               Result := Locals (1);
            end;
         when 16#7886A2745F3E762A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterForeignServerStmt");
               Build_Access.Set_Field (Locals (1), "servername", Values (3));
               Build_Access.Set_Field (Locals (1), "version", Values (4));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Build_Access.Set_Field (Locals (1), "has_version", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#78AEA22D6EAE879A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (7));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "keys", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "including", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexname", Values (2));
               Build_Access.Set_Field (Locals (1), "indexspace", Builders.No_Value);
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Version_Invoke (Build_Access, "processCASbits", (1 => Values (3), 2 => Builders.Number
                       (Interfaces.Integer_64 (Locations (3))), 3 => Builders.Text ("UNIQUE"), 4 =>
                       Builders.Field_Reference (Locals (1), "deferrable"), 5 => Builders.Field_Reference (Locals (1),
                       "initdeferred"), 6 => Builders.No_Value, 7 => Builders.No_Value, 8 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Locals (1);
            end;
         when 16#78C8A072EA37D30E# =>
               Result := Version_Invoke (Build_Access, "makeString", (1 => Builders.Text ("default")));
         when 16#78CE5E727B2D6EC4# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "SystemFuncName", (1 => Builders.Text ("similar_to_escape"))), 2 => Version_Invoke (Build_Access,
                  "list_make2_impl", (1 => Builders.Number (1), 2 => Values (5), 3 => Values (7))), 3 =>
                  Builders.Number (0), 4 => Builders.Number (Interfaces.Integer_64 (Locations (2)))));
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (9), 2 =>
                  Builders.Text ("!~"), 3 => Values (1), 4 => Locals (1), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
            end;
         when 16#79099CCFA1F75FA3# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 4) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (1);
               Locals (2) := Values (3);
               Locals (3) := Build_Access.Cell_Element (Version_Invoke (Build_Access, "list_nth_cell", (1 => Values
                  (1), 2 => Builders.Number (1))));
               Locals (4) := Build_Access.Cell_Element (Version_Invoke (Build_Access, "list_nth_cell", (1 => Values
                  (3), 2 => Builders.Number (1))));
               if Semantics.Truth (Semantics.Binary ("&", Locals (1), Locals (2))) then
                  declare
                     Ignored : constant Builders.Dynamic_Value :=
                       Version_Invoke (Build_Access, "scanner_yyerror", (1 => Builders.Text
                          ("duplicate trigger events specified"), 2 => Builders.No_Value));
                  begin
                     null;
                  end;
               end if;
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 =>
                  Version_Invoke (Build_Access, "makeInteger", (1 => Semantics.Binary ("|", Locals (1), Locals (2)))),
                  3 => Version_Invoke (Build_Access, "list_concat", (1 => Locals (3), 2 => Locals (4)))));
            end;
         when 16#790F2233B5ABFD59# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (12), 2 =>
                  Builders.Text ("BETWEEN SYMMETRIC"), 3 => Values (1), 4 => Version_Invoke (Build_Access,
                  "list_make2_impl", (1 => Builders.Number (1), 2 => Values (4), 3 => Values (6))), 5 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2)))));
         when 16#790FEE5D9EF409BD# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("sequence_name"), 2 =>
                  Values (3), 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#7919FC866BEECA48# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (2);
               Build_Access.Set_Field (Locals (1), "nnames", Builders.Number (2));
               Parse_Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 =>
                  Version_Invoke (Build_Access, "makeRawStmt", (1 => Locals (1), 2 => Builders.Number (0)))));
            end;
         when 16#792708E3D403F6B4# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("VariableSetStmt");
               Build_Access.Set_Field (Locals (1), "kind", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "name", Builders.Text ("TRANSACTION"));
               Build_Access.Set_Field (Locals (1), "args", Values (2));
               Build_Access.Set_Field (Locals (1), "jumble_args", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "location", Semantics.Unary ("-", Builders.Number (1)));
               Result := Locals (1);
            end;
         when 16#7936075F5329FF76# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ReplicaIdentityStmt");
               Build_Access.Set_Field (Locals (1), "identity_type", Builders.Number (105));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 16#79555F7E8E282647# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (32));
               Build_Access.Set_Field (Locals (1), "objects", Values (3));
               Build_Access.Set_Field (Locals (1), "behavior", Values (4));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#796F2080F5871C81# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterObjectSchemaStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (39));
               Build_Access.Set_Field (Locals (1), "object", Values (3));
               Build_Access.Set_Field (Locals (1), "newschema", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#798CA0B970D4EE76# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (18));
               Build_Access.Set_Field (Locals (1), "relation", Values (6));
               Build_Access.Set_Field (Locals (1), "subname", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "newname", Values (9));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#799C47182CA0EAB4# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (2);
               Build_Access.Set_Field (Locals (1), "nnames", Builders.Number (3));
               Parse_Result := Version_Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 =>
                  Version_Invoke (Build_Access, "makeRawStmt", (1 => Locals (1), 2 => Builders.Number (0)))));
            end;
         when 16#79A424226A2364D6# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 3) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ColumnRef");
               Locals (2) := Build_Access.New_Object ("ResTarget");
               Locals (3) := Build_Access.New_Object ("SelectStmt");
               Build_Access.Set_Field (Locals (1), "fields", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (231), 2 => Build_Access.New_Object ("A_Star"))));
               Build_Access.Set_Field (Locals (1), "location", Semantics.Unary ("-", Builders.Number (1)));
               Build_Access.Set_Field (Locals (2), "name", Builders.No_Value);
               Build_Access.Set_Field (Locals (2), "indirection", Builders.No_Value);
               Build_Access.Set_Field (Locals (2), "val", Locals (1));
               Build_Access.Set_Field (Locals (2), "location", Semantics.Unary ("-", Builders.Number (1)));
               Build_Access.Set_Field (Locals (3), "targetList", Version_Invoke (Build_Access, "list_make1_impl", (1
                  => Builders.Number (231), 2 => Locals (2))));
               Build_Access.Set_Field (Locals (3), "fromClause", Version_Invoke (Build_Access, "list_make1_impl", (1
                  => Builders.Number (231), 2 => Values (2))));
               Result := Locals (3);
            end;
         when 16#79B2518011D4ABBB# =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("GLOBAL is deprecated in temporary table creation"));
               Result := Values (4);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (116));
         when 16#7A02404CF80AAB62# =>
               Result := Builders.Number (48);
         when 16#7A20B405F4116542# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterOwnerStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (26));
               Build_Access.Set_Field (Locals (1), "object", Version_Invoke (Build_Access, "lcons", (1 =>
                  Version_Invoke (Build_Access, "makeString", (1 => Values (6))), 2 => Values (4))));
               Build_Access.Set_Field (Locals (1), "newowner", Values (9));
               Result := Locals (1);
            end;
         when 16#7A386E20EB04C086# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ReplicaIdentityStmt");
               Build_Access.Set_Field (Locals (1), "identity_type", Builders.Number (100));
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 16#7A80D2D241F6F6B0# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterOwnerStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (39));
               Build_Access.Set_Field (Locals (1), "object", Values (3));
               Build_Access.Set_Field (Locals (1), "newowner", Values (6));
               Result := Locals (1);
            end;
         when 16#7A8B198C0FE9F1BF# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("JsonObjectAgg");
               Build_Access.Set_Field (Locals (1), "arg", Values (3));
               Build_Access.Set_Field (Locals (1), "absent_on_null", Values (4));
               Build_Access.Set_Field (Locals (1), "unique", Values (5));
               Build_Access.Set_Field (Locals (1), "constructor", Build_Access.New_Object ("JsonAggConstructor"));
               Build_Access.Set_Field (Locals (1), "constructor.output", Values (6));
               Build_Access.Set_Field (Locals (1), "constructor.agg_order", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "constructor.location", Builders.Number (Interfaces.Integer_64
                  (Locations (1))));
               Result := Locals (1);
            end;
         when 16#7A910CF9AAEB1CAE# =>
               Result := Builders.Text ("^");
         when 16#7A9D3CAC0DE0B5E5# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (231), 2 =>
                  Builders.No_Value, 3 => Values (4)));
         when 16#7AAA38096C4C0EC7# =>
               Result := Version_Invoke (Build_Access, "SystemTypeName", (1 => Values (1)));
               if Semantics.Truth (Semantics.Binary ("==", Version_Invoke (Build_Access, "strcmp", (1 => Values (1), 2
                  => Builders.Text ("bpchar"))), Builders.Number (0))) then
                  Build_Access.Set_Field (Result, "typmods", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                     Builders.Number (1), 2 => Version_Invoke (Build_Access, "makeIntConst", (1 => Builders.Number
                     (1), 2 => Semantics.Unary ("-", Builders.Number (1)))))));
               end if;
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 16#7ADB4D1307C7D5CE# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ObjectWithArgs");
               Build_Access.Set_Field (Locals (1), "objname", Version_Invoke (Build_Access, "check_func_name", (1 =>
                  Version_Invoke (Build_Access, "lcons", (1 => Version_Invoke (Build_Access, "makeString", (1 =>
                  Values (1))), 2 => Values (2))), 2 => Builders.No_Value)));
               Build_Access.Set_Field (Locals (1), "args_unspecified", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#7AE271631F30FA45# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (40));
               Build_Access.Set_Field (Locals (1), "relation", Values (5));
               Build_Access.Set_Field (Locals (1), "subname", Values (8));
               Build_Access.Set_Field (Locals (1), "newname", Values (10));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#7B3A23E9F4C98AEB# =>
               Result := Builders.Number (116);
         when 16#7B450568547B9602# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateEventTrigStmt");
               Build_Access.Set_Field (Locals (1), "trigname", Values (4));
               Build_Access.Set_Field (Locals (1), "eventname", Values (6));
               Build_Access.Set_Field (Locals (1), "whenclause", Values (8));
               Build_Access.Set_Field (Locals (1), "funcname", Values (11));
               Result := Locals (1);
            end;
         when 16#7B501F25A10B870F# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterFunctionStmt");
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (28));
               Build_Access.Set_Field (Locals (1), "func", Values (3));
               Build_Access.Set_Field (Locals (1), "actions", Values (4));
               Result := Locals (1);
            end;
         when 16#7B832F41362F81A8# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterEnumStmt");
               Build_Access.Set_Field (Locals (1), "typeName", Values (3));
               Build_Access.Set_Field (Locals (1), "oldVal", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "newVal", Values (7));
               Build_Access.Set_Field (Locals (1), "newValNeighbor", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "newValIsAfter", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "skipIfNewValExists", Values (6));
               Result := Locals (1);
            end;
         when 16#7B905A0212CB6866# =>
               Result := Version_Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (5), 2 =>
                  Builders.Text ("="), 3 => Values (3), 4 => Values (5), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 16#7BC801852C548350# =>
               Result := Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number (1), 2 => Values (4),
                  3 => Version_Invoke (Build_Access, "makeInteger", (1 => Builders.Number (0)))));
         when 16#7BD9949D8A35C367# =>
               Result := Builders.Text ("varchar");
         when 16#7C1A48F6E3B995F1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (58));
               Build_Access.Set_Field (Locals (1), "def", Values (3));
               Result := Locals (1);
            end;
         when 16#7C30C74C147921D6# =>
               Result := Build_Access.New_Object ("IntoClause");
               Build_Access.Set_Field (Result, "rel", Values (2));
               Build_Access.Set_Field (Result, "colNames", Builders.No_Value);
               Build_Access.Set_Field (Result, "options", Builders.No_Value);
               Build_Access.Set_Field (Result, "onCommit", Builders.Number (0));
               Build_Access.Set_Field (Result, "tableSpaceName", Builders.No_Value);
               Build_Access.Set_Field (Result, "viewQuery", Builders.No_Value);
               Build_Access.Set_Field (Result, "skipData", Builders.Number (0));
         when 16#7C4586A7C15F463D# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (65));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7C5144A3714D81E7# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Version_Invoke (Build_Access, "makeFuncCall", (1 => Values (1), 2 => Version_Invoke
                  (Build_Access, "lappend", (1 => Values (3), 2 => Values (6))), 3 => Builders.Number (0), 4 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
               Build_Access.Set_Field (Locals (1), "func_variadic", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "agg_order", Values (7));
               Result := Locals (1);
            end;
         when 16#7C5D0CAA1EF41C55# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DropStmt");
               Build_Access.Set_Field (Locals (1), "objects", Version_Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Version_Invoke (Build_Access, "lcons", (1 => Version_Invoke (Build_Access,
                  "makeString", (1 => Values (8))), 2 => Values (6))))));
               Build_Access.Set_Field (Locals (1), "removeType", Builders.Number (26));
               Build_Access.Set_Field (Locals (1), "behavior", Values (9));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "concurrent", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7C692A48B436899C# =>
               Result := Version_Invoke (Build_Access, "makeNotExpr", (1 => Version_Invoke (Build_Access,
                  "makeFuncCall", (1 => Version_Invoke (Build_Access, "SystemFuncName", (1 => Builders.Text
                  ("is_normalized"))), 2 => Version_Invoke (Build_Access, "list_make2_impl", (1 => Builders.Number
                  (231), 2 => Values (1), 3 => Version_Invoke (Build_Access, "makeStringConst", (1 => Values (4), 2 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (4))))))), 3 => Builders.Number (3), 4 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (2))))), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (2)))));
         when 16#7C891E32B3ECBEB2# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterObjectSchemaStmt");
               Build_Access.Set_Field (Locals (1), "objectType", Builders.Number (47));
               Build_Access.Set_Field (Locals (1), "object", Values (3));
               Build_Access.Set_Field (Locals (1), "newschema", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7C8C829ED1716529# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (3);
               Build_Access.Set_Field (Locals (1), "is_local", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7D0C2E0796A8FDE0# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (38));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 16#7D37A38FD4BBB73A# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ViewStmt");
               Build_Access.Set_Field (Locals (1), "view", Values (5));
               Build_Access.Set_Field (Locals (1), "view.relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "aliases", Values (7));
               Build_Access.Set_Field (Locals (1), "query", Version_Invoke (Build_Access, "makeRecursiveViewSelect",
                  (1 => Build_Access.Field (Locals (1), "view.relname"), 2 => Build_Access.Field (Locals (1),
                  "aliases"), 3 => Values (11))));
               Build_Access.Set_Field (Locals (1), "replace", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "options", Values (9));
               Build_Access.Set_Field (Locals (1), "withCheckOption", Values (12));
               if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (1), "withCheckOption"),
                  Builders.Number (0))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("WITH CHECK OPTION not supported on recursive views"));
               end if;
               Result := Locals (1);
            end;
         when 16#7D93BF540D24976D# =>
               Result := Builders.Number (110);
         when 16#7DE9C89E4462AB89# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateSchemaStmt");
               Build_Access.Set_Field (Locals (1), "schemaname", Values (3));
               Build_Access.Set_Field (Locals (1), "authrole", Values (5));
               Build_Access.Set_Field (Locals (1), "schemaElts", Values (6));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7E53CCFD16B28A25# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("FunctionParameter");
               Build_Access.Set_Field (Locals (1), "name", Values (2));
               Build_Access.Set_Field (Locals (1), "argType", Values (3));
               Build_Access.Set_Field (Locals (1), "mode", Values (1));
               Build_Access.Set_Field (Locals (1), "defexpr", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#7E71F8BF7BC6374F# =>
               Result := Builders.Text ("delete");
         when 16#7E95DDE5553220A7# =>
               Result := Version_Invoke (Build_Access, "makeNullAConst", (1 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 16#7E98BECDC72E7C19# =>
               Result := Semantics.Binary ("<<", Builders.Number (1), Builders.Number (1));
         when 16#7EB9DC8A37D5D2A1# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CTECycleClause");
               Build_Access.Set_Field (Locals (1), "cycle_col_list", Values (2));
               Build_Access.Set_Field (Locals (1), "cycle_mark_column", Values (4));
               Build_Access.Set_Field (Locals (1), "cycle_mark_value", Values (6));
               Build_Access.Set_Field (Locals (1), "cycle_mark_default", Values (8));
               Build_Access.Set_Field (Locals (1), "cycle_path_column", Values (10));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 16#7EBC7241E04F09C8# =>
               Result := Version_Invoke (Build_Access, "makeFuncCall", (1 => Version_Invoke (Build_Access,
                  "SystemFuncName", (1 => Builders.Text ("system_user"))), 2 => Builders.No_Value, 3 =>
                  Builders.Number (3), 4 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#7F0CE3F62B17802C# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (9));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "pktable", Values (2));
               Build_Access.Set_Field (Locals (1), "fk_attrs", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "pk_attrs", Values (3));
               Build_Access.Set_Field (Locals (1), "fk_matchtype", Values (4));
               Build_Access.Set_Field (Locals (1), "fk_upd_action", Build_Access.Field (Values (5),
                  "updateAction.action"));
               Build_Access.Set_Field (Locals (1), "fk_del_action", Build_Access.Field (Values (5),
                  "deleteAction.action"));
               Build_Access.Set_Field (Locals (1), "fk_del_set_cols", Build_Access.Field (Values (5),
                  "deleteAction.cols"));
               Build_Access.Set_Field (Locals (1), "is_enforced", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "skip_validation", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "initially_valid", Builders.Number (1));
               Result := Locals (1);
            end;
         when 16#7F187A5AD22649B5# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DiscardStmt");
               Build_Access.Set_Field (Locals (1), "target", Builders.Number (0));
               Result := Locals (1);
            end;
         when 16#7F20903BA7FEFD58# =>
               Result := Version_Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("validator"), 2 =>
                  Builders.No_Value, 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 16#7F266EE43D165248# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateOpClassItem");
               Build_Access.Set_Field (Locals (1), "itemtype", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "number", Values (2));
               Build_Access.Set_Field (Locals (1), "class_args", Values (4));
               Result := Locals (1);
            end;
         when 16#7F30D7713FDF23F4# =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("RenameStmt");
               Build_Access.Set_Field (Locals (1), "renameType", Builders.Number (12));
               Build_Access.Set_Field (Locals (1), "object", Values (3));
               Build_Access.Set_Field (Locals (1), "newname", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when others => null;
      end case;
   end Reduce;

end Flyology.Postgres.SQL.Native.Action_Catalog_Chunk_07;
