--  Generated by tools/generate_native_actions.py.  Do not edit.
with Flyology.Postgres.SQL.Native.Action_Helper_Catalog;
with Flyology.Postgres.SQL.Native.Semantics;

package body Flyology.Postgres.SQL.Native.Actions_V16_Support is

   function Invoke
     (Build : not null access Builders.Builder; Name : String;
      Arguments : Builders.Semantic_Array) return Builders.Dynamic_Value
   is
   begin
      if Name = "SplitColQualList" then
         return Action_Helper_Catalog.Execute
           (16#FA2F42DFC007F35C#, Build, Arguments, Invoke'Access);
      elsif Name = "SystemFuncName" then
         return Action_Helper_Catalog.Execute
           (16#C7FCD1F523EC0D3A#, Build, Arguments, Invoke'Access);
      elsif Name = "SystemTypeName" then
         return Action_Helper_Catalog.Execute
           (16#A643245B22B3DBB0#, Build, Arguments, Invoke'Access);
      elsif Name = "TableFuncTypeName" then
         return Action_Helper_Catalog.Execute
           (16#D13641D1795AD382#, Build, Arguments, Invoke'Access);
      elsif Name = "check_func_name" then
         return Action_Helper_Catalog.Execute
           (16#27D949CDD45FD683#, Build, Arguments, Invoke'Access);
      elsif Name = "check_indirection" then
         return Action_Helper_Catalog.Execute
           (16#5EC15A33C3C72FAB#, Build, Arguments, Invoke'Access);
      elsif Name = "check_qualified_name" then
         return Action_Helper_Catalog.Execute
           (16#D0BC376FAB9E3137#, Build, Arguments, Invoke'Access);
      elsif Name = "extractAggrArgTypes" then
         return Action_Helper_Catalog.Execute
           (16#9C3D6FE7C8960AAB#, Build, Arguments, Invoke'Access);
      elsif Name = "extractArgTypes" then
         return Action_Helper_Catalog.Execute
           (16#6C898ACAEB92FE01#, Build, Arguments, Invoke'Access);
      elsif Name = "insertSelectOptions" then
         return Action_Helper_Catalog.Execute
           (16#6E85272A53714CE9#, Build, Arguments, Invoke'Access);
      elsif Name = "makeAArrayExpr" then
         return Action_Helper_Catalog.Execute
           (16#DE3E5DB64F1C6F84#, Build, Arguments, Invoke'Access);
      elsif Name = "makeAConst" then
         return Action_Helper_Catalog.Execute
           (16#F8D53620755B0E05#, Build, Arguments, Invoke'Access);
      elsif Name = "makeAndExpr" then
         return Action_Helper_Catalog.Execute
           (16#4F347BA5438337CD#, Build, Arguments, Invoke'Access);
      elsif Name = "makeBitStringConst" then
         return Action_Helper_Catalog.Execute
           (16#D8BAC86166ED2F3F#, Build, Arguments, Invoke'Access);
      elsif Name = "makeBoolAConst" then
         return Action_Helper_Catalog.Execute
           (16#8DA04820C722108A#, Build, Arguments, Invoke'Access);
      elsif Name = "makeColumnRef" then
         return Action_Helper_Catalog.Execute
           (16#BA657157CC1E813F#, Build, Arguments, Invoke'Access);
      elsif Name = "makeFloatConst" then
         return Action_Helper_Catalog.Execute
           (16#DCCE7877C3AEC518#, Build, Arguments, Invoke'Access);
      elsif Name = "makeIntConst" then
         return Action_Helper_Catalog.Execute
           (16#BB687F8A7C0BD564#, Build, Arguments, Invoke'Access);
      elsif Name = "makeNotExpr" then
         return Action_Helper_Catalog.Execute
           (16#091D5CBCCD040968#, Build, Arguments, Invoke'Access);
      elsif Name = "makeNullAConst" then
         return Action_Helper_Catalog.Execute
           (16#904322BAC0DADA84#, Build, Arguments, Invoke'Access);
      elsif Name = "makeOrExpr" then
         return Action_Helper_Catalog.Execute
           (16#275512D936553B7D#, Build, Arguments, Invoke'Access);
      elsif Name = "makeOrderedSetArgs" then
         return Action_Helper_Catalog.Execute
           (16#748E4BE641F63D90#, Build, Arguments, Invoke'Access);
      elsif Name = "makeParamRef" then
         return Action_Helper_Catalog.Execute
           (16#811171889542DB23#, Build, Arguments, Invoke'Access);
      elsif Name = "makeParamRefCast" then
         return Action_Helper_Catalog.Execute
           (16#2887DB8AA85898C5#, Build, Arguments, Invoke'Access);
      elsif Name = "makeRangeVarFromAnyName" then
         return Action_Helper_Catalog.Execute
           (16#A93B53E85E865527#, Build, Arguments, Invoke'Access);
      elsif Name = "makeRangeVarFromQualifiedName" then
         return Action_Helper_Catalog.Execute
           (16#8910C65420BCA6C5#, Build, Arguments, Invoke'Access);
      elsif Name = "makeRawStmt" then
         return Action_Helper_Catalog.Execute
           (16#93792A469B7A3121#, Build, Arguments, Invoke'Access);
      elsif Name = "makeRecursiveViewSelect" then
         return Action_Helper_Catalog.Execute
           (16#087D0E3D5813A37A#, Build, Arguments, Invoke'Access);
      elsif Name = "makeRoleSpec" then
         return Action_Helper_Catalog.Execute
           (16#C5C52660A9D5380F#, Build, Arguments, Invoke'Access);
      elsif Name = "makeSQLValueFunction" then
         return Action_Helper_Catalog.Execute
           (16#D5AD1747C097ACEE#, Build, Arguments, Invoke'Access);
      elsif Name = "makeSetOp" then
         return Action_Helper_Catalog.Execute
           (16#68D312CB35519B74#, Build, Arguments, Invoke'Access);
      elsif Name = "makeStringConst" then
         return Action_Helper_Catalog.Execute
           (16#D0D86F5637D1D598#, Build, Arguments, Invoke'Access);
      elsif Name = "makeStringConstCast" then
         return Action_Helper_Catalog.Execute
           (16#55F9455A76949A6A#, Build, Arguments, Invoke'Access);
      elsif Name = "makeTypeCast" then
         return Action_Helper_Catalog.Execute
           (16#B080137DA499522F#, Build, Arguments, Invoke'Access);
      elsif Name = "makeXmlExpr" then
         return Action_Helper_Catalog.Execute
           (16#6BBB31B226558CCB#, Build, Arguments, Invoke'Access);
      elsif Name = "mergeTableFuncParameters" then
         return Action_Helper_Catalog.Execute
           (16#415F270E2DA7DA0B#, Build, Arguments, Invoke'Access);
      elsif Name = "parsePartitionStrategy" then
         return Action_Helper_Catalog.Execute
           (16#3C4189025405F9E9#, Build, Arguments, Invoke'Access);
      elsif Name = "preprocess_pubobj_list" then
         return Action_Helper_Catalog.Execute
           (16#57C3CF5C19420845#, Build, Arguments, Invoke'Access);
      elsif Name = "processCASbits" then
         return Action_Helper_Catalog.Execute
           (16#893F607ED338F875#, Build, Arguments, Invoke'Access);
      elsif Name = "updateRawStmtEnd" then
         return Action_Helper_Catalog.Execute
           (16#5134E6CCB055FF9F#, Build, Arguments, Invoke'Access);
      elsif Name = "makeA_Expr" then
         return Action_Helper_Catalog.Execute
           (16#64F996DCDC8969A3#, Build, Arguments, Invoke'Access);
      elsif Name = "makeAlias" then
         return Action_Helper_Catalog.Execute
           (16#617582D2B7884EC0#, Build, Arguments, Invoke'Access);
      elsif Name = "makeBoolExpr" then
         return Action_Helper_Catalog.Execute
           (16#020198BB5473D9AF#, Build, Arguments, Invoke'Access);
      elsif Name = "makeDefElem" then
         return Action_Helper_Catalog.Execute
           (16#BEC913BB37E0E54C#, Build, Arguments, Invoke'Access);
      elsif Name = "makeDefElemExtended" then
         return Action_Helper_Catalog.Execute
           (16#1CDEB892F05D979A#, Build, Arguments, Invoke'Access);
      elsif Name = "makeFuncCall" then
         return Action_Helper_Catalog.Execute
           (16#22FFAFE0374CABC0#, Build, Arguments, Invoke'Access);
      elsif Name = "makeGroupingSet" then
         return Action_Helper_Catalog.Execute
           (16#0905CEAF06766F09#, Build, Arguments, Invoke'Access);
      elsif Name = "makeJsonEncoding" then
         return Action_Helper_Catalog.Execute
           (16#2DA246D38E56F8E3#, Build, Arguments, Invoke'Access);
      elsif Name = "makeJsonFormat" then
         return Action_Helper_Catalog.Execute
           (16#184B2C2B80265EDF#, Build, Arguments, Invoke'Access);
      elsif Name = "makeJsonIsPredicate" then
         return Action_Helper_Catalog.Execute
           (16#0276711F513B2E09#, Build, Arguments, Invoke'Access);
      elsif Name = "makeJsonKeyValue" then
         return Action_Helper_Catalog.Execute
           (16#63D6AAEA64E329FB#, Build, Arguments, Invoke'Access);
      elsif Name = "makeJsonValueExpr" then
         return Action_Helper_Catalog.Execute
           (16#B110EB2ED020AFC4#, Build, Arguments, Invoke'Access);
      elsif Name = "makeRangeVar" then
         return Action_Helper_Catalog.Execute
           (16#34C55F502B33A2DB#, Build, Arguments, Invoke'Access);
      elsif Name = "makeSimpleA_Expr" then
         return Action_Helper_Catalog.Execute
           (16#8FDA236164A87DAF#, Build, Arguments, Invoke'Access);
      elsif Name = "makeTypeName" then
         return Action_Helper_Catalog.Execute
           (16#23454D5FC9E7CBB8#, Build, Arguments, Invoke'Access);
      elsif Name = "makeTypeNameFromNameList" then
         return Action_Helper_Catalog.Execute
           (16#B619383CD3A8D9A3#, Build, Arguments, Invoke'Access);
      elsif Name = "makeVacuumRelation" then
         return Action_Helper_Catalog.Execute
           (16#9C5F2C4BED0F2D60#, Build, Arguments, Invoke'Access);
      else
         return Semantics.Invoke (Build, Name, Arguments);
      end if;
   end Invoke;

end Flyology.Postgres.SQL.Native.Actions_V16_Support;
