--  Generated by tools/generate_native_actions.py.  Do not edit.
with Interfaces;
with Flyology.Postgres.SQL.Native.Builders;
with Flyology.Postgres.SQL.Native.Semantics;
with Flyology.Postgres.SQL.Native.Actions_V14_Support;

package body Flyology.Postgres.SQL.Native.Actions_V14_Chunk_03 is

   pragma Style_Checks (Off);
   use type Interfaces.Integer_64;

   function Invoke
     (Build : not null access Builders.Builder; Name : String;
      Arguments : Builders.Semantic_Array) return Builders.Dynamic_Value
      renames Actions_V14_Support.Invoke;

   procedure Reduce
     (Build        : aliased in out Builders.Builder;
      Rule         : Positive;
      Values       : Builders.Semantic_Array;
      Locations    : Builders.Location_Array;
      Result       : in out Builders.Dynamic_Value;
      Location     : in out Integer;
      Parse_Result : in out Builders.Dynamic_Value)
   is
      Build_Access : constant not null access Builders.Builder :=
        Build'Unchecked_Access;
   begin
      case Rule is
         when 359 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (62));
               Build_Access.Set_Field (Locals (1), "def", Values (1));
               Result := Locals (1);
            end;
         when 360 =>
               Result := Values (3);
         when 361 =>
               Result := Builders.No_Value;
         when 362 =>
               Result := Builders.Number (1);
         when 363 =>
               Result := Builders.Number (0);
         when 364 =>
               Result := Builders.Number (0);
         when 365 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CollateClause");
               Build_Access.Set_Field (Locals (1), "arg", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "collname", Values (2));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 366 =>
               Result := Builders.No_Value;
         when 367 =>
               Result := Values (2);
         when 368 =>
               Result := Builders.No_Value;
         when 369 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ReplicaIdentityStmt");
               Build_Access.Set_Field (Locals (1), "identity_type", Builders.Number (110));
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 370 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ReplicaIdentityStmt");
               Build_Access.Set_Field (Locals (1), "identity_type", Builders.Number (102));
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 371 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ReplicaIdentityStmt");
               Build_Access.Set_Field (Locals (1), "identity_type", Builders.Number (100));
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 372 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ReplicaIdentityStmt");
               Build_Access.Set_Field (Locals (1), "identity_type", Builders.Number (105));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 373 =>
               Result := Values (2);
         when 374 =>
               Result := Values (2);
         when 375 =>
               Result := Builders.No_Value;
         when 376 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 377 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 378 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Values (3), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 379 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Builders.No_Value, 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 380 =>
               Result := Invoke (Build_Access, "makeDefElemExtended", (1 => Values (1), 2 => Values (3), 3 => Values
                  (5), 4 => Builders.Number (0), 5 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 381 =>
               Result := Invoke (Build_Access, "makeDefElemExtended", (1 => Values (1), 2 => Values (3), 3 =>
                  Builders.No_Value, 4 => Builders.Number (0), 5 => Builders.Number (Interfaces.Integer_64 (Locations
                  (1)))));
         when 382 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 383 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 384 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("restart"), 2 => Builders.No_Value,
                  3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 385 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("restart"), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 386 =>
               if Semantics.Truth (Semantics.Binary ("||", Semantics.Binary ("||", Semantics.Binary ("==", Invoke
                  (Build_Access, "strcmp", (1 => Build_Access.Field (Values (2), "defname"), 2 => Builders.Text
                  ("as"))), Builders.Number (0)), Semantics.Binary ("==", Invoke (Build_Access, "strcmp", (1 =>
                  Build_Access.Field (Values (2), "defname"), 2 => Builders.Text ("restart"))), Builders.Number (0))),
                  Semantics.Binary ("==", Invoke (Build_Access, "strcmp", (1 => Build_Access.Field (Values (2),
                  "defname"), 2 => Builders.Text ("owned_by"))), Builders.Number (0)))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("sequence option ""%s"" not supported here"));
               end if;
               Result := Values (2);
         when 387 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("generated"), 2 => Invoke
                  (Build_Access, "makeInteger", (1 => Values (3))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 388 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 4) :=
                 (others => Builders.No_Value);
            begin
               Locals (2) := Build_Access.New_Object ("PartitionBoundSpec");
               Build_Access.Set_Field (Locals (2), "strategy", Builders.Number (104));
               Build_Access.Set_Field (Locals (2), "modulus", Semantics.Set_Field (Build_Access, Locals (2),
                  "remainder", Semantics.Unary ("-", Builders.Number (1))));
               declare
                  Loop_List : constant Builders.Dynamic_Value := Values (5);
               begin
                  for Loop_Index in 1 .. Build_Access.Length (Loop_List) loop
                     Locals (1) := Build_Access.Cell (Loop_List, Loop_Index);
                     Locals (4) := Build_Access.Cell_Element (Locals (1));
                     if Semantics.Truth (Semantics.Binary ("==", Invoke (Build_Access, "strcmp", (1 =>
                        Build_Access.Field (Locals (4), "defname"), 2 => Builders.Text ("modulus"))), Builders.Number
                        (0))) then
                        if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (2), "modulus"),
                           Semantics.Unary ("-", Builders.Number (1)))) then
                           raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                              ("modulus for hash partition provided more than once"));
                        end if;
                        Build_Access.Set_Field (Locals (2), "modulus", Invoke (Build_Access, "defGetInt32", (1 =>
                           Locals (4))));
                     else
                        if Semantics.Truth (Semantics.Binary ("==", Invoke (Build_Access, "strcmp", (1 =>
                           Build_Access.Field (Locals (4), "defname"), 2 => Builders.Text ("remainder"))),
                           Builders.Number (0))) then
                           if Semantics.Truth (Semantics.Binary ("!=", Build_Access.Field (Locals (2), "remainder"),
                              Semantics.Unary ("-", Builders.Number (1)))) then
                              raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                                 ("remainder for hash partition provided more than once"));
                           end if;
                           Build_Access.Set_Field (Locals (2), "remainder", Invoke (Build_Access, "defGetInt32", (1 =>
                              Locals (4))));
                        else
                           raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                              ("unrecognized hash partition bound specification ""%s"""));
                        end if;
                     end if;
                     <<Continue_Loop_1>>
                     null;
                  end loop;
               end;
               if Semantics.Truth (Semantics.Binary ("==", Build_Access.Field (Locals (2), "modulus"), Semantics.Unary
                  ("-", Builders.Number (1)))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("modulus for hash partition must be specified"));
               end if;
               if Semantics.Truth (Semantics.Binary ("==", Build_Access.Field (Locals (2), "remainder"),
                  Semantics.Unary ("-", Builders.Number (1)))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("remainder for hash partition must be specified"));
               end if;
               Build_Access.Set_Field (Locals (2), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (3))));
               Result := Locals (2);
            end;
         when 389 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionBoundSpec");
               Build_Access.Set_Field (Locals (1), "strategy", Builders.Number (108));
               Build_Access.Set_Field (Locals (1), "is_default", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "listdatums", Values (5));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (3))));
               Result := Locals (1);
            end;
         when 390 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionBoundSpec");
               Build_Access.Set_Field (Locals (1), "strategy", Builders.Number (114));
               Build_Access.Set_Field (Locals (1), "is_default", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "lowerdatums", Values (5));
               Build_Access.Set_Field (Locals (1), "upperdatums", Values (9));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (3))));
               Result := Locals (1);
            end;
         when 391 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PartitionBoundSpec");
               Build_Access.Set_Field (Locals (1), "is_default", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 392 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Invoke (Build_Access,
                  "makeInteger", (1 => Values (2))), 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 393 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 394 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 395 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableStmt");
               Build_Access.Set_Field (Locals (1), "relation", Invoke (Build_Access, "makeRangeVarFromAnyName", (1 =>
                  Values (3), 2 => Builders.Number (Interfaces.Integer_64 (Locations (3))), 3 => Builders.No_Value)));
               Build_Access.Set_Field (Locals (1), "cmds", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (47));
               Result := Locals (1);
            end;
         when 396 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 397 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 398 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "def", Values (3));
               Build_Access.Set_Field (Locals (1), "behavior", Values (4));
               Result := Locals (1);
            end;
         when 399 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (14));
               Build_Access.Set_Field (Locals (1), "name", Values (5));
               Build_Access.Set_Field (Locals (1), "behavior", Values (6));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (1));
               Result := Locals (1);
            end;
         when 400 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (14));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "behavior", Values (4));
               Build_Access.Set_Field (Locals (1), "missing_ok", Builders.Number (0));
               Result := Locals (1);
            end;
         when 401 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("AlterTableCmd");
               Locals (2) := Build_Access.New_Object ("ColumnDef");
               Build_Access.Set_Field (Locals (1), "subtype", Builders.Number (29));
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Build_Access.Set_Field (Locals (1), "def", Locals (2));
               Build_Access.Set_Field (Locals (1), "behavior", Values (8));
               Build_Access.Set_Field (Locals (2), "typeName", Values (6));
               Build_Access.Set_Field (Locals (2), "collClause", Values (7));
               Build_Access.Set_Field (Locals (2), "raw_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (2), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (3))));
               Result := Locals (1);
            end;
         when 402 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ClosePortalStmt");
               Build_Access.Set_Field (Locals (1), "portalname", Values (2));
               Result := Locals (1);
            end;
         when 403 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ClosePortalStmt");
               Build_Access.Set_Field (Locals (1), "portalname", Builders.No_Value);
               Result := Locals (1);
            end;
         when 404 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CopyStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "query", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "attlist", Values (4));
               Build_Access.Set_Field (Locals (1), "is_from", Values (5));
               Build_Access.Set_Field (Locals (1), "is_program", Values (6));
               Build_Access.Set_Field (Locals (1), "filename", Values (7));
               Build_Access.Set_Field (Locals (1), "whereClause", Values (11));
               if Semantics.Truth (Semantics.Binary ("&&", Build_Access.Field (Locals (1), "is_program"),
                  Semantics.Binary ("==", Build_Access.Field (Locals (1), "filename"), Builders.No_Value))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("STDIN/STDOUT not allowed with PROGRAM"));
               end if;
               if Semantics.Truth (Semantics.Binary ("&&", Semantics.Unary ("!", Build_Access.Field (Locals (1),
                  "is_from")), Semantics.Binary ("!=", Build_Access.Field (Locals (1), "whereClause"),
                  Builders.No_Value))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("WHERE clause not allowed with COPY TO"));
               end if;
               Build_Access.Set_Field (Locals (1), "options", Builders.No_Value);
               if Semantics.Truth (Values (2)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Values (2))));
               end if;
               if Semantics.Truth (Values (8)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "lappend", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Values (8))));
               end if;
               if Semantics.Truth (Values (10)) then
                  Build_Access.Set_Field (Locals (1), "options", Invoke (Build_Access, "list_concat", (1 =>
                     Build_Access.Field (Locals (1), "options"), 2 => Values (10))));
               end if;
               Result := Locals (1);
            end;
         when 405 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CopyStmt");
               Build_Access.Set_Field (Locals (1), "relation", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "query", Values (3));
               Build_Access.Set_Field (Locals (1), "attlist", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "is_from", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_program", Values (6));
               Build_Access.Set_Field (Locals (1), "filename", Values (7));
               Build_Access.Set_Field (Locals (1), "options", Values (9));
               if Semantics.Truth (Semantics.Binary ("&&", Build_Access.Field (Locals (1), "is_program"),
                  Semantics.Binary ("==", Build_Access.Field (Locals (1), "filename"), Builders.No_Value))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("STDIN/STDOUT not allowed with PROGRAM"));
               end if;
               Result := Locals (1);
            end;
         when 406 =>
               Result := Builders.Number (1);
         when 407 =>
               Result := Builders.Number (0);
         when 408 =>
               Result := Builders.Number (1);
         when 409 =>
               Result := Builders.Number (0);
         when 410 =>
               Result := Values (1);
         when 411 =>
               Result := Builders.No_Value;
         when 412 =>
               Result := Builders.No_Value;
         when 413 =>
               Result := Values (1);
         when 414 =>
               Result := Values (2);
         when 415 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 416 =>
               Result := Builders.No_Value;
         when 417 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("format"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Builders.Text ("binary"))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 418 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("freeze"), 2 => Invoke
                  (Build_Access, "makeInteger", (1 => Builders.Number (1))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 419 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("delimiter"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (3))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 420 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("null"), 2 => Invoke (Build_Access,
                  "makeString", (1 => Values (3))), 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 421 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("format"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Builders.Text ("csv"))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 422 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("header"), 2 => Invoke
                  (Build_Access, "makeInteger", (1 => Builders.Number (1))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 423 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("quote"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (3))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 424 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("escape"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (3))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 425 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("force_quote"), 2 => Values (3), 3
                  => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 426 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("force_quote"), 2 =>
                  Build_Access.New_Object ("A_Star"), 3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 427 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("force_not_null"), 2 => Values (4),
                  3 => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 428 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("force_null"), 2 => Values (3), 3
                  => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 429 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("encoding"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (2))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 430 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("format"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Builders.Text ("binary"))), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 431 =>
               Result := Builders.No_Value;
         when 432 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Builders.Text ("delimiter"), 2 => Invoke
                  (Build_Access, "makeString", (1 => Values (3))), 3 => Builders.Number (Interfaces.Integer_64
                  (Locations (2)))));
         when 433 =>
               Result := Builders.No_Value;
         when 436 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 437 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 438 =>
               Result := Invoke (Build_Access, "makeDefElem", (1 => Values (1), 2 => Values (2), 3 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 439 =>
               Result := Invoke (Build_Access, "makeString", (1 => Values (1)));
         when 440 =>
               Result := Values (1);
         when 441 =>
               Result := Build_Access.New_Object ("A_Star");
         when 442 =>
               Result := Values (2);
         when 443 =>
               Result := Builders.No_Value;
         when 444 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 445 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 446 =>
               Result := Invoke (Build_Access, "makeString", (1 => Values (1)));
         when 447 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (4), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (4));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (6));
               Build_Access.Set_Field (Locals (1), "inhRelations", Values (8));
               Build_Access.Set_Field (Locals (1), "partspec", Values (9));
               Build_Access.Set_Field (Locals (1), "ofTypename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (10));
               Build_Access.Set_Field (Locals (1), "options", Values (11));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (12));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (13));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Result := Locals (1);
            end;
         when 448 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (7), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (7));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (9));
               Build_Access.Set_Field (Locals (1), "inhRelations", Values (11));
               Build_Access.Set_Field (Locals (1), "partspec", Values (12));
               Build_Access.Set_Field (Locals (1), "ofTypename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (13));
               Build_Access.Set_Field (Locals (1), "options", Values (14));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (15));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (16));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Result := Locals (1);
            end;
         when 449 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (4), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (4));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (7));
               Build_Access.Set_Field (Locals (1), "inhRelations", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "partspec", Values (8));
               Build_Access.Set_Field (Locals (1), "ofTypename", Invoke (Build_Access, "makeTypeNameFromNameList", (1
                  => Values (6))));
               Build_Access.Set_Field (Locals (1), "ofTypename.location", Builders.Number (Interfaces.Integer_64
                  (Locations (6))));
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (9));
               Build_Access.Set_Field (Locals (1), "options", Values (10));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (11));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (12));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Result := Locals (1);
            end;
         when 450 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (7), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (7));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (10));
               Build_Access.Set_Field (Locals (1), "inhRelations", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "partspec", Values (11));
               Build_Access.Set_Field (Locals (1), "ofTypename", Invoke (Build_Access, "makeTypeNameFromNameList", (1
                  => Values (9))));
               Build_Access.Set_Field (Locals (1), "ofTypename.location", Builders.Number (Interfaces.Integer_64
                  (Locations (9))));
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (12));
               Build_Access.Set_Field (Locals (1), "options", Values (13));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (14));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (15));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Result := Locals (1);
            end;
         when 451 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (4), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (4));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (8));
               Build_Access.Set_Field (Locals (1), "inhRelations", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (231), 2 => Values (7))));
               Build_Access.Set_Field (Locals (1), "partbound", Values (9));
               Build_Access.Set_Field (Locals (1), "partspec", Values (10));
               Build_Access.Set_Field (Locals (1), "ofTypename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (11));
               Build_Access.Set_Field (Locals (1), "options", Values (12));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (13));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (14));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Result := Locals (1);
            end;
         when 452 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateStmt");
               Build_Access.Set_Field (Values (7), "relpersistence", Values (2));
               Build_Access.Set_Field (Locals (1), "relation", Values (7));
               Build_Access.Set_Field (Locals (1), "tableElts", Values (11));
               Build_Access.Set_Field (Locals (1), "inhRelations", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (231), 2 => Values (10))));
               Build_Access.Set_Field (Locals (1), "partbound", Values (12));
               Build_Access.Set_Field (Locals (1), "partspec", Values (13));
               Build_Access.Set_Field (Locals (1), "ofTypename", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "constraints", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "accessMethod", Values (14));
               Build_Access.Set_Field (Locals (1), "options", Values (15));
               Build_Access.Set_Field (Locals (1), "oncommit", Values (16));
               Build_Access.Set_Field (Locals (1), "tablespacename", Values (17));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Result := Locals (1);
            end;
         when 453 =>
               Result := Builders.Number (116);
         when 454 =>
               Result := Builders.Number (116);
         when 455 =>
               Result := Builders.Number (116);
         when 456 =>
               Result := Builders.Number (116);
         when 457 =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("GLOBAL is deprecated in temporary table creation"));
               Result := Builders.Number (116);
         when 458 =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("GLOBAL is deprecated in temporary table creation"));
               Result := Builders.Number (116);
         when 459 =>
               Result := Builders.Number (117);
         when 460 =>
               Result := Builders.Number (112);
         when 461 =>
               Result := Values (1);
         when 462 =>
               Result := Builders.No_Value;
         when 463 =>
               Result := Values (2);
         when 464 =>
               Result := Builders.No_Value;
         when 465 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 466 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 467 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (231), 2 => Values (1)));
         when 468 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 469 =>
               Result := Values (1);
         when 470 =>
               Result := Values (1);
         when 471 =>
               Result := Values (1);
         when 472 =>
               Result := Values (1);
         when 473 =>
               Result := Values (1);
         when 474 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ColumnDef");
               Build_Access.Set_Field (Locals (1), "colname", Values (1));
               Build_Access.Set_Field (Locals (1), "typeName", Values (2));
               Build_Access.Set_Field (Locals (1), "compression", Values (3));
               Build_Access.Set_Field (Locals (1), "inhcount", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_local", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "is_not_null", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_from_type", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "storage", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "raw_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "cooked_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "collOid", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "fdwoptions", Values (4));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "SplitColQualList", (1 => Values (5), 2 => Builders.Field_Reference (Locals
                       (1), "constraints"), 3 => Builders.Field_Reference (Locals (1), "collClause"), 4 =>
                       Builders.No_Value));
               begin
                  null;
               end;
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 475 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ColumnDef");
               Build_Access.Set_Field (Locals (1), "colname", Values (1));
               Build_Access.Set_Field (Locals (1), "typeName", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "inhcount", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_local", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "is_not_null", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_from_type", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "storage", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "raw_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "cooked_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "collOid", Builders.Number (0));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "SplitColQualList", (1 => Values (2), 2 => Builders.Field_Reference (Locals
                       (1), "constraints"), 3 => Builders.Field_Reference (Locals (1), "collClause"), 4 =>
                       Builders.No_Value));
               begin
                  null;
               end;
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 476 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ColumnDef");
               Build_Access.Set_Field (Locals (1), "colname", Values (1));
               Build_Access.Set_Field (Locals (1), "typeName", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "inhcount", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_local", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "is_not_null", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "is_from_type", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "storage", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "raw_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "cooked_default", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "collOid", Builders.Number (0));
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "SplitColQualList", (1 => Values (4), 2 => Builders.Field_Reference (Locals
                       (1), "constraints"), 3 => Builders.Field_Reference (Locals (1), "collClause"), 4 =>
                       Builders.No_Value));
               begin
                  null;
               end;
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 477 =>
               Result := Values (2);
         when 478 =>
               Result := Invoke (Build_Access, "pstrdup", (1 => Builders.Text ("default")));
         when 479 =>
               Result := Values (1);
         when 480 =>
               Result := Builders.No_Value;
         when 481 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 482 =>
               Result := Builders.No_Value;
         when 483 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (3);
               Build_Access.Set_Field (Locals (1), "conname", Values (2));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 484 =>
               Result := Values (1);
         when 485 =>
               Result := Values (1);
         when 486 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CollateClause");
               Build_Access.Set_Field (Locals (1), "arg", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "collname", Values (2));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 487 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 488 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 489 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (7));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "keys", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "options", Values (2));
               Build_Access.Set_Field (Locals (1), "indexname", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexspace", Values (3));
               Result := Locals (1);
            end;
         when 490 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (6));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "keys", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "options", Values (3));
               Build_Access.Set_Field (Locals (1), "indexname", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "indexspace", Values (4));
               Result := Locals (1);
            end;
         when 491 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (5));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "is_no_inherit", Values (5));
               Build_Access.Set_Field (Locals (1), "raw_expr", Values (3));
               Build_Access.Set_Field (Locals (1), "cooked_expr", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "skip_validation", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "initially_valid", Builders.Number (1));
               Result := Locals (1);
            end;
         when 492 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "raw_expr", Values (2));
               Build_Access.Set_Field (Locals (1), "cooked_expr", Builders.No_Value);
               Result := Locals (1);
            end;
         when 493 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "generated_when", Values (2));
               Build_Access.Set_Field (Locals (1), "options", Values (5));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 494 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "generated_when", Values (2));
               Build_Access.Set_Field (Locals (1), "raw_expr", Values (5));
               Build_Access.Set_Field (Locals (1), "cooked_expr", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               if Semantics.Truth (Semantics.Binary ("!=", Values (2), Builders.Number (97))) then
                  raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                     ("for a generated column, GENERATED ALWAYS must be specified"));
               end if;
               Result := Locals (1);
            end;
         when 495 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (9));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Build_Access.Set_Field (Locals (1), "pktable", Values (2));
               Build_Access.Set_Field (Locals (1), "fk_attrs", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "pk_attrs", Values (3));
               Build_Access.Set_Field (Locals (1), "fk_matchtype", Values (4));
               Build_Access.Set_Field (Locals (1), "fk_upd_action", Semantics.Binary (">>", Values (5),
                  Builders.Number (8)));
               Build_Access.Set_Field (Locals (1), "fk_del_action", Semantics.Binary ("&", Values (5), Builders.Number
                  (255)));
               Build_Access.Set_Field (Locals (1), "skip_validation", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "initially_valid", Builders.Number (1));
               Result := Locals (1);
            end;
         when 496 =>
               Result := Builders.Number (97);
         when 497 =>
               Result := Builders.Number (100);
         when 498 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (10));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 499 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (11));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 500 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (12));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 501 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("Constraint");
               Build_Access.Set_Field (Locals (1), "contype", Builders.Number (13));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 502 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("TableLikeClause");
               Build_Access.Set_Field (Locals (1), "relation", Values (2));
               Build_Access.Set_Field (Locals (1), "options", Values (3));
               Build_Access.Set_Field (Locals (1), "relationOid", Builders.Number (0));
               Result := Locals (1);
            end;
         when 503 =>
               Result := Semantics.Binary ("|", Values (1), Values (3));
         when 504 =>
               Result := Semantics.Binary ("&", Values (1), Semantics.Unary ("~", Values (3)));
         when 505 =>
               Result := Builders.Number (0);
         when 506 =>
               Result := Builders.Number (1);
         when 507 =>
               Result := Builders.Number (1);
         when 508 =>
               Result := Builders.Number (1);
         when others => null;
      end case;
   end Reduce;

end Flyology.Postgres.SQL.Native.Actions_V14_Chunk_03;
