--  Generated by tools/generate_native_actions.py.  Do not edit.
with Interfaces;
with Flyology.Postgres.SQL.Native.Builders;
with Flyology.Postgres.SQL.Native.Semantics;
with Flyology.Postgres.SQL.Native.Actions_V16_Support;

package body Flyology.Postgres.SQL.Native.Actions_V16_Chunk_11 is

   pragma Style_Checks (Off);
   use type Interfaces.Integer_64;

   function Invoke
     (Build : not null access Builders.Builder; Name : String;
      Arguments : Builders.Semantic_Array) return Builders.Dynamic_Value
      renames Actions_V16_Support.Invoke;

   procedure Reduce
     (Build        : aliased in out Builders.Builder;
      Rule         : Positive;
      Values       : Builders.Semantic_Array;
      Locations    : Builders.Location_Array;
      Result       : in out Builders.Dynamic_Value;
      Location     : in out Integer;
      Parse_Result : in out Builders.Dynamic_Value)
   is
      Build_Access : constant not null access Builders.Builder :=
        Build'Unchecked_Access;
   begin
      case Rule is
         when 1576 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("PrepareStmt");
               Build_Access.Set_Field (Locals (1), "name", Values (2));
               Build_Access.Set_Field (Locals (1), "argtypes", Values (3));
               Build_Access.Set_Field (Locals (1), "query", Values (5));
               Result := Locals (1);
            end;
         when 1577 =>
               Result := Values (2);
         when 1578 =>
               Result := Builders.No_Value;
         when 1584 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ExecuteStmt");
               Build_Access.Set_Field (Locals (1), "name", Values (2));
               Build_Access.Set_Field (Locals (1), "params", Values (3));
               Result := Locals (1);
            end;
         when 1585 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableAsStmt");
               Locals (2) := Build_Access.New_Object ("ExecuteStmt");
               Build_Access.Set_Field (Locals (2), "name", Values (7));
               Build_Access.Set_Field (Locals (2), "params", Values (8));
               Build_Access.Set_Field (Locals (1), "query", Locals (2));
               Build_Access.Set_Field (Locals (1), "into", Values (4));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "is_select_into", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (0));
               Build_Access.Set_Field (Values (4), "rel.relpersistence", Values (2));
               Build_Access.Set_Field (Values (4), "skipData", Semantics.Unary ("!", Values (9)));
               Result := Locals (1);
            end;
         when 1586 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 2) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CreateTableAsStmt");
               Locals (2) := Build_Access.New_Object ("ExecuteStmt");
               Build_Access.Set_Field (Locals (2), "name", Values (10));
               Build_Access.Set_Field (Locals (2), "params", Values (11));
               Build_Access.Set_Field (Locals (1), "query", Locals (2));
               Build_Access.Set_Field (Locals (1), "into", Values (7));
               Build_Access.Set_Field (Locals (1), "objtype", Builders.Number (41));
               Build_Access.Set_Field (Locals (1), "is_select_into", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "if_not_exists", Builders.Number (1));
               Build_Access.Set_Field (Values (7), "rel.relpersistence", Values (2));
               Build_Access.Set_Field (Values (7), "skipData", Semantics.Unary ("!", Values (12)));
               Result := Locals (1);
            end;
         when 1587 =>
               Result := Values (2);
         when 1588 =>
               Result := Builders.No_Value;
         when 1589 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DeallocateStmt");
               Build_Access.Set_Field (Locals (1), "name", Values (2));
               Result := Locals (1);
            end;
         when 1590 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DeallocateStmt");
               Build_Access.Set_Field (Locals (1), "name", Values (3));
               Result := Locals (1);
            end;
         when 1591 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DeallocateStmt");
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1592 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DeallocateStmt");
               Build_Access.Set_Field (Locals (1), "name", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1593 =>
               Build_Access.Set_Field (Values (5), "relation", Values (4));
               Build_Access.Set_Field (Values (5), "onConflictClause", Values (6));
               Build_Access.Set_Field (Values (5), "returningList", Values (7));
               Build_Access.Set_Field (Values (5), "withClause", Values (1));
               Result := Values (5);
         when 1594 =>
               Result := Values (1);
         when 1595 =>
               Build_Access.Set_Field (Values (1), "alias", Invoke (Build_Access, "makeAlias", (1 => Values (3), 2 =>
                  Builders.No_Value)));
               Result := Values (1);
         when 1596 =>
               Result := Build_Access.New_Object ("InsertStmt");
               Build_Access.Set_Field (Result, "cols", Builders.No_Value);
               Build_Access.Set_Field (Result, "selectStmt", Values (1));
         when 1597 =>
               Result := Build_Access.New_Object ("InsertStmt");
               Build_Access.Set_Field (Result, "cols", Builders.No_Value);
               Build_Access.Set_Field (Result, "override", Values (2));
               Build_Access.Set_Field (Result, "selectStmt", Values (4));
         when 1598 =>
               Result := Build_Access.New_Object ("InsertStmt");
               Build_Access.Set_Field (Result, "cols", Values (2));
               Build_Access.Set_Field (Result, "selectStmt", Values (4));
         when 1599 =>
               Result := Build_Access.New_Object ("InsertStmt");
               Build_Access.Set_Field (Result, "cols", Values (2));
               Build_Access.Set_Field (Result, "override", Values (5));
               Build_Access.Set_Field (Result, "selectStmt", Values (7));
         when 1600 =>
               Result := Build_Access.New_Object ("InsertStmt");
               Build_Access.Set_Field (Result, "cols", Builders.No_Value);
               Build_Access.Set_Field (Result, "selectStmt", Builders.No_Value);
         when 1601 =>
               Result := Builders.Number (1);
         when 1602 =>
               Result := Builders.Number (2);
         when 1603 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1604 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1605 =>
               Result := Build_Access.New_Object ("ResTarget");
               Build_Access.Set_Field (Result, "name", Values (1));
               Build_Access.Set_Field (Result, "indirection", Invoke (Build_Access, "check_indirection", (1 => Values
                  (2), 2 => Builders.No_Value)));
               Build_Access.Set_Field (Result, "val", Builders.No_Value);
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1606 =>
               Result := Build_Access.New_Object ("OnConflictClause");
               Build_Access.Set_Field (Result, "action", Builders.Number (2));
               Build_Access.Set_Field (Result, "infer", Values (3));
               Build_Access.Set_Field (Result, "targetList", Values (7));
               Build_Access.Set_Field (Result, "whereClause", Values (8));
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1607 =>
               Result := Build_Access.New_Object ("OnConflictClause");
               Build_Access.Set_Field (Result, "action", Builders.Number (1));
               Build_Access.Set_Field (Result, "infer", Values (3));
               Build_Access.Set_Field (Result, "targetList", Builders.No_Value);
               Build_Access.Set_Field (Result, "whereClause", Builders.No_Value);
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1608 =>
               Result := Builders.No_Value;
         when 1609 =>
               Result := Build_Access.New_Object ("InferClause");
               Build_Access.Set_Field (Result, "indexElems", Values (2));
               Build_Access.Set_Field (Result, "whereClause", Values (4));
               Build_Access.Set_Field (Result, "conname", Builders.No_Value);
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1610 =>
               Result := Build_Access.New_Object ("InferClause");
               Build_Access.Set_Field (Result, "indexElems", Builders.No_Value);
               Build_Access.Set_Field (Result, "whereClause", Builders.No_Value);
               Build_Access.Set_Field (Result, "conname", Values (3));
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1611 =>
               Result := Builders.No_Value;
         when 1612 =>
               Result := Values (2);
         when 1613 =>
               Result := Builders.No_Value;
         when 1614 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DeleteStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (4));
               Build_Access.Set_Field (Locals (1), "usingClause", Values (5));
               Build_Access.Set_Field (Locals (1), "whereClause", Values (6));
               Build_Access.Set_Field (Locals (1), "returningList", Values (7));
               Build_Access.Set_Field (Locals (1), "withClause", Values (1));
               Result := Locals (1);
            end;
         when 1615 =>
               Result := Values (2);
         when 1616 =>
               Result := Builders.No_Value;
         when 1617 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("LockStmt");
               Build_Access.Set_Field (Locals (1), "relations", Values (3));
               Build_Access.Set_Field (Locals (1), "mode", Values (4));
               Build_Access.Set_Field (Locals (1), "nowait", Values (5));
               Result := Locals (1);
            end;
         when 1618 =>
               Result := Values (2);
         when 1619 =>
               Result := Builders.Number (8);
         when 1620 =>
               Result := Builders.Number (1);
         when 1621 =>
               Result := Builders.Number (2);
         when 1622 =>
               Result := Builders.Number (3);
         when 1623 =>
               Result := Builders.Number (4);
         when 1624 =>
               Result := Builders.Number (5);
         when 1625 =>
               Result := Builders.Number (6);
         when 1626 =>
               Result := Builders.Number (7);
         when 1627 =>
               Result := Builders.Number (8);
         when 1628 =>
               Result := Builders.Number (1);
         when 1629 =>
               Result := Builders.Number (0);
         when 1630 =>
               Result := Builders.Number (2);
         when 1631 =>
               Result := Builders.Number (1);
         when 1632 =>
               Result := Builders.Number (0);
         when 1633 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("UpdateStmt");
               Build_Access.Set_Field (Locals (1), "relation", Values (3));
               Build_Access.Set_Field (Locals (1), "targetList", Values (5));
               Build_Access.Set_Field (Locals (1), "fromClause", Values (6));
               Build_Access.Set_Field (Locals (1), "whereClause", Values (7));
               Build_Access.Set_Field (Locals (1), "returningList", Values (8));
               Build_Access.Set_Field (Locals (1), "withClause", Values (1));
               Result := Locals (1);
            end;
         when 1634 =>
               Result := Values (1);
         when 1635 =>
               Result := Invoke (Build_Access, "list_concat", (1 => Values (1), 2 => Values (3)));
         when 1636 =>
               Build_Access.Set_Field (Values (1), "val", Values (3));
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1637 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 6) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Invoke (Build_Access, "list_length", (1 => Values (2)));
               Locals (2) := Builders.Number (1);
               declare
                  Loop_List : constant Builders.Dynamic_Value := Values (2);
               begin
                  for Loop_Index in 1 .. Build_Access.Length (Loop_List) loop
                     Locals (3) := Build_Access.Cell (Loop_List, Loop_Index);
                     Locals (5) := Build_Access.Cell_Element (Locals (3));
                     Locals (6) := Build_Access.New_Object ("MultiAssignRef");
                     Build_Access.Set_Field (Locals (6), "source", Values (5));
                     Build_Access.Set_Field (Locals (6), "colno", Locals (2));
                     Build_Access.Set_Field (Locals (6), "ncolumns", Locals (1));
                     Build_Access.Set_Field (Locals (5), "val", Locals (6));
                     Locals (2) := Semantics.Binary ("+", Locals (2), Builders.Number (1));
                     <<Continue_Loop_2>>
                     null;
                  end loop;
               end;
               Result := Values (2);
            end;
         when 1638 =>
               Result := Build_Access.New_Object ("ResTarget");
               Build_Access.Set_Field (Result, "name", Values (1));
               Build_Access.Set_Field (Result, "indirection", Invoke (Build_Access, "check_indirection", (1 => Values
                  (2), 2 => Builders.No_Value)));
               Build_Access.Set_Field (Result, "val", Builders.No_Value);
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1639 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1640 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1641 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeStmt");
               Build_Access.Set_Field (Locals (1), "withClause", Values (1));
               Build_Access.Set_Field (Locals (1), "relation", Values (4));
               Build_Access.Set_Field (Locals (1), "sourceRelation", Values (6));
               Build_Access.Set_Field (Locals (1), "joinCondition", Values (8));
               Build_Access.Set_Field (Locals (1), "mergeWhenClauses", Values (9));
               Result := Locals (1);
            end;
         when 1642 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1643 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 1644 =>
               Build_Access.Set_Field (Values (5), "matched", Builders.Number (1));
               Build_Access.Set_Field (Values (5), "condition", Values (3));
               Result := Values (5);
         when 1645 =>
               Build_Access.Set_Field (Values (5), "matched", Builders.Number (1));
               Build_Access.Set_Field (Values (5), "condition", Values (3));
               Result := Values (5);
         when 1646 =>
               Build_Access.Set_Field (Values (6), "matched", Builders.Number (0));
               Build_Access.Set_Field (Values (6), "condition", Values (4));
               Result := Values (6);
         when 1647 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "matched", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (7));
               Build_Access.Set_Field (Locals (1), "condition", Values (3));
               Result := Locals (1);
            end;
         when 1648 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "matched", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (7));
               Build_Access.Set_Field (Locals (1), "condition", Values (4));
               Result := Locals (1);
            end;
         when 1649 =>
               Result := Values (2);
         when 1650 =>
               Result := Builders.No_Value;
         when 1651 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (2));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "targetList", Values (3));
               Build_Access.Set_Field (Locals (1), "values", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1652 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (4));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "targetList", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "values", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1653 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "targetList", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "values", Values (2));
               Result := Locals (1);
            end;
         when 1654 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "override", Values (3));
               Build_Access.Set_Field (Locals (1), "targetList", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "values", Values (5));
               Result := Locals (1);
            end;
         when 1655 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "targetList", Values (3));
               Build_Access.Set_Field (Locals (1), "values", Values (5));
               Result := Locals (1);
            end;
         when 1656 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "override", Values (6));
               Build_Access.Set_Field (Locals (1), "targetList", Values (3));
               Build_Access.Set_Field (Locals (1), "values", Values (8));
               Result := Locals (1);
            end;
         when 1657 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("MergeWhenClause");
               Build_Access.Set_Field (Locals (1), "commandType", Builders.Number (3));
               Build_Access.Set_Field (Locals (1), "override", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "targetList", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "values", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1658 =>
               Result := Values (3);
         when 1659 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("DeclareCursorStmt");
               Build_Access.Set_Field (Locals (1), "portalname", Values (2));
               Build_Access.Set_Field (Locals (1), "options", Semantics.Binary ("|", Semantics.Binary ("|", Values
                  (3), Values (5)), Builders.Number (256)));
               Build_Access.Set_Field (Locals (1), "query", Values (7));
               Result := Locals (1);
            end;
         when 1660 =>
               Result := Values (1);
         when 1661 =>
               Result := Builders.Number (0);
         when 1662 =>
               Result := Semantics.Binary ("|", Values (1), Builders.Number (4));
         when 1663 =>
               Result := Semantics.Binary ("|", Values (1), Builders.Number (2));
         when 1664 =>
               Result := Semantics.Binary ("|", Values (1), Builders.Number (1));
         when 1665 =>
               Result := Semantics.Binary ("|", Values (1), Builders.Number (16));
         when 1666 =>
               Result := Semantics.Binary ("|", Values (1), Builders.Number (8));
         when 1667 =>
               Result := Builders.Number (0);
         when 1668 =>
               Result := Builders.Number (32);
         when 1669 =>
               Result := Builders.Number (0);
         when 1672 =>
               Result := Values (2);
         when 1673 =>
               Result := Values (2);
         when 1674 =>
               Result := Values (1);
         when 1675 =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "insertSelectOptions", (1 => Values (1), 2 => Values (2), 3 =>
                       Builders.No_Value, 4 => Builders.No_Value, 5 => Builders.No_Value, 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (1);
         when 1676 =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "insertSelectOptions", (1 => Values (1), 2 => Values (2), 3 => Values (3), 4
                       => Values (4), 5 => Builders.No_Value, 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (1);
         when 1677 =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "insertSelectOptions", (1 => Values (1), 2 => Values (2), 3 => Values (4), 4
                       => Values (3), 5 => Builders.No_Value, 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (1);
         when 1678 =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "insertSelectOptions", (1 => Values (2), 2 => Builders.No_Value, 3 =>
                       Builders.No_Value, 4 => Builders.No_Value, 5 => Values (1), 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (2);
         when 1679 =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "insertSelectOptions", (1 => Values (2), 2 => Values (3), 3 =>
                       Builders.No_Value, 4 => Builders.No_Value, 5 => Values (1), 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (2);
         when 1680 =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "insertSelectOptions", (1 => Values (2), 2 => Values (3), 3 => Values (4), 4
                       => Values (5), 5 => Values (1), 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (2);
         when 1681 =>
               declare
                  Ignored : constant Builders.Dynamic_Value :=
                    Invoke (Build_Access, "insertSelectOptions", (1 => Values (2), 2 => Values (3), 3 => Values (5), 4
                       => Values (4), 5 => Values (1), 6 => Builders.No_Value));
               begin
                  null;
               end;
               Result := Values (2);
         when 1682 =>
               Result := Values (1);
         when 1683 =>
               Result := Values (1);
         when 1684 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SelectStmt");
               Build_Access.Set_Field (Locals (1), "targetList", Values (3));
               Build_Access.Set_Field (Locals (1), "intoClause", Values (4));
               Build_Access.Set_Field (Locals (1), "fromClause", Values (5));
               Build_Access.Set_Field (Locals (1), "whereClause", Values (6));
               Build_Access.Set_Field (Locals (1), "groupClause", Build_Access.Field (Values (7), "list"));
               Build_Access.Set_Field (Locals (1), "groupDistinct", Build_Access.Field (Values (7), "distinct"));
               Build_Access.Set_Field (Locals (1), "havingClause", Values (8));
               Build_Access.Set_Field (Locals (1), "windowClause", Values (9));
               Result := Locals (1);
            end;
         when 1685 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SelectStmt");
               Build_Access.Set_Field (Locals (1), "distinctClause", Values (2));
               Build_Access.Set_Field (Locals (1), "targetList", Values (3));
               Build_Access.Set_Field (Locals (1), "intoClause", Values (4));
               Build_Access.Set_Field (Locals (1), "fromClause", Values (5));
               Build_Access.Set_Field (Locals (1), "whereClause", Values (6));
               Build_Access.Set_Field (Locals (1), "groupClause", Build_Access.Field (Values (7), "list"));
               Build_Access.Set_Field (Locals (1), "groupDistinct", Build_Access.Field (Values (7), "distinct"));
               Build_Access.Set_Field (Locals (1), "havingClause", Values (8));
               Build_Access.Set_Field (Locals (1), "windowClause", Values (9));
               Result := Locals (1);
            end;
         when 1686 =>
               Result := Values (1);
         when 1687 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 3) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("ColumnRef");
               Locals (2) := Build_Access.New_Object ("ResTarget");
               Locals (3) := Build_Access.New_Object ("SelectStmt");
               Build_Access.Set_Field (Locals (1), "fields", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Build_Access.New_Object ("A_Star"))));
               Build_Access.Set_Field (Locals (1), "location", Semantics.Unary ("-", Builders.Number (1)));
               Build_Access.Set_Field (Locals (2), "name", Builders.No_Value);
               Build_Access.Set_Field (Locals (2), "indirection", Builders.No_Value);
               Build_Access.Set_Field (Locals (2), "val", Locals (1));
               Build_Access.Set_Field (Locals (2), "location", Semantics.Unary ("-", Builders.Number (1)));
               Build_Access.Set_Field (Locals (3), "targetList", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Locals (2))));
               Build_Access.Set_Field (Locals (3), "fromClause", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Values (2))));
               Result := Locals (3);
            end;
         when 1688 =>
               Result := Invoke (Build_Access, "makeSetOp", (1 => Builders.Number (1), 2 => Semantics.Binary ("==",
                  Values (3), Builders.Number (1)), 3 => Values (1), 4 => Values (4)));
         when 1689 =>
               Result := Invoke (Build_Access, "makeSetOp", (1 => Builders.Number (2), 2 => Semantics.Binary ("==",
                  Values (3), Builders.Number (1)), 3 => Values (1), 4 => Values (4)));
         when 1690 =>
               Result := Invoke (Build_Access, "makeSetOp", (1 => Builders.Number (3), 2 => Semantics.Binary ("==",
                  Values (3), Builders.Number (1)), 3 => Values (1), 4 => Values (4)));
         when 1691 =>
               Result := Build_Access.New_Object ("WithClause");
               Build_Access.Set_Field (Result, "ctes", Values (2));
               Build_Access.Set_Field (Result, "recursive", Builders.Number (0));
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1692 =>
               Result := Build_Access.New_Object ("WithClause");
               Build_Access.Set_Field (Result, "ctes", Values (2));
               Build_Access.Set_Field (Result, "recursive", Builders.Number (0));
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1693 =>
               Result := Build_Access.New_Object ("WithClause");
               Build_Access.Set_Field (Result, "ctes", Values (3));
               Build_Access.Set_Field (Result, "recursive", Builders.Number (1));
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (1))));
         when 1694 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1695 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1696 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CommonTableExpr");
               Build_Access.Set_Field (Locals (1), "ctename", Values (1));
               Build_Access.Set_Field (Locals (1), "aliascolnames", Values (2));
               Build_Access.Set_Field (Locals (1), "ctematerialized", Values (4));
               Build_Access.Set_Field (Locals (1), "ctequery", Values (6));
               Build_Access.Set_Field (Locals (1), "search_clause", Values (8));
               Build_Access.Set_Field (Locals (1), "cycle_clause", Values (9));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 1697 =>
               Result := Builders.Number (1);
         when 1698 =>
               Result := Builders.Number (2);
         when 1699 =>
               Result := Builders.Number (0);
         when 1700 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CTESearchClause");
               Build_Access.Set_Field (Locals (1), "search_col_list", Values (5));
               Build_Access.Set_Field (Locals (1), "search_breadth_first", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "search_seq_column", Values (7));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 1701 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CTESearchClause");
               Build_Access.Set_Field (Locals (1), "search_col_list", Values (5));
               Build_Access.Set_Field (Locals (1), "search_breadth_first", Builders.Number (1));
               Build_Access.Set_Field (Locals (1), "search_seq_column", Values (7));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 1702 =>
               Result := Builders.No_Value;
         when 1703 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CTECycleClause");
               Build_Access.Set_Field (Locals (1), "cycle_col_list", Values (2));
               Build_Access.Set_Field (Locals (1), "cycle_mark_column", Values (4));
               Build_Access.Set_Field (Locals (1), "cycle_mark_value", Values (6));
               Build_Access.Set_Field (Locals (1), "cycle_mark_default", Values (8));
               Build_Access.Set_Field (Locals (1), "cycle_path_column", Values (10));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 1704 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("CTECycleClause");
               Build_Access.Set_Field (Locals (1), "cycle_col_list", Values (2));
               Build_Access.Set_Field (Locals (1), "cycle_mark_column", Values (4));
               Build_Access.Set_Field (Locals (1), "cycle_mark_value", Invoke (Build_Access, "makeBoolAConst", (1 =>
                  Builders.Number (1), 2 => Semantics.Unary ("-", Builders.Number (1)))));
               Build_Access.Set_Field (Locals (1), "cycle_mark_default", Invoke (Build_Access, "makeBoolAConst", (1 =>
                  Builders.Number (0), 2 => Semantics.Unary ("-", Builders.Number (1)))));
               Build_Access.Set_Field (Locals (1), "cycle_path_column", Values (6));
               Build_Access.Set_Field (Locals (1), "location", Builders.Number (Interfaces.Integer_64 (Locations
                  (1))));
               Result := Locals (1);
            end;
         when 1705 =>
               Result := Builders.No_Value;
         when 1706 =>
               Result := Values (1);
         when 1707 =>
               Result := Builders.No_Value;
         when 1708 =>
               Result := Build_Access.New_Object ("IntoClause");
               Build_Access.Set_Field (Result, "rel", Values (2));
               Build_Access.Set_Field (Result, "colNames", Builders.No_Value);
               Build_Access.Set_Field (Result, "options", Builders.No_Value);
               Build_Access.Set_Field (Result, "onCommit", Builders.Number (0));
               Build_Access.Set_Field (Result, "tableSpaceName", Builders.No_Value);
               Build_Access.Set_Field (Result, "viewQuery", Builders.No_Value);
               Build_Access.Set_Field (Result, "skipData", Builders.Number (0));
         when 1709 =>
               Result := Builders.No_Value;
         when 1710 =>
               Result := Values (3);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (116));
         when 1711 =>
               Result := Values (3);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (116));
         when 1712 =>
               Result := Values (4);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (116));
         when 1713 =>
               Result := Values (4);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (116));
         when 1714 =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("GLOBAL is deprecated in temporary table creation"));
               Result := Values (4);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (116));
         when 1715 =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("GLOBAL is deprecated in temporary table creation"));
               Result := Values (4);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (116));
         when 1716 =>
               Result := Values (3);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (117));
         when 1717 =>
               Result := Values (2);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (112));
         when 1718 =>
               Result := Values (1);
               Build_Access.Set_Field (Result, "relpersistence", Builders.Number (112));
         when 1721 =>
               Result := Builders.Number (1);
         when 1722 =>
               Result := Builders.Number (2);
         when 1723 =>
               Result := Builders.Number (0);
         when 1724 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Builders.No_Value));
         when 1725 =>
               Result := Values (4);
         when 1728 =>
               Result := Values (1);
         when 1729 =>
               Result := Builders.No_Value;
         when 1730 =>
               Result := Values (1);
         when 1731 =>
               Result := Builders.No_Value;
         when 1732 =>
               Result := Values (3);
         when 1733 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1734 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1735 =>
               Result := Build_Access.New_Object ("SortBy");
               Build_Access.Set_Field (Result, "node", Values (1));
               Build_Access.Set_Field (Result, "sortby_dir", Builders.Number (3));
               Build_Access.Set_Field (Result, "sortby_nulls", Values (4));
               Build_Access.Set_Field (Result, "useOp", Values (3));
               Build_Access.Set_Field (Result, "location", Builders.Number (Interfaces.Integer_64 (Locations (3))));
         when 1736 =>
               Result := Build_Access.New_Object ("SortBy");
               Build_Access.Set_Field (Result, "node", Values (1));
               Build_Access.Set_Field (Result, "sortby_dir", Values (2));
               Build_Access.Set_Field (Result, "sortby_nulls", Values (3));
               Build_Access.Set_Field (Result, "useOp", Builders.No_Value);
               Build_Access.Set_Field (Result, "location", Semantics.Unary ("-", Builders.Number (1)));
         when 1737 =>
               Result := Values (1);
               Build_Access.Set_Field (Result, "limitOffset", Values (2));
         when 1738 =>
               Result := Values (2);
               Build_Access.Set_Field (Result, "limitOffset", Values (1));
         when 1739 =>
               Result := Values (1);
         when 1740 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Values (1));
               Build_Access.Set_Field (Locals (1), "limitCount", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1741 =>
               Result := Values (1);
         when 1742 =>
               Result := Builders.No_Value;
         when 1743 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitCount", Values (2));
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1744 =>
               raise Semantics.Parser_Error with Semantics.Text_Of (Builders.Text
                  ("LIMIT #,# syntax is not supported"));
         when 1745 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitCount", Values (3));
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1746 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitCount", Values (3));
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (2));
               Result := Locals (1);
            end;
         when 1747 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitCount", Invoke (Build_Access, "makeIntConst", (1 =>
                  Builders.Number (1), 2 => Semantics.Unary ("-", Builders.Number (1)))));
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (1));
               Result := Locals (1);
            end;
         when 1748 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__SelectLimit");
               Build_Access.Set_Field (Locals (1), "limitOffset", Builders.No_Value);
               Build_Access.Set_Field (Locals (1), "limitCount", Invoke (Build_Access, "makeIntConst", (1 =>
                  Builders.Number (1), 2 => Semantics.Unary ("-", Builders.Number (1)))));
               Build_Access.Set_Field (Locals (1), "limitOption", Builders.Number (2));
               Result := Locals (1);
            end;
         when 1749 =>
               Result := Values (2);
         when 1750 =>
               Result := Values (2);
         when 1751 =>
               Result := Values (1);
         when 1752 =>
               Result := Invoke (Build_Access, "makeNullAConst", (1 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 1753 =>
               Result := Values (1);
         when 1754 =>
               Result := Values (1);
         when 1755 =>
               Result := Invoke (Build_Access, "makeSimpleA_Expr", (1 => Builders.Number (0), 2 => Builders.Text
                  ("+"), 3 => Builders.No_Value, 4 => Values (2), 5 => Builders.Number (Interfaces.Integer_64
                  (Locations (1)))));
         when 1756 =>
               Result := Invoke (Build_Access, "doNegate", (1 => Values (2), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 1757 =>
               Result := Invoke (Build_Access, "makeIntConst", (1 => Values (1), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 1758 =>
               Result := Invoke (Build_Access, "makeFloatConst", (1 => Values (1), 2 => Builders.Number
                  (Interfaces.Integer_64 (Locations (1)))));
         when 1759 =>
               Result := Builders.Number (0);
         when 1760 =>
               Result := Builders.Number (0);
         when 1761 =>
               Result := Builders.Number (0);
         when 1762 =>
               Result := Builders.Number (0);
         when 1763 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__GroupClause");
               Build_Access.Set_Field (Locals (1), "distinct", Semantics.Binary ("==", Values (3), Builders.Number
                  (2)));
               Build_Access.Set_Field (Locals (1), "list", Values (4));
               Result := Locals (1);
            end;
         when 1764 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("__GroupClause");
               Build_Access.Set_Field (Locals (1), "distinct", Builders.Number (0));
               Build_Access.Set_Field (Locals (1), "list", Builders.No_Value);
               Result := Locals (1);
            end;
         when 1765 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1766 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when 1767 =>
               Result := Values (1);
         when 1768 =>
               Result := Values (1);
         when 1769 =>
               Result := Values (1);
         when 1770 =>
               Result := Values (1);
         when 1771 =>
               Result := Values (1);
         when 1772 =>
               Result := Invoke (Build_Access, "makeGroupingSet", (1 => Builders.Number (0), 2 => Builders.No_Value, 3
                  => Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 1773 =>
               Result := Invoke (Build_Access, "makeGroupingSet", (1 => Builders.Number (2), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 1774 =>
               Result := Invoke (Build_Access, "makeGroupingSet", (1 => Builders.Number (3), 2 => Values (3), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 1775 =>
               Result := Invoke (Build_Access, "makeGroupingSet", (1 => Builders.Number (4), 2 => Values (4), 3 =>
                  Builders.Number (Interfaces.Integer_64 (Locations (1)))));
         when 1776 =>
               Result := Values (2);
         when 1777 =>
               Result := Builders.No_Value;
         when 1778 =>
               Result := Values (1);
         when 1779 =>
               Result := Builders.No_Value;
         when 1780 =>
               Result := Values (1);
         when 1781 =>
               Result := Builders.No_Value;
         when 1782 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1783 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (2)));
         when 1784 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("LockingClause");
               Build_Access.Set_Field (Locals (1), "lockedRels", Values (2));
               Build_Access.Set_Field (Locals (1), "strength", Values (1));
               Build_Access.Set_Field (Locals (1), "waitPolicy", Values (3));
               Result := Locals (1);
            end;
         when 1785 =>
               Result := Builders.Number (4);
         when 1786 =>
               Result := Builders.Number (3);
         when 1787 =>
               Result := Builders.Number (2);
         when 1788 =>
               Result := Builders.Number (1);
         when 1789 =>
               Result := Values (2);
         when 1790 =>
               Result := Builders.No_Value;
         when 1791 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Build_Access.New_Object ("SelectStmt");
               Build_Access.Set_Field (Locals (1), "valuesLists", Invoke (Build_Access, "list_make1_impl", (1 =>
                  Builders.Number (1), 2 => Values (3))));
               Result := Locals (1);
            end;
         when 1792 =>
            declare
               Locals : Builders.Semantic_Array (1 .. 1) :=
                 (others => Builders.No_Value);
            begin
               Locals (1) := Values (1);
               Build_Access.Set_Field (Locals (1), "valuesLists", Invoke (Build_Access, "lappend", (1 =>
                  Build_Access.Field (Locals (1), "valuesLists"), 2 => Values (4))));
               Result := Locals (1);
            end;
         when 1793 =>
               Result := Values (2);
         when 1794 =>
               Result := Builders.No_Value;
         when 1795 =>
               Result := Invoke (Build_Access, "list_make1_impl", (1 => Builders.Number (1), 2 => Values (1)));
         when 1796 =>
               Result := Invoke (Build_Access, "lappend", (1 => Values (1), 2 => Values (3)));
         when others => null;
      end case;
   end Reduce;

end Flyology.Postgres.SQL.Native.Actions_V16_Chunk_11;
