name = "flyology_postgres"
description = "Postgres client and protocol server for Flyology tasks"
version = "0.1.1-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-postgres"
tags = ["ada", "postgres", "database", "client", "server", "protocol"]

[[depends-on]]
flyology = "~0.1.1-dev"
system_random = "^1.0.0"
hmac_ada = "^0.2.0"

[[pins]]
flyology = { url='https://github.com/flyology-ada/flyology.git', commit='195b2289cb436a404ea67a7784799be6daa55d6a' }
