name = "flyology_postgres_proof"
description = "Proof environment for the Flyology Postgres wire and SCRAM cores"
version = "0.1.1-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"

[[depends-on]]
flyology_postgres = "*"
gnatprove = "^16.1.0"

[[pins]]
flyology_postgres = { path = ".." }
