#!/usr/bin/env python3
"""Generate the native semantic-builder to owned-AST parser path."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from generate_ada import SCALARS, Enum, Field, Message, accessor_name, enum_literal, parse_proto, reachable_schema, sequence_name
from generate_native_actions import clang_ast, enum_values as clang_enum_values
from generate_owned_ast import (
    access_name,
    convert_access_name,
    message_name,
    owned_type,
    release_contents_name,
    schema_parts,
)


MAXIMUM_DEPTH = 256


def native_record(name: str) -> str:
    return "Convert_Native_" + message_name(name)


def native_access(name: str) -> str:
    return native_record(name) + "_Access"


def native_sequence(name: str) -> str:
    return "Convert_Native_" + name


def native_enum(name: str) -> str:
    return "Convert_Native_" + message_name(name)


def native_enum_is_default(name: str) -> str:
    return "Native_" + message_name(name) + "_Is_Default"


def source_expression(message: Message, field: Field) -> str:
    if message.name == "List":
        return "Item"
    expression = f'Build.Field (Item, "{field.json_name}")'
    if field.name == "str" and message.name in {"String", "Float", "BitString"}:
        fallback = {"String": "sval", "Float": "fval", "BitString": "bsval"}[message.name]
        return (
            f'(declare Value : constant Builders.Dynamic_Value := {expression}; '
            f' begin (if Value.Kind = Builders.Null_Value then '
            f'Build.Field (Item, "{fallback}") else Value))'
        )
    return expression


def scalar_conversion(field: Field, expression: str) -> str:
    kind = field.type_name
    if kind == "bool":
        return f"Native_Boolean ({expression})"
    if kind in {"string", "bytes"}:
        return f"Native_Text ({expression})"
    if kind in {"int32", "sint32", "sfixed32", "int64", "sint64", "sfixed64"}:
        if SCALARS[kind] == "Interfaces.Integer_64":
            return f"Native_Integer ({expression})"
        return f"{SCALARS[kind]} (Native_Integer ({expression}))"
    if kind in {"uint32", "fixed32", "uint64", "fixed64"}:
        if SCALARS[kind] == "Interfaces.Unsigned_64":
            return f"Native_Unsigned ({expression})"
        return f"{SCALARS[kind]} (Native_Unsigned ({expression}))"
    if kind in {"float", "double"}:
        if SCALARS[kind] == "Interfaces.IEEE_Float_64":
            return f"Native_Float ({expression})"
        return f"{SCALARS[kind]} (Native_Float ({expression}))"
    raise AssertionError(kind)


def value_conversion(
    field: Field,
    expression: str,
    messages: dict[str, Message],
    enums: dict[str, Enum],
) -> str:
    if field.type_name in SCALARS:
        return scalar_conversion(field, expression)
    if field.type_name == "Node":
        return f"Convert_Native_Node (Build, {expression}, Depth + 1)"
    if field.type_name in messages:
        return f"{native_access(field.type_name)} (Build, {expression}, Depth + 1)"
    if field.type_name in enums:
        return f"{native_enum(field.type_name)} ({expression})"
    raise AssertionError(field.type_name)


def present_expression(field: Field, expression: str, enums: dict[str, Enum]) -> str:
    if field.type_name == "bool":
        return f"Native_Boolean ({expression})"
    if field.type_name in {"string", "bytes"}:
        return f"Native_Text_Is_Present ({expression})"
    if field.type_name in {
        "int32", "sint32", "sfixed32", "int64", "sint64", "sfixed64",
        "uint32", "fixed32", "uint64", "fixed64",
    }:
        converter = "Native_Integer" if field.type_name[0] not in {"u", "f"} else "Native_Unsigned"
        return f"{converter} ({expression}) /= 0"
    if field.type_name in {"float", "double"}:
        return "True"
    if field.type_name in enums:
        return f"not {native_enum_is_default(field.type_name)} ({expression})"
    return "True"


def generate(
    major: int,
    version_number: int,
    messages: list[Message],
    enums: list[Enum],
    source_enums: dict[str, int],
) -> str:
    message_map, enum_map, concrete, repeated, _ = schema_parts(messages, enums)
    node = message_map["Node"]
    node_targets = {field.type_name for field in node.fields}
    access_targets = {
        field.type_name
        for message in messages
        if message.name != "Node"
        for field in message.fields
        if field.type_name in message_map and field.type_name != "Node"
        and not (message.name == "A_Const" and not field.repeated)
    }
    access_targets.add("RawStmt")
    used_sequences = {
        sequence_name(field, message_map, enum_map)
        for message in concrete
        for field in message.fields
        if field.repeated
    }
    lines = [
        "--  Generated by tools/generate_owned_parser.py.  Do not edit.",
        "pragma Style_Checks (Off);",
        "with Ada.Strings.Unbounded;",
        "with Interfaces;",
        "with Flyology.Postgres.SQL.Native.Builders;",
        f"with Flyology.Postgres.SQL.Native.Version_V{major};",
        "",
        f"separate (Flyology.Postgres.SQL.AST.V{major})",
        "procedure Parse",
        "  (SQL     : String;",
        "   Result  : in out Owned_Syntax_Tree;",
        "   Options : Parse_Options := Default_Options)",
        "is",
        "   package Builders renames Flyology.Postgres.SQL.Native.Builders;",
        f"   package Parser renames Flyology.Postgres.SQL.Native.Version_V{major};",
        "   use type Builders.Value_Kind;",
        "   use type Interfaces.Integer_64;",
        "",
        "   function Native_Integer",
        "     (Item : Builders.Dynamic_Value) return Interfaces.Integer_64 is",
        "   begin",
        "      if Item.Kind /= Builders.Integer_Value then",
        "         raise Constraint_Error with \"native integer required\";",
        "      end if;",
        "      return Item.Integer_Data;",
        "   end Native_Integer;",
        "",
        "   function Native_Unsigned",
        "     (Item : Builders.Dynamic_Value) return Interfaces.Unsigned_64 is",
        "      Value : constant Interfaces.Integer_64 := Native_Integer (Item);",
        "   begin",
        "      if Value < 0 then",
        "         raise Constraint_Error with \"native unsigned integer required\";",
        "      end if;",
        "      return Interfaces.Unsigned_64 (Value);",
        "   end Native_Unsigned;",
        "",
        "   function Native_Boolean",
        "     (Item : Builders.Dynamic_Value) return Boolean is",
        "     (case Item.Kind is",
        "         when Builders.Boolean_Value => Item.Boolean_Data,",
        "         when Builders.Integer_Value => Item.Integer_Data /= 0,",
        "         when others => raise Constraint_Error with \"native boolean required\");",
        "",
        "   function Native_Float",
        "     (Item : Builders.Dynamic_Value) return Interfaces.IEEE_Float_64 is",
        "      pragma Unreferenced (Item);",
        "   begin",
        "      raise Constraint_Error with \"unexpected native floating scalar\";",
        "      return 0.0;",
        "   end Native_Float;",
        "",
        "   function Native_Text (Item : Builders.Dynamic_Value) return Text is",
        "   begin",
        "      if Item.Kind = Builders.Text_Value then",
        "         return Item.Text_Data;",
        "      elsif Item.Kind = Builders.Integer_Value",
        "        and then Item.Integer_Data in 0 .. 255",
        "      then",
        "         return Ada.Strings.Unbounded.To_Unbounded_String",
        "           ((1 => Character'Val (Item.Integer_Data)));",
        "      end if;",
        "      raise Constraint_Error with \"native text required\";",
        "   end Native_Text;",
        "",
        "   function Native_Text_Is_Present",
        "     (Item : Builders.Dynamic_Value) return Boolean is",
        "     (case Item.Kind is",
        "         when Builders.Text_Value =>",
        "            Ada.Strings.Unbounded.Length (Item.Text_Data) /= 0,",
        "         when Builders.Integer_Value => Item.Integer_Data /= 0,",
        "         when others => False);",
        "",
    ]

    for enum in enums:
        target = message_name(enum.name)
        mapped = [
            (source_enums[name], number, enum_literal(enum, name))
            for name, number in enum.values if name in source_enums
        ]
        lines.extend([
            f"   function {native_enum(enum.name)}",
            f"     (Item : Builders.Dynamic_Value) return {target} is",
            "      Value : constant Interfaces.Integer_64 := Native_Integer (Item);",
            "   begin",
            "      case Value is",
        ])
        by_number: dict[int, str] = {}
        for source_number, _, literal in mapped:
            by_number.setdefault(source_number, literal)
        for number, literal in by_number.items():
            lines.append(f"         when {number} => return {literal};")
        lines.extend([
            "         when others =>",
            "            raise Constraint_Error with \"unknown native enum value\";",
            "      end case;",
            f"   end {native_enum(enum.name)};",
            "",
            f"   function {native_enum_is_default(enum.name)}",
            "     (Item : Builders.Dynamic_Value) return Boolean is",
            "      Value : constant Interfaces.Integer_64 := Native_Integer (Item);",
            "   begin",
            "      case Value is",
        ])
        default_sources = {
            source_number
            for source_number, wire_number, _ in mapped
            if wire_number == 0
        }
        for source_number in sorted(default_sources):
            lines.append(f"         when {source_number} => return True;")
        lines.extend([
            "         when others => return False;",
            "      end case;",
            f"   end {native_enum_is_default(enum.name)};",
            "",
        ])

    lines.extend([
        "   function Convert_Native_Node",
        "     (Build : Builders.Builder; Item : Builders.Dynamic_Value;",
        "      Depth : Natural) return Node_Access;",
    ])
    for message in concrete:
        target = message_name(message.name)
        lines.extend([
            f"   function {native_record(message.name)}",
            "     (Build : Builders.Builder; Item : Builders.Dynamic_Value;",
            f"      Depth : Natural) return {target};",
        ])
        if message.name in access_targets:
            lines.extend([
                f"   function {native_access(message.name)}",
                "     (Build : Builders.Builder; Item : Builders.Dynamic_Value;",
                f"      Depth : Natural) return {target}_Access;",
            ])
    lines.append("")

    for name, field in repeated.items():
        if name not in used_sequences:
            continue
        lines.extend([
            f"   function {native_sequence(name)}",
            "     (Build : Builders.Builder; Items : Builders.Dynamic_Value;",
            f"      Depth : Natural) return {name}",
            "   is",
            f"      Value : {name};",
            "   begin",
            f"      if Depth > {MAXIMUM_DEPTH} then",
            "         raise Constraint_Error with \"excessive native AST recursion\";",
            "      end if;",
            "      if Items.Kind = Builders.Null_Value then",
            "         return Value;",
            "      elsif Items.Kind /= Builders.List_Value then",
            "         raise Constraint_Error with \"native list required\";",
            "      end if;",
            "      for Index in 1 .. Build.Length (Items) loop",
        ])
        element = "Build.Element (Items, Index)"
        converted = value_conversion(field, element, message_map, enum_map)
        if field.type_name in message_map:
            element_type = owned_type(field, message_map, enum_map)
            lines.extend([
                "         declare",
                f"            Child : {element_type} := {converted};",
                "         begin",
                "            Value.Append (Child);",
                "         exception",
                "            when others =>",
                "               Release (Child);",
                "               raise;",
                "         end;",
            ])
        else:
            lines.append(f"         Value.Append ({converted});")
        lines.extend(["      end loop;", "      return Value;"])
        if field.type_name in message_map:
            element_type = owned_type(field, message_map, enum_map)
            lines.extend([
                "   exception",
                "      when others =>",
                "         for Child of Value loop",
                "            declare",
                f"               Copy : {element_type} := Child;",
                "            begin",
                "               Release (Copy);",
                "            end;",
                "         end loop;",
                "         Value.Clear;",
                "         raise;",
            ])
        lines.extend([f"   end {native_sequence(name)};", ""])

    # Inline scalar messages are needed by A_Const's C union representation.
    inline_targets = {
        field.type_name
        for message in messages if message.name == "A_Const"
        for field in message.fields
        if field.type_name in message_map and field.type_name != "Node"
    }
    for name in sorted(inline_targets):
        target_message = message_map[name]
        if not target_message.fields:
            continue
        inner = target_message.fields[0]
        target = message_name(name)
        converted = value_conversion(inner, "Scalar", message_map, enum_map)
        present = present_expression(inner, "Scalar", enum_map)
        component = accessor_name(inner)
        lines.extend([
            f"   function Convert_Native_Inline_{target}",
            f"     (Scalar : Builders.Dynamic_Value) return {target}_Access",
            "   is",
            f"      Value : {target};",
            "   begin",
            f"      if Scalar.Kind /= Builders.Null_Value and then ({present}) then",
            f"         Value.{component} := (Present => True, Value => {converted});",
            "      end if;",
            f"      return new {target}'(Value);",
            f"   end Convert_Native_Inline_{target};",
            "",
        ])

    # PostgreSQL 14 represents A_Const's scalar union as a Node.
    if any(field.type_name == "Node" for field in message_map["A_Const"].fields):
        lines.extend([
            "   function Convert_Native_Inline_Node",
            "     (Build : Builders.Builder; Item : Builders.Dynamic_Value)",
            "      return Node_Access",
            "   is",
            "      Tag : constant Builders.Dynamic_Value := Build.Field (Item, \"val.type\");",
            "   begin",
            "      if Tag.Kind /= Builders.Integer_Value then",
            "         raise Constraint_Error with \"A_Const node tag is absent\";",
            "      end if;",
            "      case Tag.Integer_Data is",
        ])
        for field in node.fields:
            target_message = message_map[field.type_name]
            tag = source_enums.get("T_" + field.type_name)
            if tag is None:
                continue
            target = message_name(field.type_name)
            if not target_message.fields:
                lines.extend([
                    f"         when {tag} =>",
                    f"            return new Node'(Kind => Node_{target},",
                    f"                             {target}_Payload => (null record));",
                ])
                continue
            inner = target_message.fields[0]
            if inner.repeated or (
                inner.type_name not in SCALARS and inner.type_name not in enum_map
            ):
                continue
            scalar_path = "val.val." + inner.json_name
            converted = value_conversion(inner, f'Build.Field (Item, "{scalar_path}")', message_map, enum_map)
            present = present_expression(inner, f'Build.Field (Item, "{scalar_path}")', enum_map)
            component = accessor_name(inner)
            lines.extend([
                f"         when {tag} =>",
                "            declare",
                f"               Value : {target};",
                f"               Scalar : constant Builders.Dynamic_Value := Build.Field (Item, \"{scalar_path}\");",
                "            begin",
                f"               if Scalar.Kind /= Builders.Null_Value and then ({present}) then",
                f"                  Value.{component} := (Present => True, Value => {converted});",
                "               end if;",
                "               return new Node'",
                f"                 (Kind => Node_{target}, {target}_Payload => Value);",
                "            end;",
            ])
        lines.extend([
            "         when others =>",
            "            raise Constraint_Error with \"unknown A_Const node tag\";",
            "      end case;",
            "   end Convert_Native_Inline_Node;",
            "",
        ])

    for message in concrete:
        target = message_name(message.name)
        lines.extend([
            f"   function {native_record(message.name)}",
            "     (Build : Builders.Builder; Item : Builders.Dynamic_Value;",
            f"      Depth : Natural) return {target}",
            "   is",
            f"      Value : {target};",
            "   begin",
            f"      if Depth > {MAXIMUM_DEPTH} then",
            "         raise Constraint_Error with \"excessive native AST recursion\";",
            "      end if;",
        ])
        if message.name != "List":
            lines.extend([
                "      if Item.Kind /= Builders.Object_Value",
                f"        or else Build.Object_Type (Item) /= \"{message.name}\"",
                "      then",
                f"         raise Constraint_Error with \"native {message.name} object required\";",
                "      end if;",
            ])
        for field in message.fields:
            component = accessor_name(field)
            source = source_expression(message, field)
            if message.name == "A_Const" and not field.repeated and field.type_name in message_map:
                if field.type_name == "Node":
                    lines.extend([
                        f"      if Build.Field (Item, \"val.type\").Kind /= Builders.Null_Value then",
                        f"         Value.{component} :=",
                        "           (Present => True,",
                        "            Value => Convert_Native_Inline_Node (Build, Item));",
                        "      end if;",
                    ])
                else:
                    target_message = message_map[field.type_name]
                    if target_message.fields:
                        inner = target_message.fields[0]
                        prefix = "val." + field.json_name + "."
                        lines.extend([
                            f"      if Build.Field (Item, \"{prefix}type\").Kind /= Builders.Null_Value then",
                            f"         Value.{component} :=",
                            "           (Present => True,",
                            f"            Value => Convert_Native_Inline_{message_name(field.type_name)}",
                            f"              (Build.Field (Item, \"{prefix}{inner.json_name}\")));",
                            "      end if;",
                        ])
                continue
            if field.repeated:
                lines.append(
                    f"      Value.{component} := {native_sequence(sequence_name(field, message_map, enum_map))}"
                    f" (Build, {source}, Depth + 1);"
                )
            else:
                if field.type_name in enum_map:
                    source = (
                        f"(declare Stored : constant Builders.Dynamic_Value := {source}; "
                        "begin (if Stored.Kind = Builders.Null_Value then "
                        "Builders.Number (0) else Stored))"
                    )
                converted = value_conversion(field, "Source", message_map, enum_map)
                present = present_expression(field, "Source", enum_map)
                lines.extend([
                    "      declare",
                    f"         Source : constant Builders.Dynamic_Value := {source};",
                    "      begin",
                    f"         if Source.Kind /= Builders.Null_Value and then ({present}) then",
                    f"            Value.{component} := (Present => True, Value => {converted});",
                    "         end if;",
                    "      end;",
                ])
        lines.extend([
            "      return Value;",
            "   exception",
            "      when others =>",
            f"         {release_contents_name(message.name)} (Value);",
            "         raise;",
            f"   end {native_record(message.name)};",
            "",
        ])
        if message.name in access_targets:
            lines.extend([
                f"   function {native_access(message.name)}",
                "     (Build : Builders.Builder; Item : Builders.Dynamic_Value;",
                f"      Depth : Natural) return {target}_Access",
                "   is",
                f"      Value : {target} := {native_record(message.name)} (Build, Item, Depth);",
                "   begin",
                f"      return new {target}'(Value);",
                "   exception",
                "      when others =>",
                f"         {release_contents_name(message.name)} (Value);",
                "         raise;",
                f"   end {native_access(message.name)};",
                "",
            ])

    lines.extend([
        "   function Convert_Native_Node",
        "     (Build : Builders.Builder; Item : Builders.Dynamic_Value;",
        "      Depth : Natural) return Node_Access is",
        "   begin",
        f"      if Depth > {MAXIMUM_DEPTH} then",
        "         raise Constraint_Error with \"excessive native AST recursion\";",
        "      end if;",
        "      if Item.Kind = Builders.Null_Value then",
        "         return new Node'(Kind => No_Node);",
        "      elsif Item.Kind = Builders.List_Value then",
    ])
    list_target = message_name("List")
    lines.extend([
        f"         return new Node'(Kind => Node_{list_target},",
        f"                          {list_target}_Payload =>",
        f"                            {native_record('List')} (Build, Item, Depth + 1));",
        "      elsif Item.Kind /= Builders.Object_Value then",
        "         raise Constraint_Error with \"native node object required\";",
        "      end if;",
    ])
    first = True
    for field in node.fields:
        target = message_name(field.type_name)
        keyword = "if" if first else "elsif"
        first = False
        lines.extend([
            f"      {keyword} Build.Object_Type (Item) = \"{field.type_name}\" then",
            "         declare",
            f"            Value : {target} := {native_record(field.type_name)}",
            "              (Build, Item, Depth + 1);",
            "         begin",
            f"            return new Node'(Kind => Node_{target},",
            f"                             {target}_Payload => Value);",
            "         exception",
            "            when others =>",
            f"               {release_contents_name(field.type_name)} (Value);",
            "               raise;",
            "         end;",
        ])
    lines.extend([
        "      else",
        "         raise Constraint_Error with",
        "           \"unknown native node type \" & Build.Object_Type (Item);",
        "      end if;",
        "   end Convert_Native_Node;",
        "",
        "   function Convert_Native_Root",
        "     (Build : Builders.Builder; Root : Builders.Dynamic_Value)",
        "      return Parse_Result",
        "   is",
        "      Value : Parse_Result;",
        "   begin",
        f"      Value.Version := (Present => True, Value => {version_number});",
        "      if Root.Kind not in Builders.Null_Value | Builders.List_Value then",
        "         raise Constraint_Error with \"native statement list required\";",
        "      end if;",
        "      for Index in 1 .. Build.Length (Root) loop",
        "         declare",
        "            Item : constant Builders.Dynamic_Value := Build.Element (Root, Index);",
        "            Raw  : Raw_Stmt_Access;",
        "         begin",
        "            if Item.Kind = Builders.Object_Value",
        "              and then Build.Object_Type (Item) = \"RawStmt\"",
        "            then",
        "               Raw := Convert_Native_Raw_Stmt_Access (Build, Item, 1);",
        "            else",
        "               Raw := new Raw_Stmt;",
        "               Raw.Statement :=",
        "                 (Present => True, Value => Convert_Native_Node (Build, Item, 1));",
        "            end if;",
        "            Value.Statements.Append (Raw);",
        "         exception",
        "            when others =>",
        "               Release (Raw);",
        "               raise;",
        "         end;",
        "      end loop;",
        "      return Value;",
        "   exception",
        "      when others =>",
        "         Release_Contents_Parse_Result (Value);",
        "         raise;",
        "   end Convert_Native_Root;",
        "",
        "   Build        : aliased Builders.Builder;",
        "   Native_Root  : Builders.Dynamic_Value;",
        "   Error_Offset : Natural := 0;",
        "   Success      : Boolean := False;",
        "   Failure      : Ada.Strings.Unbounded.Unbounded_String;",
        "begin",
        "   for Index in SQL'Range loop",
        "      if SQL (Index) = Character'Val (0) then",
        "         Clear (Result);",
        "         Result.Source_Text :=",
        "           Ada.Strings.Unbounded.To_Unbounded_String (SQL);",
        "         Result.Diagnostic_Message :=",
        "           Ada.Strings.Unbounded.To_Unbounded_String",
        "             (\"SQL input contains an embedded NUL byte\");",
        "         Result.Diagnostic_Position := Index - SQL'First + 1;",
        "         return;",
        "      end if;",
        "   end loop;",
        *(
            [
                "   if Options /= Default_Options then",
                "      raise Unsupported_Parse_Options with",
                "        \"PostgreSQL 14's native parser supports only Default_Options\";",
                "   end if;",
            ]
            if major == 14
            else []
        ),
        "   Clear (Result);",
        "   Result.Source_Text := Ada.Strings.Unbounded.To_Unbounded_String (SQL);",
        "   Parser.Parse",
        "     (SQL, Options, Build, Native_Root, Error_Offset, Failure, Success);",
        "   if not Success then",
        "      Result.Diagnostic_Message := Failure;",
        "      Result.Diagnostic_Position :=",
        "        (if SQL'Length = 0 then 0 else Error_Offset + 1);",
        "      return;",
        "   end if;",
        "   Result.Root := Convert_Native_Root (Build, Native_Root);",
        "   Result.Valid := True;",
        "exception",
        "   when others =>",
        "      Clear (Result);",
        "      raise;",
        "end Parse;",
        "",
    ])
    return "\n".join(lines)


def write_if_changed(path: Path, contents: str, check: bool) -> None:
    old = path.read_text() if path.exists() else None
    if check:
        if old != contents:
            raise SystemExit(f"generated direct owned parser is stale: {path}")
    elif old != contents:
        path.write_text(contents)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--major", type=int, required=True)
    parser.add_argument("--proto", type=Path, required=True)
    parser.add_argument("--vendor", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    all_messages, all_enums = parse_proto(args.proto)
    messages, enums = reachable_schema(all_messages, all_enums)
    clang_root, _ = clang_ast(args.vendor)
    source_enums = clang_enum_values(clang_root)
    version_header = args.vendor / "src" / "postgres" / "include" / "pg_config.h"
    version_match = re.search(
        r"^#define\s+PG_VERSION_NUM\s+(\d+)\s*$",
        version_header.read_text(),
        re.MULTILINE,
    )
    if version_match is None:
        raise ValueError(f"PG_VERSION_NUM is missing from {version_header}")
    output = args.output / f"flyology-postgres-sql-ast-v{args.major}-parse.adb"
    write_if_changed(
        output,
        generate(args.major, int(version_match.group(1)), messages, enums, source_enums),
        args.check,
    )
    print(
        f"{'verified' if args.check else 'generated'} PostgreSQL {args.major} "
        f"owned parser"
    )


if __name__ == "__main__":
    main()
