#!/usr/bin/env python3
"""Generate exhaustive visitors for the owned PostgreSQL AST."""

from __future__ import annotations

import argparse
from pathlib import Path

from generate_ada import (
    Message,
    accessor_name,
    message_name,
    parse_proto,
    reachable_schema,
)


def callback_name(prefix: str, name: str) -> str:
    return prefix + "_" + message_name(name)


def walk_name(name: str) -> str:
    return "Walk_" + message_name(name)


def generate_spec(major: int, messages: list[Message]) -> str:
    lines = [
        "--  Generated by tools/generate_owned_visitors.py.  Do not edit.",
        'pragma Style_Checks ("M160");',
        "",
        f"package Flyology.Postgres.SQL.AST.V{major}.Visitors is",
        "",
        "   type Traversal_Control is",
        "     (Continue_Traversal, Skip_Children, Stop_Traversal);",
        "",
        "   type Visitor is abstract tagged limited null record;",
        "",
    ]
    for message in messages:
        target = message_name(message.name)
        lines.extend([
            f"   procedure {callback_name('Enter', message.name)}",
            "     (Self    : in out Visitor;",
            f"      Item    : {target};",
            "      Control : in out Traversal_Control) is null;",
            "",
            f"   procedure {callback_name('Leave', message.name)}",
            "     (Self : in out Visitor;",
            f"      Item : {target}) is null;",
            "",
        ])
    lines.extend([
        "   procedure Traverse",
        "     (Self : in out Visitor'Class;",
        "      Tree : Owned_Syntax_Tree)",
        "     with Pre => Tree.Valid;",
        "   --  Visit the complete valid tree in depth-first, source-field order.",
        "",
        "   procedure Traverse",
        "     (Self : in out Visitor'Class;",
        "      Root : Parse_Result);",
        "   --  Visit an owned parse-result record without requiring its owner.",
        "",
        "   procedure Traverse",
        "     (Self : in out Visitor'Class;",
        "      Root : Node_Access);",
        "   --  Visit a node subtree.  A null root performs no callbacks.",
        "",
        "   --  Enter callbacks begin with Continue_Traversal.  They may choose",
        "   --  Skip_Children to omit that message's descendants while retaining",
        "   --  its matching Leave callback, or Stop_Traversal to end immediately.",
        "   --  Exceptions from callbacks propagate and do not promise balanced",
        "   --  Leave callbacks.  Traversal is read-only and does not take ownership.",
        "",
        f"end Flyology.Postgres.SQL.AST.V{major}.Visitors;",
        "",
    ])
    return "\n".join(lines)


def child_walk_lines(
    message: Message,
    message_map: dict[str, Message],
) -> list[str]:
    lines: list[str] = []
    for field in message.fields:
        if field.type_name not in message_map:
            continue
        component = accessor_name(field)
        child_walk = walk_name(field.type_name)
        if field.repeated:
            lines.extend([
                f"            for Child of Item.{component} loop",
                "               exit when State.Stopped;",
                "               if Child /= null then",
                f"                  {child_walk} (Self, Child.all, State);",
                "               end if;",
                "            end loop;",
            ])
        else:
            lines.extend([
                f"            if Item.{component}.Present",
                f"              and then Item.{component}.Value /= null",
                "            then",
                f"               {child_walk}",
                f"                 (Self, Item.{component}.Value.all, State);",
                "            end if;",
            ])
    return lines


def generate_body(major: int, messages: list[Message]) -> str:
    message_map = {item.name: item for item in messages}
    node = message_map["Node"]
    lines = [
        "--  Generated by tools/generate_owned_visitors.py.  Do not edit.",
        "pragma Style_Checks (Off);",
        "",
        f"package body Flyology.Postgres.SQL.AST.V{major}.Visitors is",
        "",
        "   type Traversal_State is record",
        "      Stopped : Boolean := False;",
        "   end record;",
        "",
    ]
    for message in messages:
        lines.extend([
            f"   procedure {walk_name(message.name)}",
            "     (Self  : in out Visitor'Class;",
            f"      Item  : {message_name(message.name)};",
            "      State : in out Traversal_State);",
        ])
    lines.append("")

    for message in messages:
        target = message_name(message.name)
        walker = walk_name(message.name)
        enter = callback_name("Enter", message.name)
        leave = callback_name("Leave", message.name)
        lines.extend([
            f"   procedure {walker}",
            "     (Self  : in out Visitor'Class;",
            f"      Item  : {target};",
            "      State : in out Traversal_State)",
            "   is",
            "      Control : Traversal_Control := Continue_Traversal;",
            "   begin",
            "      if State.Stopped then",
            "         return;",
            "      end if;",
            f"      {enter} (Self, Item, Control);",
            "      case Control is",
            "         when Stop_Traversal =>",
            "            State.Stopped := True;",
            "            return;",
            "         when Skip_Children =>",
            "            null;",
            "         when Continue_Traversal =>",
        ])
        if message.name == "Node":
            lines.extend([
                "            case Item.Kind is",
                "               when No_Node =>",
                "                  null;",
            ])
            for field in node.fields:
                target_name = message_name(field.type_name)
                lines.extend([
                    f"               when Node_{target_name} =>",
                    f"                  {walk_name(field.type_name)}",
                    f"                    (Self, Item.{target_name}_Payload, State);",
                ])
            lines.append("            end case;")
        else:
            children = child_walk_lines(message, message_map)
            lines.extend(children if children else ["            null;"])
        lines.extend([
            "      end case;",
            "      if not State.Stopped then",
            f"         {leave} (Self, Item);",
            "      end if;",
            f"   end {walker};",
            "",
        ])

    lines.extend([
        "   procedure Traverse",
        "     (Self : in out Visitor'Class;",
        "      Tree : Owned_Syntax_Tree)",
        "   is",
        "      State : Traversal_State;",
        "   begin",
        "      Walk_Parse_Result (Self, Tree.Root, State);",
        "   end Traverse;",
        "",
        "   procedure Traverse",
        "     (Self : in out Visitor'Class;",
        "      Root : Parse_Result)",
        "   is",
        "      State : Traversal_State;",
        "   begin",
        "      Walk_Parse_Result (Self, Root, State);",
        "   end Traverse;",
        "",
        "   procedure Traverse",
        "     (Self : in out Visitor'Class;",
        "      Root : Node_Access)",
        "   is",
        "      State : Traversal_State;",
        "   begin",
        "      if Root /= null then",
        "         Walk_Node (Self, Root.all, State);",
        "      end if;",
        "   end Traverse;",
        "",
        f"end Flyology.Postgres.SQL.AST.V{major}.Visitors;",
        "",
    ])
    return "\n".join(lines)


def write_if_changed(path: Path, contents: str, check: bool) -> None:
    old = path.read_text() if path.exists() else None
    if check:
        if old != contents:
            raise SystemExit(f"generated owned visitor is stale: {path}")
    elif old != contents:
        path.write_text(contents)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--major", type=int, required=True)
    parser.add_argument("--proto", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    all_messages, all_enums = parse_proto(args.proto)
    messages, _ = reachable_schema(all_messages, all_enums)
    stem = f"flyology-postgres-sql-ast-v{args.major}-visitors"
    write_if_changed(
        args.output / f"{stem}.ads",
        generate_spec(args.major, messages),
        args.check,
    )
    write_if_changed(
        args.output / f"{stem}.adb",
        generate_body(args.major, messages),
        args.check,
    )
    print(
        f"{'verified' if args.check else 'generated'} PostgreSQL {args.major} "
        f"owned visitors: {len(messages)} messages"
    )


if __name__ == "__main__":
    main()
