name = "psqlish"
description = "A small, bounded psql-like client built on Flyology Postgres"
version = "0.1.1-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-postgres"
tags = ["example", "postgres", "client", "repl"]

executables = ["psqlish"]

[[depends-on]]
flyology_postgres = "*"
flyology = "~0.1.1-dev"
linenoise_ada = "^1.1.2"

[[pins]]
flyology_postgres = { path = "../.." }

[[actions]]
type = "test"
command = ["./scripts/test.sh"]
