name = "flyology_postgres_sql"
description = "Versioned PostgreSQL raw SQL parser and Ada syntax tree"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-postgres"
tags = ["ada", "postgres", "sql", "parser", "ast"]

project-files = ["sql.gpr"]

[[depends-on]]
flyology_postgres_sql_v14 = "*"
flyology_postgres_sql_v15 = "*"
flyology_postgres_sql_v16 = "*"
flyology_postgres_sql_v17 = "*"
flyology_postgres_sql_v18 = "*"

[[pins]]
flyology_postgres_sql_v14 = { path = "v14" }
flyology_postgres_sql_v15 = { path = "v15" }
flyology_postgres_sql_v16 = { path = "v16" }
flyology_postgres_sql_v17 = { path = "v17" }
flyology_postgres_sql_v18 = { path = "v18" }
